### ISSUE TITLE
Bluetooth disconnected!

### ISSUE THREAD

**Issue by khbue** [itsMeDavidV/Watchla-Support#100]
After going through the procedure in connecting Apple Watchla Bluetooth with Model 3, Watchla shows Bluetooth disconnected.
Please help!![image](https://user-images.githubusercontent.com/98472510/213885439-490000d8-3053-4596-a16a-4f2b8c0c849e.jpeg)

**Comment by itsMeDavidV** [comment]
This could be because of a delay in reflecting connected status. Have you tried refreshing this by going back and then re-opening the Manage Bluetooth screen? 

Also you can check on the vehicle's side by going to Settings > Locks and checking to see if key you set up for Watchla is active or not.

**Comment by khbue** [comment]
Yes, was back in the car, trying to refresh. But in the car there is no key, except for our phones and key cards.
Can I reset the whole process to start with the procedure again?

**Comment by itsMeDavidV** [comment]
> Can I reset the whole process to start with the procedure again?

Yes, tap Delete BLE Data and restart the process.

Also by chance did you name the key that Watchla made in your vehicle?

Also sorry about this. This will be investigated and fixed if possible.

**Comment by khbue** [comment]
Thanks a lot!It works!!I deleted BLE Data and did a restart.Viele Grüße!  Best regards!Prof. Dr. Karl-Heinz BüttnerMobile:  +49 160 7559032Email:     ***@***.*** 22.01.2023 um 20:02 schrieb David Villegas ***@***.***>:﻿

Can I reset the whole process to start with the procedure again?

Yes, tap Delete BLE Data and restart the process.
Also by chance did you name the key that Watchla made in your vehicle?

**Comment by itsMeDavidV** [comment]
Sweet! I'm glad to hear this worked for you! Please feel free to reach out if you encounter anything else.
