### ISSUE TITLE
Problem with Siri shortcut to start climate 

### ISSUE THREAD

**Issue by mitsel2782** [itsMeDavidV/Watchla-Support#102]
I can start the climate from my phone app, but the Siri shortcut won’t work from my watch. Please advise. Thanks.

**Comment by itsMeDavidV** [comment]
Hi @mitsel2782 sorry to hear that. Is the climate shortcut not working for you via Siri or the Shortcuts app or both?

And what is the error messages afterwards?

**Comment by mitsel2782** [comment]
Just the Siri shortcut from the watch. The manual button from the watch or phone will turn on the climate. Mitch. Mitch Selbiger, Associate Broker, Sotheby’s International Realty, 18949 Coastal Highway, #304, Rehoboth Beach, DE. 19971, 410-274-3479 (cell) On Jan 26, 2023, at 2:43 PM, David Villegas ***@***.***> wrote:﻿
Hi @mitsel2782 sorry to hear that. Is the climate shortcut not working for you via Siri or the Shortcuts app or both?
And what is the error messages afterwards?

**Comment by itsMeDavidV** [comment]
@mitsel2782 what error message does Siri give you afterwards?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
