### ISSUE TITLE
Regarding watchla Apple Watch app

### ISSUE THREAD

**Issue by Flash0889** [itsMeDavidV/Watchla-Support#103]
When using the watch app and attempting to open the doors, the pictures open the opposite door. For example the picture that represents the drivers door actually opens the passenger door and that goes for all the doors.

**Comment by itsMeDavidV** [comment]
Hi @Flash0889 sorry about that. This issue has been fixed and the fix will be available in Watchla's upcoming update v3.02 in the coming days.

**Comment by Flash0889** [comment]
Awesome! Thanks for being so quick to update that.

**Comment by itsMeDavidV** [comment]
you're very welcome!

**Comment by itsMeDavidV** [comment]
Hi @Flash0889 just wanted to let you know that a new update (v3.02) has just been released that fixes the issue you described.

You can update here: https://apps.apple.com/us/app/watchla/id1546599747

Thank you for reporting this! Please don't hesitate to reach out with any other feedback you might have.
