### ISSUE TITLE
Cant connect to tesla via bluetooth

### ISSUE THREAD

**Issue by Blackpizza777** [itsMeDavidV/Watchla-Support#106]
Im trying to connect the watchla apl to tesla model 3 but im only getting this screen- see attached photos. Am i doing something wrong?
![Uploading 268E526B-F00B-48CD-B678-E3689A8C2A1E.jpeg…]()

**Comment by itsMeDavidV** [comment]
Hi @Blackpizza777 thanks for reporting this. Unfortunately for some reason it seems there is a GitHub error with your image causing it not to show. Could you try re-uploading it or alternatively you can email it here: david@watchla.app if that works better for you.

**Comment by bvstoronto** [comment]
I bought the app yesterday, I also face the same issue please help. 
I have Bluetooth enabled for Watchla (Paired iPhone -> Settings -> Watchla -> Bluetooth)
 Mobile Access is enabled on the vehicle touchscreen (Controls > Safety > Allow Mobile Access).
I already use tesla app on 3 phones. and use the same iphones as keys as well

 I placed the Key Card on the center console

when i try to start pairing from watchla for the watch, it gives following:
initializing...,  and after sometime it says  waiting,,,,,but nothing happens 

I tried rebooting watch, phone and even tesla. 

Other than bluetooth all other commands are working great!

**Comment by itsMeDavidV** [comment]
Hi @Blackpizza777 I just wanted to update you to let you know that a new Watchla update (v3.02) has been released that addresses an issue similar to what you have described here. You can update here: https://apps.apple.com/us/app/watchla/id1546599747

Please do let me know if this new update resolves this issue for you!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
