### ISSUE TITLE
Open doors glitch

### ISSUE THREAD

**Issue by SchulzeyBoy** [itsMeDavidV/Watchla-Support#108]
Hi, I LOVE the new Bluetooth connectivity for Apple Watch. It makes all the other Tesla-Apple watch apps obsolete imo.

One glitch though is that when opening doors it opens the door on the opposite side of the car to what I select on the watch. Could it be because our car is right-hand drive (Australia)?

Cheers,
Peter

**Comment by itsMeDavidV** [comment]
Hi @SchulzeyBoy I'm really glad you like Watchla! And thanks for reporting this. I'm happy to report this issue has been fixed and an update with the fix (v3.02) will be coming this week!

**Comment by SchulzeyBoy** [comment]
Hi David,

Thanks for that, great service.

Just one other small annoyance, when I use Siri to ask something about the car (eg. is it locked?) it responds with “Ok viewing, your Tesla is locked”. Does it need to say “Ok viewing…” first? I could live with the Ok, but “viewing”?

Cheers,
Peter

**Comment by itsMeDavidV** [comment]
@SchulzeyBoy You're very welcome and thank you! I just wanted to let you know that v3.02 was released earlier today which fixes this issue. 

You can update here: https://apps.apple.com/us/app/watchla/id1546599747

Thanks for reporting this. Please don't hesitate to reach out with any other feedback you may have!

Also regarding Siri responses, unfortunately Watchla has limited control over some of the words Siri chooses to use. Hopefully in the future Apple will continue to expand Siri's capabilities so App Developers can deliver better experiences :/
