### ISSUE TITLE
Option to start Precondition from complication 

### ISSUE THREAD

**Issue by runeld** [itsMeDavidV/Watchla-Support#112]
Currently trying to switch from Tessie to Watchla, but I'm really missing the option to start cabin/battery preconditioning directly from a complication.

As far as I can tell it's possible to select a "climate status" complication, from which to start preconditioning, but not to start preconditioning directly?

**Comment by itsMeDavidV** [comment]
Hi @runeld you're going to want to use the "Toggle max defrost" complication. This complication will trigger preconditioning for both the cabin & battery. 

This complication was renamed from "Toggle Preconditioning" to "Toggle max defrost" to be in line with Tesla, after they made a similar naming change.

Nonetheless, Toggle Max Defrost whether in Watchla or the Tesla app will trigger the following api url: `/api/1/vehicles/{id}/command/set_preconditioning_max` which will heat up both your cabin and battery as well as turn on defrosters.

Hope this helps. Please reach out if you have any questions!
