### ISSUE TITLE
Error Signing In (official update thread)[Fixed]

### ISSUE THREAD

**Issue by kwanck** [itsMeDavidV/Watchla-Support#113]
i cannot signing in to the apps

**Comment by buliwyf42** [comment]
Same here, login not possible. On the other hand, the login with the iOS and Mac Version of “Auth for tesla” does also not work. Perhaps a Tesla issue. Both worked for my account a few days ago. I tried to set up my wife account. "Login not possible."
Tesla Token on Android still works for creating tokens. But they are not accepted in Watchla.

**Comment by kwanck** [comment]
thanks man, wait and see when they will solve it then.

**Comment by itsMeDavidV** [comment]
Hi @buliwyf42 @kwanck Unfortunately this is a widespread issue that affects many platforms using the Tesla API, not just Watchla. This is a top priority issue and we are investigating right now.

**Comment by itsMeDavidV** [comment]
This will be the official update thread for this issue. Additionally you can also receive updates on [Twitter](https://twitter.com/WatchlaApp/status/1625920793279619072?s=20&t=pA8b9jtpaYr1v7OQrwoEmw)

Any new updates or info regarding this issue will be in the comments below. Thank you all for you patience as this is diligently investigated.

**Comment by itsMeDavidV** [comment]
**Update: If you can get a Tesla API token, you can use it to successfully sign in to Watchla.** Just tap the "Sign in with Token" option in the sign in screen.

**Comment by itsMeDavidV** [comment]
**Update:** the issue has been identified and a solution has also been identified which is now being tested at this moment.

Once a solution is solidified an update will be prepared and Watchla will ask Apple to expedite the update review & release.

**Comment by itsMeDavidV** [comment]
**Update:** The fix to this issue has been tested and packaged in new update v3.3 which is currently in the process of being sent to Apple.

More to come.

**Comment by itsMeDavidV** [comment]
Update: Watchla has sent Apple the new update for review and they have agreed to expedite their review process for Watchla :)

If all goes well, Watchla's new update will be available in the coming hours.

**Comment by itsMeDavidV** [comment]
Apple just notified Watchla that they are currently reviewing v3.3 now.

**Comment by kwanck** [comment]
thank you very much for the fast response, the problem has fixed and happy using now, many thanks watchla!

**Comment by itsMeDavidV** [comment]
@kwanck You're very welcome, glad to hear that!

**Comment by itsMeDavidV** [comment]
Happy to announce that Watchla update v3.3, which contains the fix for this issue, was released a made available for download earlier today. If you are experiencing this sign in issue, please make sure to [update](https://apps.apple.com/us/app/watchla/id1546599747)

This issue will stay open for a day or so that others who may not have updated yet can see this thread.

**Comment by itsMeDavidV** [comment]
Given that it's been a bit of time for people to see, closing this.
