### ISSUE TITLE
Remote Start not working with new Bluetooth setup

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#114]
I have tried several times, across version iterations, to remote start the car using my watch while set up with Bluetooth. Never works. When I turn off BLE (disable Bluetooth) then I am able to use remote start via Web instead of Bluetooth. Will Watch in Bluetooth mode eventually be able to Remote Start? That's the main thing I use Watchla for, so it's sad not to have it work in that mode.

**Comment by itsMeDavidV** [comment]
@ttwajsb noted. Sorry about this. Will investigate and get back to you.

**Comment by ttwajsb** [comment]
Been seeing and getting notifications about using Bluetooth with Watch. Just tried again and for the attached symptoms. Please advise. 
Watch Series 4; iPhone 14 Pro; both current OS and Watchla app
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/9358980/f627a81c-1f26-4227-801d-12205a3175c7)
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/9358980/55527481-e526-4876-99a3-140bb685eaab)
