### ISSUE TITLE
Unable to retrieve vehicle data

### ISSUE THREAD

**Issue by ArmandAgopian** [itsMeDavidV/Watchla-Support#117]
Hi I've been unable to use the watch for a few months. It gets stuck loading data and nothing loads.

Steps I've tried:
-log in again multiple times with credentials
-refresh watch app
-reinstall watch and phone app

The Tesla app and Tessie app both work and retrieve data just fine.

**Comment by ArmandAgopian** [comment]
I'd also like to mention that this began around the time of the 2.0 update. The refreshing has been very finicky since then.

**Comment by itsMeDavidV** [comment]
Hi @ArmandAgopian very sorry to hear that. Can you send your Support code to my email: david@watchla.app so that I can check any relevant error logs and report back on what exactly is happening and what next steps might be?

**Comment by ArmandAgopian** [comment]
![image](https://user-images.githubusercontent.com/14142757/222247255-98b413bc-410b-46d6-800a-29a9d1a10604.png)

I can't get any code because the app won't stop showing the progressview. My email is armandagopian457@gmail.com, I'm not sure if you're able to track that way.

**Comment by ArmandAgopian** [comment]
Got it to work finally, sent you an email

**Comment by itsMeDavidV** [comment]
Got it! Will check and report back.

**Comment by ArmandAgopian** [comment]
Any update?

**Comment by itsMeDavidV** [comment]
@ArmandAgopian emailed you!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
