### ISSUE TITLE
Can get Bluetooth to connect

### ISSUE THREAD

**Issue by KenReneris** [itsMeDavidV/Watchla-Support#119]
I have 2 Tesla’s and my watch has connected to 1 of them but won’t connect to the other.   I select “Start->I’m ready” and the watch goes to “initializing” and just sits there.   I’ve tried uninstalling the watch app, phone app, resetting the blue tooth data option, resetting watch preferences, rebooting the car, changing “allow mobile access” in the car on&off.  Power cycling the watch .. which gets to “waiting” and then stopping.

If it helps, the very first time I tried in this car it made it slightly further… the watch showed “use cardkey” and I proceeded past that and it got stuck on some sort finalizing screen.  I eventually aborted that and the account didn’t show up in the car.  Since then I tried all the above and then tried on my other tesla were it worked fine.  I’m back to this telsa and it’s still stuck.

Any ideas?

**Comment by itsMeDavidV** [comment]
Hi @KenReneris sorry to hear that. Can you send over your Watchla support code to my email: david@watchla.app so I can check any relevant error logs and get back to you with a clearer picture of what's happening in the background?

**Comment by itsMeDavidV** [comment]
Hi @KenReneris I'm happy to report that a fix is ready to be tested! An email with additional info on this was sent out to you.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
