### ISSUE TITLE
Not able to connect to car

### ISSUE THREAD

**Issue by spongerius** [itsMeDavidV/Watchla-Support#123]
Hi,

When I opened the app on the phone and on my watch, I get the spinning icon and then it says can’t connect. 

This has been happening for the past few days

**Comment by itsMeDavidV** [comment]
Hi @spongerius Watchla relies on Tesla Servers to connect to your vehicle. I would recommend ensuring that both your vehicle and devices have ideal connections to the internet. Sometimes parking in a garage or parking garage or connecting to home WiFi from a long distance can hinder the vehicle's ability to connect to the internet at ideal speeds. Additionally if you actively keep Sentry Mode off, this can also be a contributor as your vehicle will be more prone to falling into deep sleep, which in turn causes your vehicle to take longer to wake and connect to Tesla Servers when prompted to do so.

Additionally, if you send you Watchla support code to my email: david@watchla.app I'd be happy to check any associated error logs to see if there is anything irregular occurring.

Hope this finds you well,
-David

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
