### ISSUE TITLE
Siri in french

### ISSUE THREAD

**Issue by Steffi3rd** [itsMeDavidV/Watchla-Support#124]
Hi from France 🇫🇷

I just bought Watchla yesterday and it works great. 😃

I can unlock Tesla and drive and lock it using the Apple Watch (Ultra). That's what I wanted. No iPhone around.

But I saw two cons : 
- **Need to open the app** to unlock Tesla, I knew before buying it that only "Stats" can do that _at this time_. I hope it will be add soon on Watchla
- App is english but it's ok. But more important, Siri is only english so it seems useless for french users

Is it possible to add French support? How to contribute?

Thank you for this app and good job!

**Comment by itsMeDavidV** [comment]
Hi @Steffi3rd ! 

So all Apple Watch apps (besides health related apps, with special permissions granted by Apple) are limited in the amount of time they can process Bluetooth communications while in background, to preserve battery life. So while Watchla can passively unlock your vehicle from the background, it may not be able to do so every time as the limits set forth by watchOS are very restrictive. Here's a helpful tweet thread where you can read about this more extensively: https://twitter.com/WatchlaApp/status/1638373233115398145?s=20

Additionally I'm happy to report that French will be supported on Watchla soon! I'll have more details soon on how to contribute :)

As for Watchla Siri Shortcuts, you can always change the voice phrase to anything you want either in English or in French. Here is an example: https://twitter.com/WatchlaApp/status/1637906946186686465?s=20 

In the future when French is supported on Watchla, these voice phrases will automatically be in French for French users

Hope this info finds you well, please don't hesitate to reach out with any questions!
