### ISSUE TITLE
App Icon looks blurry on Apple Watch

### ISSUE THREAD

**Issue by Steffi3rd** [itsMeDavidV/Watchla-Support#125]
<img width="56" alt="Capture d’écran 2023-03-27 à 10 42 47" src="https://user-images.githubusercontent.com/814410/227893531-976fe932-2bf5-4021-93d6-16e1dbde904f.png">

This icon looks blurry on Apple Watch. I think it's because of the white halo

**Comment by itsMeDavidV** [comment]
Hi @Steffi3rd the bolt indeed has a Neon blur :) also this image is extremely tiny as it was designed to fit in a very tiny space. So it doesn't take much expanding for it to blur or pixilate dramatically. You can always see what the icon truly looks like on the App Store screen as the icon there is 1024 px which is the biggest an app icon can get!
