### ISSUE TITLE
Missing unlatch door watch

### ISSUE THREAD

**Issue by nutsofamily** [itsMeDavidV/Watchla-Support#128]
There is no “unlatch door” in Apple Watch

**Comment by itsMeDavidV** [comment]
Hi @nutsofamily unlatch door is "Open Doors". 

In the Tesla app, the UI is more focused on unlatching the driver door in the even the handle inoperable, hence why it's called "Unlatch door", however in Watchla you can open all doors and for Model X you can open Falcon Wing doors, so it's better aptly named "Open Doors".

You can access the open doors screen by going to All Commands in the watch app. Additionally, you can add a shortcut button to the Open Doors screen to your Home Screen on the watch app as well as individual doors to open or all doors, all at once. 

You can customize your Home Screen for the watch app in the iOS app by going to Preferences -> Custom Layout.

Hope this info finds you well, please don't hesitate to reach out with any questions.

**Comment by nutsofamily** [comment]
I tried to add a complication for open door (unlatch door eg if hands full) but there is no shortcut for that listed in the possible complications. Yes I can see it on the iPhone app, but it is not an option in the watch. I have to do a complication to Watchla first and then there is the open latch so that is 2 separate things I have to do. I would like to press unlatch door (your unlock door) with just 1 button press in Apple watch....

**Comment by nutsofamily** [comment]
![w](https://user-images.githubusercontent.com/24458433/229225894-ebaa571e-ae6e-4347-9c63-b2753a7b3ef5.PNG)

**Comment by itsMeDavidV** [comment]
Ah ok, so if I'm reading you right, you're requesting that there be a watch face complication for opening the door?

If that's the case, I'm happy to report that this is coming to Watchla along with a Siri Shortcut for open doors.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
