### ISSUE TITLE
Bluetooth not getting past “connecting”

### ISSUE THREAD

**Issue by caans** [itsMeDavidV/Watchla-Support#129]
I have latest Apple Watch ultra and model x 2017 and just bought this app.

My issue is the Bluetooth connection. I have my 2017 model X already allowing mobile access. My iPhone key is working. My Apple Watch Bluetooth turns on and searching other Bluetooth devices but nothing happens. I followed the instructions to be in the car.

Bluetooth set up is stuck on “connecting” any help would be very much appreciated.

**Comment by itsMeDavidV** [comment]
Hi @caans unfortunately your Tesla most likely doesn't support Phone Key. It's believed that only refreshed Model X's built on or after 2021 support Phone Key. 

In general, if you are able to connect to your vehicle from the official Tesla app over Bluetooth (not just the internet) your vehicle supports Phone Key. You can also check by going to Locks -> Keys in your Tesla's settings. If you see your phone in the list of keys, then your vehicle most likely supports Phone Key.

You can read more about this on Watchla's FAQs here: https://watchla.app/faqs/ under the Q: "Is my vehicle compatible with Watchla’s Bluetooth connectivity features?"

Hope this info helps, please don't hesitate to reach out with any questions.

-David

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
