### ISSUE TITLE
Bluetooth status “Disconnected”

### ISSUE THREAD

**Issue by mkaiserco** [itsMeDavidV/Watchla-Support#130]
Just installed Watchla and connected to my Tesla. I then (accidentally) removed the newly added Key. When I realised what I had done, I then hit Delete BLE Data. Now I can’t figure out how to reconnect and add a Key.

The Bluetooth Status in the Watchla Preferences say’s Disconnected.

I have deleted Watchla from my iPhone and watch and re-added. But I still can’t connect and get a Key added. Suggestion?

**Comment by itsMeDavidV** [comment]
Hi @mkaiserco I would recommend deleting your BLE data again. This can be done in the Manage Bluetooth screen at the bottom of the screen. This will reset your Bluetooth data and settings and should bring up the Bluetooth setup screen.

If the Bluetooth setup screen does not appear for you, please reply with your support code and I will investigate.

**Comment by mkaiserco** [comment]
Yes, deleting (again) solved the problem. Thank you.
______________________
Mike Kaiser
***@***.***

**Comment by itsMeDavidV** [comment]
Awesome! I'm very glad to hear that. Please don't hesitate to reach out if there is anything else that arises.
