### ISSUE TITLE
Bluetooth setup doesn’t recognize Tesla card key on console

### ISSUE THREAD

**Issue by Tntow56** [itsMeDavidV/Watchla-Support#133]

**Comment by itsMeDavidV** [comment]
Hi @Tntow56 please send your Watchla support code to https://watchla.app/contact with a link to this issue so that this can be investigated. 

Thanks,
-David

**Comment by rgurrala** [comment]
hello! i have the same issue. this is my support code- iEn3TYYotN

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
