### ISSUE TITLE
Watchla will not connect to my new model S via Bluetooth

### ISSUE THREAD

**Issue by MI10000** [itsMeDavidV/Watchla-Support#138]
It worked for a while then it stopped. I tried reinstalling and no connection possible it just keeps spinning.

**Comment by itsMeDavidV** [comment]
Hi @MI10000 can you please send over your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue. Thanks!

**Comment by MI10000** [comment]
Thank you for your email. I eventually uninstalled and reinstalled everything and now it works again and it’s awesome. I’ll let you know if I have any issues down the road. Otherwise thank you so much.Sent from my iPhoneOn Jun 25, 2023, at 5:08 PM, David Villegas ***@***.***> wrote:﻿
Hi @MI10000 can you please send over your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue. Thanks!
