### ISSUE TITLE
No Watchla app appearing on my Apple Watch

### ISSUE THREAD

**Issue by LoloHi75** [itsMeDavidV/Watchla-Support#141]
Hi! I just downloaded your app willing to use it on my Apple Watch (model 1, 42mm alu) and I don’t see it visible in the list of apps. I reinitialized my Apple Watch but nothing changes. Both iOS and watch OS version are uptodate. I hope I didn’t spend 7,99€ for nothing. 
Thanks by advance for your support and reply. 
![IMG_7762](https://github.com/itsMeDavidV/Watchla-Support/assets/138584059/8f5b4bf3-9c80-4887-8142-dbe23107763d)
Code: ukm96gzW3p

**Comment by itsMeDavidV** [comment]
Hi @LoloHi75 you can always download the Watchla watch app directly from the App Store app on your Apple Watch. 

Unfortunately, Watchla has no control over downloads or installation, so if you find yourself still not being able to download the app, I’d reach out to Apple Support as they would be best equipped to help you through this issue.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
