### ISSUE TITLE
Not able to LogIn

### ISSUE THREAD

**Issue by heuselNET** [itsMeDavidV/Watchla-Support#142]
Hi Folks,

this happens direct after setting mail  and hitting OK

![IMG_3665](https://github.com/itsMeDavidV/Watchla-Support/assets/139992075/474f3650-ce9f-452e-909d-52465473463c)

**Comment by itsMeDavidV** [comment]
Hi @heuselNET are you using a VPN? Additionally can you send over your support code to https://watchla.app/contact so this can be investigated? Thanks!

**Comment by heuselNET** [comment]
hi @itsMeDavidV, no VPN at all. No Private Relay or something 🤷🏼
Thanks

**Comment by heuselNET** [comment]
Hi, today i tried again on cellular network and it works. Maybe that or problem systemside at tesla.
Thanks for your reply.
