### ISSUE TITLE
Won’t authorise via Tesla app on iPhone 

### ISSUE THREAD

**Issue by zivbri** [itsMeDavidV/Watchla-Support#143]
Hi. I have just downloaded and tried to authenticate via Tesla app. It says access denied

**Comment by itsMeDavidV** [comment]
Hi @zivbri can you please send over your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue, thanks!

**Comment by zivbri** [comment]
Hi David.

Any update ?

Thanks

Brian

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zivbri** [comment]
[Image.png.png]

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itsMeDavidV** [comment]
@zivbri Not as of yet. I will update this issue as soon as there are updates. For now, you can always sign in with a Tesla token. 

If you're not familiar with obtaining a Tesla token you can always generate one on Watchla's sister app, Authla: https://apps.apple.com/us/app/authla/id1546597644

Additionally another alternative to Authla is Auth app for Tesla: https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613

**Comment by itsMeDavidV** [comment]
Hi @zivbri I have a few questions for you in an effort to try to pinpoint what might have caused this issue for you:

• Did this issue occur on your very first attempt at signing in? If not, approximately how many sign in attempts were made before this issue occurred?

• Have you tried signing in on both cellular and WiFi?

• Are you able to sign in with a Tesla token?

**Comment by kentgoldman** [comment]
I am having this same issue on my initial sign in. I am signing in over WiFi and have not tried a token yet.

**Comment by kentgoldman** [comment]
![IMG_1772](https://github.com/itsMeDavidV/Watchla-Support/assets/25410406/663fd735-5797-4449-8c56-bf0576cff500)

This is what I see after the login screen.

**Comment by itsMeDavidV** [comment]
Hi @kentgoldman as a work around you can try switching connections (eg: WiFi -> Cellular) or using a token to sign in. If you're not familiar with obtaining a Tesla token on your own, you can easily get one on Authla: https://apps.apple.com/us/app/authla/id1546597644

Unfortunately this is an issue that only affects some people and it's not known why yet, however it is being investigated.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
