### ISSUE TITLE
Bluetooth Disconnect 

### ISSUE THREAD

**Issue by Maisey1965** [itsMeDavidV/Watchla-Support#146]
My watchla app is able to do commands, but after I initially connected it as a phone key, it now continues to say ‘disconnected’ for Bluetooth and I can’t change that in any way, despite turning off and on my watch and my phone.
I’d like to be able to use my watch as a key to drive my Model Y if possible.  Any suggestions?

**Comment by itsMeDavidV** [comment]
Hi @Maisey1965 can you please send in your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue. Thanks!

**Comment by Maisey1965** [comment]
Hello, 

I'm happy to do that - where would I find my Watchla support code?

Thanks,

Kent
     On Wednesday, August 9, 2023 at 02:55:03 p.m. MDT, David Villegas ***@***.***> wrote:  
 
 


Hi @Maisey1965 can you please send in your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue. Thanks!

**Comment by JalinEnterprisesLLC** [comment]
I have the same issue of no Bluetooth digital key connection after installing tesla version 2023.26.7.  Series 6 Apple Watch / version 9.6 (20U73) software

**Comment by itsMeDavidV** [comment]
Hi all please see an update regarding this issue here: https://github.com/itsMeDavidV/Watchla-Support/issues/145#issuecomment-1672377383

**Comment by itsMeDavidV** [comment]
New update: a beta build that addresses this issue is available now, [please click here for more info](https://github.com/itsMeDavidV/Watchla-Support/issues/145#issuecomment-1674011453)

Also closing this issue and pushing this discussion to #145

**Comment by Maisey1965** [comment]
Hello, I’m a counselor not a tech person, so I don’t understand what it means to be closed and there’s a beta for this issue.
All I know is that my Watchla app on my watch regarding Bluetooth continues to be ‘disconnected’
I will hunt around to see if I can find the code you asked me to send 


Sent from My Kent's iPhone


On Thursday, August 10, 2023, 4:37 PM, David Villegas ***@***.***> wrote:




Closed #146 as completed.

**Comment by Maisey1965** [comment]
BEq5CeSibp
Is my code 


Sent from My Kent's iPhone


On Thursday, August 10, 2023, 8:31 PM, kmholl ***@***.***> wrote:

Hello, I’m a counselor not a tech person, so I don’t understand what it means to be closed and there’s a beta for this issue.
All I know is that my Watchla app on my watch regarding Bluetooth continues to be ‘disconnected’
I will hunt around to see if I can find the code you asked me to send 


Sent from My Kent's iPhone


On Thursday, August 10, 2023, 4:37 PM, David Villegas ***@***.***> wrote:




Closed #146 as completed.

**Comment by itsMeDavidV** [comment]
Hi @Maisey1965 thanks for providing your support code. After investigating, it seems that you are not facing the same issue as mentioned in #145 prior.

Have you tried deleting your Bluetooth data and re-setting up Bluetooth?

To delete your Bluetooth data, goto Preferences -> Manage Bluetooth -> Delete BLE Data.

Once you delete your Bluetooth data, try setting up Bluetooth--everything should then work normally.

Also be sure that the Tesla key card you are using when setting up your Watchla Bluetooth key is working and active.

Hope this helps!

**Comment by Maisey1965** [comment]
Hi David,
I tried to delete BLE DATA , hitting okay to delete,
Then it goes to either being stuck on scanning…
Or initializing…
And when I check the Watchla app again on my watch it shows That BLE is still there. So I try to delete it again, and it confirms that it has been deleted, and the same cycle repeats.
I’ve tried about 4 -5 times over the past 1/2 hour of trying to delete , Then “I’m ready”, then initializing or searching and then back to deleting BLE.
The journey continues.
All of my commands still work though, so happy about that.
kindly, 
Kent 


Sent from My Kent's iPhone


On Friday, August 11, 2023, 1:39 AM, David Villegas ***@***.***> wrote:




Hi @Maisey1965 thanks for providing your support code after investigating, it seems that you are not facing the same issue as mentioned in #145 prior.

Have you tried deleting your Bluetooth data and re-setting up Bluetooth?

To delete your Bluetooth data, goto Preferences -> Manage Bluetooth -> Delete BLE Data.

Once you delete your Bluetooth data, try setting up Bluetooth--everything should work.

Hope this helps!

**Comment by itsMeDavidV** [comment]
Unfortunately there still seems to be a small amount of people who still face this issue. Watchla will be releasing v3.4.8 which has prioritized a different way of identifying a Tesla via Bluetooth. This is a very new way for the 3rd party community (as in this was discovered literally today and has not been documented yet) so there will be some validation needed. 

Apple is currently reviewing v3.4.8 beta, however since it is Saturday night in California right now, this process might be delayed.

If you would like to help validate v3.4.8 beta and have not requested beta, please do so.

PS if you have not already, be sure to update Watchla to at least v3.4.7 as statistically speaking it should solve the issue for you.

**Comment by itsMeDavidV** [comment]
Hi everyone, the v3.4.8 update is now available on the [App Store](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747) and it should fix this issue for you.

Before testing please ensure that your *watch* app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.

Thank you again for your patience.

-David

**Comment by Maisey1965** [comment]
The App is working fully, after installing the newest version!
Great app 👍


Sent from My Kent's iPhone


On Sunday, August 13, 2023, 3:47 PM, David Villegas ***@***.***> wrote:




Hi everyone, the v3.4.8 update is now available on the App Store and it should fix this issue for you.

Before testing please ensure that your watch app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.

Thank you again for your patience.

-David

**Comment by itsMeDavidV** [comment]
@Maisey1965 Really glad to hear that and thank you!!
