### ISSUE TITLE
Bluetooth hang in “scanning…”

### ISSUE THREAD

**Issue by davidxdai** [itsMeDavidV/Watchla-Support#148]
In Tesla Model Y 2023 software 2023.26.7, restarted watch as well as the car, still not able to connect. My other key card and iPhone can connect via Bluetooth. I tried other TSLA key fob app, no issue.

**Comment by davidxdai** [comment]
Did resetting and restoring Apple Watch, now it’s working for Bluetooth.

**Comment by itsMeDavidV** [comment]
Hi @davidxdai thanks for reporting this, please be sure to update us if this happens again for you
