### ISSUE TITLE
Watchla no longer signs in

### ISSUE THREAD

**Issue by rossltmoss** [itsMeDavidV/Watchla-Support#15]
Since updating to iOS 15 watchla no longer signs in when using Authla . Have tried reinstalling but no longer working

**Comment by itsMeDavidV** [comment]
Hi @rossltmoss as of now Authla has not been optimized to run on iOS 15 beta. So I cannot guarantee how your experience will be on iOS 15. As the iOS 15 production update release nears closer, Authla will be tested/optimized for iOS 15. We should see the first update for Authla regarding iOS 15 most-likely in the first week of September.

As far as Watchla goes, early logs report that Watchla works well with WatchOS 8 beta.

**Comment by rossltmoss** [comment]
Thanks for the reply, after the last ios beta Authla is now working fine, and watchla has logged in ok. So it’s all looking good thanks

Sent with a Spark

**Comment by itsMeDavidV** [comment]
Sweet! Glad to hear that 👍
