### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by cynodom** [itsMeDavidV/Watchla-Support#150]
Hi,
I updated the app but I still can't connect with bluetooth.
I tried uninstalling the key on the car and the app from the phone but the bluetooth still won't connect.

Thanks

**Comment by JalinEnterprisesLLC** [comment]
Same 3.4.6 update Bluetooth still just continues to report “scanning”.  Removed Key from Tesla and reset Bluetooth data from app but no change.

**Comment by itsMeDavidV** [comment]
@cynodom  Have you updated Watchla to v3.4.7 yet?

**Comment by itsMeDavidV** [comment]
Unfortunately there still seems to be a small amount of people who still face this issue. Watchla will be releasing v3.4.8 which has prioritized a different way of identifying a Tesla via Bluetooth. This is a very new way for the 3rd party community (as in this was discovered literally today and has not been documented yet) so there will be some validation needed. 

Apple is currently reviewing v3.4.8 beta, however since it is Saturday night in California right now, this process might be delayed.

If you would like to help validate v3.4.8 beta and have not requested beta, please do so.

**Comment by cynodom** [comment]
Hi,not yet, I'll let you know as soon as I doThanksInviato da iPhoneIl giorno 13 ago 2023, alle ore 04:06, David Villegas ***@***.***> ha scritto:﻿
Unfortunately there still seems to be a small amount of people who still face this issue. Watchla will be releasing v3.4.8 which has prioritized a different way of identifying a Tesla via Bluetooth. This is a very new way for the 3rd party community (as in this was discovered literally today and has not been documented yet) so there will be some validation needed.
Apple is currently reviewing v3.4.8 beta, however since it is Saturday night in California right now, this process might be delayed.
If you would like to help validate v3.4.8 beta and have not requested beta, please do so.

**Comment by itsMeDavidV** [comment]
Hi everyone, the v3.4.8 update is now available on the [App Store](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747) and it should fix this issue for you.

Before testing please ensure that your *watch* app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.

Thank you again for your patience.

-David

**Comment by cynodom** [comment]
Hi David,Sorry for the delay in replying.
I did update to version 3.4.8 and everything seems to work again.
I really appreciate that you solved the problem in a short timeThanksInviato da iPhoneIl giorno 13 ago 2023, alle ore 23:46, David Villegas ***@***.***> ha scritto:﻿
Hi everyone, the v3.4.8 update is now available on the App Store and it should fix this issue for you.
Before testing please ensure that your watch app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.
Thank you again for your patience.
-David
