### ISSUE TITLE
Flashing and others not working over bluetooth

### ISSUE THREAD

**Issue by Wave797** [itsMeDavidV/Watchla-Support#159]
With WiFi is ok.
With Bluetooth only I am able to lock/unlock, vent, activate trunk, but not flashing lights, sentry, for which I get a code 0.
By switching commands, lock/unlock works, flashing returns code 0 and so on

**Comment by itsMeDavidV** [comment]
Hi @Wave797 flashing lights and toggling Sentry Mode are not currently able to be triggered over Bluetooth. This could change with the release of a Tesla vehicle software update in the future, however currently the functionality you desire is not offered by Tesla.
