### ISSUE TITLE
Stuck connecting Bluetooth AWU2 10.0.1 on V2023.32.x

### ISSUE THREAD

**Issue by Core-at-GitHub** [itsMeDavidV/Watchla-Support#161]
Hi David,
All updated to latest and greatest last week before installing Watchla. Getting stuck connecting Bluetooth while I connected an iPhone as without any problems last week. 
- Watchla commands run fine on Tesla.
- Watch connected to WiFi and iPhone (no cellular data)
- Mobile access allowed, Bluetooth enabled.
- Tesla M3P V2023.32.6
- Apple Watch Ultra 2 WatchOS 10.0.1
- iPhone 13 iOS 17.0.1
- Watchla 3.4.8 (299)

Thanks in advance!

**Comment by itsMeDavidV** [comment]
Hi @Core-at-GitHub thanks for reporting this and including that very relevant info, can you send over your Watchla Support code via https://watchla.app/contact?

**Comment by Core-at-GitHub** [comment]
Hi @itsMeDavidV , I shared Watchla Suppt Code .
Had typo on iPhone iOS version, it’s 17.0.1, so corrected it.

**Comment by itsMeDavidV** [comment]
@Core-at-GitHub awesome thanks! Will look into it and get back to you

**Comment by Core-at-GitHub** [comment]
Hi @itsMeDavidV , I got cellular on my watch and rebooted. Now it connected without any issues. So can't tell for sure what was the cause and solution, but it's working now.

**Comment by Core-at-GitHub** [comment]
Closing issue
