### ISSUE TITLE
On iOS 10, doors do not automatically lock when leaving the vehicles range

### ISSUE THREAD

**Issue by CaptCosmoCat** [itsMeDavidV/Watchla-Support#162]
Within the Tesla vehicle, I have it set to lock the doors automatically when walking away from the vehicle however, with the watch, the doors do not lock automatically you have to manually lock the doors on the app.

**Comment by itsMeDavidV** [comment]
Hi @CaptCosmoCat the Apple Watch has certain hardware limitations when it comes to background Bluetooth processing (the technology that enables passive unlock/walk-away lock) you'll wan't to see [this thread](https://twitter.com/WatchlaApp/status/1638373233115398145) and [these FAQs](https://watchla.app/faqs/bluetooth.html) to understand what those limitations are and how they affect locking and unlocking your vehicle while Watchla is not open.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
