### ISSUE TITLE
Vehicle not recognized in Tesla account

### ISSUE THREAD

**Issue by Jklbboul** [itsMeDavidV/Watchla-Support#163]
My Watchla app is not recognizing my model 3 to set up Bluetooth connectivity.
Side note- the watch for Tesla app did not either, the reason I have looked for another app to see if the problem was the app but it looks like there is another issue since not the Watchla app and the watch for Tesla app both don’t recognize my Tesla car

**Comment by itsMeDavidV** [comment]
Hi @Jklbboul it sounds like you may have issues with your Tesla account outside of any Tesla app. Watchla can query for all vehicles in your Tesla account, so if your vehicle is not showing in Watchla then it could mean that your vehicle may not be associated with the account you're signed into on Watchla. In Watchla, you can always check your list of vehicles and select a new primary vehicle by going to Preferences -> Select Vehicle

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
