### ISSUE TITLE
Cannot send commands and Bluetooth error

### ISSUE THREAD

**Issue by Mindcontrolola** [itsMeDavidV/Watchla-Support#166]
Tesla V 2023.38.6.
Phone iPhone 14 Pro
iOS V 17.1.1
Model 3
Watch A2477 iOS 10.1.1

![IMG_0789](https://github.com/itsMeDavidV/Watchla-Support/assets/151244290/577c239f-60dd-4296-9669-61c9b3c4af0e)
![6665986CF](https://github.com/itsMeDavidV/Watchla-Support/assets/151244290/49833f41-b9c2-47a7-aad7-b515ccd7f8d5)

Update:I fixed the Bluetooth issue. Deleted all the card except the original and added them back in. Worked like a charm to get Bluetooth to work. The not being able to send commands by data is still an issue.

Tried using both Tesla portal and tokens to sign in.  Status of Tesla shows and updates. When tapping a command like lock or anything, error 403. Tried logging in a few times. No commands work from app or watch.

Using watch is same, plus cannot setup Bluetooth. * Edit: I fixed the Bluetooth issue. Deleted all the keys and added the in the keys again.*  Sent support ticket with Support code.  Any help would be greatly appreciated to help get it to accept the sent commands. Keep getting the 403 error.  Thank you!

In Tesla settings, Mobile Access is on. Signed in multiple times using both token and Tesla portal. WiFi internet is connected.

**Comment by nskaiser** [comment]
I have the same exact issue with 403 errors.

**Comment by Kiwifruut** [comment]
I’m also having this issue with 403 errors 
![Uploading IMG_6212.jpeg…]()

**Comment by linkjap** [comment]
Same error :/

**Comment by itsMeDavidV** [comment]
Hi everyone, thanks for reporting this issue. Can you each please send over your Watchla support codes via https://watchla.app/contact so this can be investigated? Thanks!

Please be sure to link to this issue.

**Comment by itsMeDavidV** [comment]
Update, please [see this notice](https://x.com/watchlaapp/status/1726932808902553845?) as it pertains directly to this issue.

Will be working on this diligently until it is fixed, thank you in advance for your patience.

**Comment by kimlindberg** [comment]
Just bought the app a couple of hours back and I’m not able to setup Bluetooth. It’s stuck in a “Connecting” dialog. Tried several times, restarting app etc. Should I assume it’s the same issue as above?

**Comment by itsMeDavidV** [comment]
Hi @kimlindberg sorry to hear that, if your Tesla is updated to 2023.38.6 or later, then most likely yes.

This issue is currently being addressed and Watchla will have an update out as quickly as possible.

**Comment by som-saha** [comment]
Any updates on this? I just bought the Watchla app and am having the same issues. I was able to set up Bluetooth connection but Siri doesn’t work and I get 403 errors when using touchscreen on Apple Watch. Tesla version is 2023.38.6.

**Comment by itsMeDavidV** [comment]
@som-saha sorry about that and yes. The update is progressing well. Unfortunately the new signed commands technology for 3rd parties that Tesla is rolling out is not completely ready. So Watchla along with other 3rd party devs are working with Tesla to work out all the kinks. We should have a working beta update very soon. You can find out more about this and keep up with our progress here: https://x.com/WatchlaApp

**Comment by itsMeDavidV** [comment]
> I was able to set up Bluetooth connection

Also just to clarify, you're able to send commands over Bluetooth, but not over the internet correct?

**Comment by som-saha** [comment]
Thank you very much, David. I really appreciate the personal reply. I'll
keep an eye on the Twitter string.

Som

**Comment by itsMeDavidV** [comment]
Hi everyone, the fix for this is now out in beta. If you'd like to test the fix, please reach out here: https://watchla.app/contact with your email and Watchla support code.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
