### ISSUE TITLE
Cannot conmect

### ISSUE THREAD

**Issue by Arsenalamie** [itsMeDavidV/Watchla-Support#167]

**Comment by Arsenalamie** [comment]
The app is installed and appears to find my model Y but I get Tesla’s error code 540 every time I try to connect.

**Comment by Arsenalamie** [comment]
The app is installed and appears to find my model Y but I get Tesla’s error code 540 every time I try to connect.

**Comment by itsMeDavidV** [comment]
Hi @Arsenalamie a 540 status code indicates an error occurred within your vehicle leading to a bad response by said vehicle. Tesla's official wording on this particular status code is the following:

> Vehicle responded with an error - might need a reboot, OTA update, or service

**Comment by itsMeDavidV** [comment]
> might need a reboot

If you're not familiar, you can reboot your Tesla by pressing and holding both scroll wheels on your steering wheel for at least 10 seconds.

**Comment by Arsenalamie** [comment]
This is the only app with such a problem - Tesla’s app and a variety of other apps work fine.  I’ll try a reboot and let you know.Sent from my iPadOn Nov 28, 2023, at 6:34 PM, David Villegas ***@***.***> wrote:﻿
Hi @Arsenalamie a 540 status code indicates an error occurred within your vehicle leading to a bad response by said vehicle. Tesla's official wording on this particular status code is the following:

Vehicle responded with an error - might need a reboot, OTA update, or service

**Comment by Arsenalamie** [comment]
A reboot worked!  Why does this happen with apps sometimes?Sent from my iPadOn Nov 28, 2023, at 6:35 PM, David Villegas ***@***.***> wrote:﻿

might need a reboot

If you're not familiar, you can reboot your Tesla by pressing and holding both scroll wheels on your steering wheel for at least 10 seconds.
