### ISSUE TITLE
no effect please check

### ISSUE THREAD

**Issue by innhwoe** [itsMeDavidV/Watchla-Support#175]
![IMG_4243](https://github.com/itsMeDavidV/Watchla-Support/assets/153877321/d2e5fda0-f980-42bf-bb65-61343014ce05)
![Uploading IMG_4242.jpeg…]()
![Uploading IMG_4247.jpeg…]()

**Comment by innhwoe** [comment]
I need refund

**Comment by itsMeDavidV** [comment]
Hi @innhwoe sorry about that. 
You are most likely experiencing an issue associated with an API transition that is currently taking place in Tesla. [Please see here for more info.](https://x.com/watchlaapp)

Rest assured, we're working on fixing this issue asap.

If you'd like a refund you'll need to request one from Apple Support as Watchla has no control over payments or refunds.
