### ISSUE TITLE
unexpected tesla session error

### ISSUE THREAD

**Issue by lark79** [itsMeDavidV/Watchla-Support#178]
Hi. After installing watchla app, tesla related controls are not working at all.
Please see the image in the attachment.

I have completed the bluetooth key registration, but the key does not work either. I have logged out and logged back in several times, but it is the same symptom.

The app is not working at all, please provide a solution soon. Otherwise, I will request a refund.

iOS: 17.2.1
Apple Watch Ultra : WatchOS 10.2
Tesla App : 4.28.1
Support Code : zArmOjQleg

![IMG_0799](https://github.com/itsMeDavidV/Watchla-Support/assets/2034172/d26397cb-edcb-4573-a1db-3993556d4b14)
![IMG_0801](https://github.com/itsMeDavidV/Watchla-Support/assets/2034172/f2a30d8d-126d-40ad-8250-5053ca9197b9)

**Comment by itsMeDavidV** [comment]
Hi @lark79 sorry about that. This is an issue associated with an API transition that is currently taking place in Tesla. [Please see here for more info.](https://x.com/watchlaapp)

Rest assured, we're working on fixing this issue asap.

**Comment by itsMeDavidV** [comment]
Merging this issue with #166 to reduce duplicates. Please see #166 for updates on this issue.
