### ISSUE TITLE
Can no longer connect

### ISSUE THREAD

**Issue by nanoplane** [itsMeDavidV/Watchla-Support#18]
It worked for a month or so but will no longer connect to my tesla. 
V 1.95

**Comment by itsMeDavidV** [comment]
Hi sorry to hear of this. If you could please send me your Watchla support code, I can get to the bottom of it.

You can either reply in this comment thread with your support code or you can send it through Watchla's contact form here: https://watchla.app/contact (be sure to reference this issue)
