### ISSUE TITLE
Watch app

### ISSUE THREAD

**Issue by abitsoylu** [itsMeDavidV/Watchla-Support#185]
Watch app keep giving me error when trying to use Siri

**Comment by CassandraMarie** [comment]
Hi @abitsoylu, we are sorry to hear you are experiencing this issue. 

Watchla’s FAQs can guide you through step by step on how to setup and use Siri Shortcuts : https://watchla.app/faqs/

If you are still experiencing the issue please don't hesitate to reach out.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
