### ISSUE TITLE
New beta version 

### ISSUE THREAD

**Issue by Jedef2** [itsMeDavidV/Watchla-Support#188]
Hi, how can I try the latest beta Watchla version 
Mail: defour.tamigniau@defour.be
Code : sfjTJG1ATv

With best wishes 

jp

**Comment by itsMeDavidV** [comment]
Hi @Jedef2 an invite email has been sent out to you.

For others let's keep in mind that beta invite requests should either be sent via contact to https://watchla.app/contact or [via X DMs (formally, Twitter)](https://twitter.com/WatchlaApp) as this GitHub repo is dedicated to issue reporting.

**Comment by Jedef2** [comment]
Dear, I have not received the invite email for the upcoming beta version.Could you resend it to me ? With best wishes JeanEnvoyé de mon iPhoneLe 8 janv. 2024 à 06:34, David Villegas ***@***.***> a écrit :﻿
Hi @Jedef2 an invite email has been sent out to you.
For others let's keep in mind that beta invite requests should either be sent via contact to https://watchla.app/contact or via X DMs (formally, Twitter) as this GitHub repo is dedicated to issue reporting.
