### ISSUE TITLE
Unable to install Watchla 2.0 (96)

### ISSUE THREAD

**Issue by KurtSanders** [itsMeDavidV/Watchla-Support#19]
https://user-images.githubusercontent.com/12133562/141609814-cafb4863-8127-478d-9c91-8a62ada1c31e.mp4

Here is the video

**Comment by KurtSanders** [comment]
Tried installing after deleting old version of Watchla and only get Spinning install wheel in Apple Watch app.  Rebooted watch and phone, did not install.

**Comment by itsMeDavidV** [comment]
Are you only having trouble installing the watch app and not the iOS app?

I installed via TestFlight and I also had a very long spinning wheel thing happen to me as well. I ended up restarting my phone and watch and then I initiated the install in the Apple Watch app and left it for about 30 minutes and it finally did install. 

One thing to note is to check that you can install other watch apps via the Apple Watch app. If you cannot then it might be an issue with your Apple Watch in which case you would have to probably re-pair it with your phone.

**Comment by KurtSanders** [comment]
Bingo, the install finally completed and now installed 2.0 (96).  Not sure why Apple took so long to install this version and happy to test.  Looks like you have spent considerable time in re-development of the iOS companion app.  Nice work!

**Comment by itsMeDavidV** [comment]
Thanks Kurt! It's still not fully complete, but now able to be tested. Let me know what you think after you play around with it!

**Comment by KurtSanders** [comment]
Dear David,

Thanks for the quick response.  I rated it 5.0 on the App Store and noted that some users are pretty cruel in their assessments!  Don’t take their comments to hard, your App is very good and I know it takes a million hours of coding with integrated apps like this.  There are so many issues with Tesla API, Watch versions and cloud.   Hang in there, it's a great app!


¸¸.•*¨*•*´¨)
¸.•´¸.•*´¨) ¸.•*¨)
(¸.•´ (¸.•` ¤ 

Kurt Sanders
2485 Ridge Road
Xenia, Ohio 45385
+1937-723-0010

**Comment by itsMeDavidV** [comment]
Thanks Kurt! You're definitely right, the Apple Watch and Tesla api together make for a lot of moving parts. That being said though, internal ratings show the overwhelming majority of users on Watchla are happy with their experience. Sometimes it's just the angry few who are passionate enough to make reviews.

I will say though there is always room for improvement. IMO Watchla was a little slow at times to perform initial loading. In v2.0 I have made the initial load of Watchla's Watch app leaps and bounds faster and I already see the difference in my personal experiences with it!

Unrelated side note: beta build 97 enables Siri Shortcuts on watch--hope you enjoy!

**Comment by KurtSanders** [comment]
The Watchla's Siri Shortcuts are an awesome feature.  I had been using the Stats app for these, but will switch over to Watchla's to test.  

Keep up the fine improvements!


¸¸.•*¨*•*´¨)
¸.•´¸.•*´¨) ¸.•*¨)
(¸.•´ (¸.•` ¤ 

Kurt Sanders
2485 Ridge Road
Xenia, Ohio 45385
+1937-723-0010
