### ISSUE TITLE
Newest App Update: Can't Use

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#197]
I've granted Watchla access to my car (first image![image](https://github.com/itsMeDavidV/Watchla-Support/assets/9358980/59c7b485-3d1e-4349-bebc-e0fa8d327602)), and I'm the owner of the car and the primary authorized user. I'm getting the Unable To Share message so Watchla is now unusable (second image ![image](https://github.com/itsMeDavidV/Watchla-Support/assets/9358980/a0ed8d6b-be7c-4bb5-b5cb-3ed5b2db9455)). I guess I should not have tried using while traveling, when I'm most heavily using, and otherwise loving, Watchla.

**Comment by ttwajsb** [comment]
Here's further confirmation that Tesla and Watchla should be talking to each other.
<img width="517" alt="Screenshot_2024-01-12 18 05 06_VaF1Py" src="https://github.com/itsMeDavidV/Watchla-Support/assets/9358980/bbad81cb-b5cb-48b0-956a-61836237cf11">

**Comment by ttwajsb** [comment]
Same issue even after upgrading to 3.5.1

**Comment by ttwajsb** [comment]
I tried completely removing the app and all data then redownloading the latest version, and reinstalling on Watch. Same stuck spot (“Unable to Share Vehicle”) even though Watchla is now signed in using our Tesla credentials, with Watchla as an approved third party. 

'18 Tesla Model 3 v2023.44.30.8
Watch series 4 (A1976) v10.2
iPhone 14 Pro v17.1.2
Watchla v3.5.1

Watchla presently unusable

**Comment by ttwajsb** [comment]
Still no luck with v3.5.2

**Comment by itsMeDavidV** [comment]
Hi @ttwajsb authorizing use of Tesla 3rd party apps with your account requires only account permissions while adding a virtual key to the vehicle requires owner permissions.

Are you using a separate driver profile to your owner account on the Tesla app? This can sometimes be the case in couples when one is the official owner profile and the other is just a driver profile.

If you are using the owner profile, and this issue persists I'd recommend reaching out to Tesla as they are the ones who would be best fit to help you solve this issue.

**Comment by currawong** [comment]
Could I ask why you don't show the Powerwall permissions? Is it just the image that is cropped? They show for me.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
