### ISSUE TITLE
Siri commands not working on watch

### ISSUE THREAD

**Issue by Storm562** [itsMeDavidV/Watchla-Support#2]
Hi, 
Everytime I ask Siri to do something I get “Watchla will continue your request.”
A “Open Watchla” button is underneath 
I uploaded a picture 
Thanks
Paul 

![058E922A-9428-4A36-95A3-2AEA4608D0C8](https://user-images.githubusercontent.com/81866323/113481354-f3e20280-944d-11eb-9129-3fe3f5d9de51.jpeg)

**Comment by itsMeDavidV** [comment]
Hi  @Storm562, thanks for reporting this. I will investigate this issue further and reply back with an update.

In the meantime I just wanted to get some info from you around this issue, to better help me get to the bottom of it:

- Which command were you asking Siri to perform?
- Does the issue occur all the time or only at certain times / under certain circumstances
- Was your vehicle in deep sleep (or Offline) at the time that the issue occurred?
- Was there any other issues occurring at the same time (eg: a vehicle data error or watch face complications not showing correctly)?
- & I just wanted to confirm that you were signed in to Watchla during the time that this issue occurred?

**Comment by itsMeDavidV** [comment]
@Storm562 

Hi Paul, 
The issue you faced was reproduced and a fix for it has been made & submitted to beta users for testing. I will request an expedited review with Apple and hopefully the fix will be included in an App Store update of Watchla by tomorrow (Sunday, April 4th). I will comment back here when the new update is out.

**Comment by Storm562** [comment]
Thank you!

**Comment by itsMeDavidV** [comment]
@Storm562 You're welcome! Just wanted to let you know that the issue has been fixed in version 1.40 of Watchla, which as of now is available on the App Store.

If no other occurrences of this issue are reported in >= v 1.40 today I will close this issue.

Thanks again for reporting this!
