### ISSUE TITLE
Watchla can not be installed to the Apple watch

### ISSUE THREAD

**Issue by kamsimon** [itsMeDavidV/Watchla-Support#201]
Hi there,

There’s error with the Watchla app on my watch. I reinstalled everything but now can’t install the Watchla app to my watch. Please kindly help.

cheers
kamsimon

**Comment by kamsimon** [comment]
My support code 0mHBR63mJb

**Comment by itsMeDavidV** [comment]
Hi @kamsimon sorry to hear that. Unfortunately Watchla has no control over installing apps on your device. The most direct and quickest way to download an app to your Apple Watch is via the App Store app on your Apple Watch itself. If that doesn't work, I'd reaching out to Apple Support to see how you can troubleshoot.

**Comment by Snaffalot** [comment]
I have the same issue, can install the app to my phone. But from the watch app, I tap the install button for Watchla, it flashes ‘installing’ briefly and stops, going back to the button for ‘install’

**Comment by kamsimon** [comment]
Exactly the same situation here! It seems that there’s a problem of new updates of Watchla….

I had tried to uninstall the Watchla app and reinstalled and logged in everything but still nothing working until now….

**Comment by kamsimon** [comment]
It seems that everything resumed normal just now….

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
