### ISSUE TITLE
Can’t make it working after update

### ISSUE THREAD

**Issue by aeilat** [itsMeDavidV/Watchla-Support#202]
issue ref: uUebIPbuqq

Removed old key and installed new one. Did full process with all approvals to Tesla and still not working

![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156504479/ba129ecd-5f8d-4dfc-b493-284b7e7abe22)

![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156504479/ddbc7679-11ae-43bb-a53b-da80fad932a3)

![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156504479/115eefe6-3342-4c35-8621-c95b9956173c)![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156504479/779da9b3-53e7-4bc6-9be6-c338d88881b4)![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156504479/c4237b13-780f-4bdb-af48-68c0dd7900dc)

**Comment by itsMeDavidV** [comment]
Hi @aeilat can you send over the support code found on your Watchla watch app? The one you provided is unfortunately only attributed to the iOS app.

Also as for the virtual key, it's quite possible that Watchla just didn't catch that you added the key. From your support code that you provided I am seeing that you were able to successfully send a signed command indicating that you successfully installed the virtual key. We'll work on refining this detection process. For now, try force closing the app and re-opening it. That should make the warning banner go away.

**Comment by aeilat** [comment]
Thank you fir the quick reply. Ok your request led me to the watch app and i saw the key wasn't connected through there although i did the full process on the iphone. Did the process on the watch and after a few jiggles (closing and opening apps) it now works.

Thanks,

Amir

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
