### ISSUE TITLE
Apple Watch - virtual key not setup, tap to setup - stuck in loop

### ISSUE THREAD

**Issue by tdebaere** [itsMeDavidV/Watchla-Support#205]
With the new API, it was necessary to go through a number of steps in the app. I think I succesfully managed to get the app working with the new API, as I can see that in the iPhone app the vehicle data is coming in. I also managed to get the bluetooth key working from my Apple Watch Ultra, and I can see it connects with the car. 

The only issue I have is that the Watch App keeps showing me that "virtual key not setup, tap to setup". I've done that multiple times, the Watchla app is showing up in the key section of the car, but the Watch app keeps telling me to setup the virtual key.

I already removed it from the car and tried it again, and rebooted the Apple Watch.

What can I do to resolve this issue ?

thank you,

Tom

![IMG_3162](https://github.com/itsMeDavidV/Watchla-Support/assets/156520011/0e9a9504-4199-410f-a4fb-2e1c62f6e3e4)

**Comment by Jedef2** [comment]
Hi, 
I have the same issue 
I Return to the page and tap Finish Setup and then there is a loop… so it seems impossible to finish the setup.

With best witches 

jp (iPhone 11 pro , Apple Watch Ultra 2 )

**Comment by davilamb** [comment]
Same thing happening here!  Glad I am not alone god!

iPhone 11 Pro and ultra

**Comment by Maisey1965** [comment]
Same issue, tried many things, no difference.

**Comment by javipe74** [comment]
Same issue here. Even if the app recognizes the vehicle I see the virtual key not set up message all the time and all the commands give an error. I tried to delete the app and configuration in the car related to Watchla and the issue persists.

**Comment by tdebaere** [comment]
Today the problem still remains, but now I noticed something new : in the complication on the Apple Watch, the Tesla Watchla complication is shown as a curved block of "nothing"...

![IMG_3182](https://github.com/itsMeDavidV/Watchla-Support/assets/156520011/ac4f253b-ceca-4acf-8bd2-9ce070c482f4)

**Comment by CassandraMarie** [comment]
Hi @tdebaere, @javipe74, @davilamb, @Maisey1965, and @Jedef2, we apologize for the late reply. Are you still experiencing this issue?

**Comment by tdebaere** [comment]
Hi Marie, the complication is working again, thx !

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
