### ISSUE TITLE
After using a Hertz Rental, the app is stuck in a loop because that car is no longer on my Tesla account.

### ISSUE THREAD

**Issue by TMahlmann** [itsMeDavidV/Watchla-Support#209]
![IMG_4915](https://github.com/itsMeDavidV/Watchla-Support/assets/68261950/52d49c6c-8712-4129-be4f-57e67faf81f2)

I deleted the app from the Home Screen and reinstalled via the iOS App Store, same result—the app can be left open for almost an hour and still hangs.

 Is there a way to clear the login / cache?

**Comment by CassandraMarie** [comment]
Hi @TMahlmann, we apologize for the late reply. Are you still experiencing this issue?

**Comment by TMahlmann** [comment]
Hi! No problem.Thankfully I am not, after signing out of everything and signing back in. Thanks a bunch! Best,TrevorOn Aug 1, 2024, at 6:35 PM, Cassandra Marie ***@***.***> wrote:﻿
Hi @TMahlmann, we apologize for the late reply. Are you still experiencing this issue?

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
