### ISSUE TITLE
Unable to paste token

### ISSUE THREAD

**Issue by Robertmordka** [itsMeDavidV/Watchla-Support#21]
Because watchla log out every few hours I tried to authorize it with token instead of authla but the paste function is  not working on iphone screen

**Comment by itsMeDavidV** [comment]
Hi, thanks for reporting this. 

The issue you described is the result of WatchOS 8 no longer allowing paste functions from iOS to WatchOS via prompt textfield. 

Good news is that pasting into your watch from iOS is no longer needed to sign in with a token in Watchla version 2.0. Version 2.0 is set to come out any day now pending Apple's review.

In the meantime, if you'd like to get Watchla v2.0 early just send me an email via https://watchla.app/contact and I will get you in today.

-David

**Comment by itsMeDavidV** [comment]
Hi @Robertmordka Watchla 2.0 is now live. You can either update in beta or the App Store for a new and approved sign in experience
