### ISSUE TITLE
Won’t reinstall on watch 

### ISSUE THREAD

**Issue by Casualzen** [itsMeDavidV/Watchla-Support#211]
Updated the app. Would  not communicate with Watch ultra running latest watchOS. Deleted app to start all over. Now app stalls on reinstall. Have rebooted both phone and watch.

**Comment by kjepstein** [comment]
I was having the same problem, but it seems to have installed after many attempts (10 or more). I was getting a message on the Watch "You're using the old API" and asked me to "Sign Out, then Sign In". After several attempts, I ended up deleting Watchla and reinstall it from the App Store. However, I'm still getting the "Old API" message.  2023 Tesla Model X, Apple Watch 8 45mm, iPhone 15 Pro Max.  All are running the latest versions of their respective OS.  DavidV, can you help?

**Comment by Casualzen** [comment]
I solved it with my #2 standard solution: I went to bed and tried it again in the morning. :D All seems to work now, but that on-boarding was a doozy.

**Comment by kjepstein** [comment]
That’s my #1 solution. Didn’t work. Solution #2 is to do the same thing over and over again until I’m exhausted. Solution #3 is asking for help. That’s where I am now.

**Comment by x4cHaOSx** [comment]
Same issue with the latest version of watchla. I tapped endlessly and also uninstalled and reinstalled app. I am on an Apple Watch 5. 

Update: I put my watch on a charger and tried to install from the Apple Watch app and it installed!

**Comment by CassandraMarie** [comment]
Hi @Casualzen, @kjepstein, and @x4cHaOSx, we apologize for the late reply. Are you still experiencing this issue?

**Comment by Casualzen** [comment]
No. On Aug 1, 2024, at 7:38 PM, Cassandra Marie ***@***.***> wrote:﻿
Hi @Casualzen, @kjepstein, and @x4cHaOSx, we apologize for the late reply. Are you still experiencing this issue?

**Comment by x4cHaOSx** [comment]
No. On Aug 1, 2024, at 7:38 PM, Cassandra Marie ***@***.***> wrote:﻿
Hi @Casualzen, @kjepstein, and @x4cHaOSx, we apologize for the late reply. Are you still experiencing this issue?

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
