### ISSUE TITLE
Toggle "Do not wake" and "Do not wake in back ground" not working

### ISSUE THREAD

**Issue by martennienhuis** [itsMeDavidV/Watchla-Support#220]
When I toggle the "Do not wake" or "Do not wake in background" on my Apple Watch the switch wil turn on. When I go back "<" and then go again to "Wake settings" the switch is off again.  

Also, the Wake settings are not in sync on my Applewatch and iPhone.

I want to turn this off because my model 3 is not going into sleep and my applewatch battery is draining too much.

The workaround for me now is to prevent background process for the watchla app (in the watch app - general - refresh in background - watchla (turn off)

Please let me know if you need more information.

**Comment by skipcooney** [comment]
+1
Running Watchla IOS ver 3.5.3. Do Not Wake settings are persistent on the iPhone but not on the Apple Watch. Also wake setting are not in synch across the watch and phone.

**Comment by skipcooney** [comment]
Ver 3.5.4 now and this bug continues

**Comment by bra123br** [comment]
Problem still there in version 3.5.5

**Comment by martennienhuis** [comment]
In watchla version 3.6.1 this problem seems te be solved (for me)

**Comment by CassandraMarie** [comment]
@martennienhuis, Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
