### ISSUE TITLE
Watchla not working

### ISSUE THREAD

**Issue by Kniggy** [itsMeDavidV/Watchla-Support#223]
Since an update my Watchla app doesn’t work with my Tesla? 
tried everything and still can’t get it set back up??
What has happened as I have paid for this app??

**Comment by Micprou** [comment]
Same for me. Icons in home page don’t work as those in all commands do. Home page turns black each time an icon is tapped. This new version is a mess…

**Comment by claire078** [comment]
> Since an update my Watchla app doesn’t work with my Tesla? tried everything and still can’t get it set back up?? What has happened as I have paid for this app??

same here. ☹️

**Comment by davidwu503** [comment]
Same here

update：
I just updated the Watchla app and now its working fine. Only issue is I can't get the complication to show on the watch. But even though it's a blank space there, I can still press there and it opens up the Watchla functions. So for the complication only, it works but just doesn't look good.

**Comment by Kniggy** [comment]
Are Watchla doing anything about this???

**Comment by itsMeDavidV** [comment]
Hi everyone, please update to [version 3.5.2. ](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747)

**Comment by Kniggy** [comment]
Done that and still nothing works, can’t connect to Watch app or my Tesla now

**Comment by itsMeDavidV** [comment]
@Kniggy have you transitioned to the new api by signing in/out and have you verified that your watch app has also updated? You can check which version you're on in the Watch app at the bottom of preferences.

If so, please send over your Watchla support code found on your watch to https://watchla.app/contact so we can investigate your case.

**Comment by Kniggy** [comment]
Done all the above and still doesn’t work
I have submitted support code

**Comment by Kennethol** [comment]
Mine dosent Work after 3.5.2 update

**Comment by Kennethol** [comment]
> Since an update my Watchla app doesn’t work with my Tesla? 
> 
> tried everything and still can’t get it set back up??
> 
> What has happened as I have paid for this app??

Same here

**Comment by GartnerE** [comment]
Mine still indicates “No vehicles found” after updating to 3.5.3.

**Comment by Kniggy** [comment]
I am fed up now of this! Used Watchla a lot before this update. I have tried everything, reset, reboot, everything and still won’t connect to virtual key…..rubbish. Can you send my money back so I can purchase another app for my watch please

**Comment by Kniggy** [comment]
Anyone had any joy with the Watchla app yet? Mine still not connecting! Not even a response to my support code I was asked to send!! Poor service IMO

**Comment by CassandraMarie** [comment]
@Kniggy, we apologize for the delayed response. With the latest update (3.8) on Watchla, are you still experiencing this issue?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
