### ISSUE TITLE
“ask to confirm command” toggle button not working

### ISSUE THREAD

**Issue by marksahagun** [itsMeDavidV/Watchla-Support#226]
The “ask to confirm command” toggle button isn’t working on the Apple Watch for me. I have toggled this off … and It shows “off” on both the Apple Watch AND the phone app and yet I am prompted to confirm commands for ALL commands issued from the Apple Watch. Hope this is fixed soon …

**Comment by HenryTung2022** [comment]
me too

**Comment by yoshiat** [comment]
Same here and I believe this was fixed in 3.5.2 that was pushed out last night.

**Comment by itsMeDavidV** [comment]
In version 3.4.9, Watchla temporarily disabled one-tap commands out of precaution as the new UI re-write was introduced. They should now be re-enabled in the update v3.5.2 that was released 14 hours ago. 

Before testing and after updating, you'll want to make sure that your watch app has also received the update as sometimes Apple Watch apps can receive updates hours or days after their iOS companion apps do. You can check this by going to Preferences in the watch app and scrolling all the way down to the version indicator.

If you find your watch app has not updated to v3.5.2 (325) or later you can directly update it on the App Store app found on your Apple Watch.

**Comment by marksahagun** [comment]
I’ve updated and it works! Thank you so much!!

**Comment by claire078** [comment]
it works me too.
thx

**Comment by itsMeDavidV** [comment]
You're very welcome! :)
