### ISSUE TITLE
Leased cars 🚙 

### ISSUE THREAD

**Issue by Asbkol** [itsMeDavidV/Watchla-Support#230]
Please push Tesla for a solution when the car is leased or own by a company/ third party👍

**Comment by nunoloureiro** [comment]
Same issue here. 

It used to work before, and now:
![IMG_1609](https://github.com/itsMeDavidV/Watchla-Support/assets/542702/aee3de5d-ef7b-4712-b215-e6e4f13e1b8b)

**Comment by Kennethol** [comment]
Also getting that messege

**Comment by itsMeDavidV** [comment]
Hi, have you seen this?

https://github.com/itsMeDavidV/Watchla-Support/issues/218#issuecomment-1899288009

**Comment by Asbkol** [comment]
Would just like to inform that the newest app release from tesla resolves this issue. I now have a working watch app. A virtual key can be added by using the keycard.
