### ISSUE TITLE
Set up Bluetooth key

### ISSUE THREAD

**Issue by cghadden** [itsMeDavidV/Watchla-Support#238]
Just get initialising then times out
Phone/settings/watchla does not show an option to use Bluetooth
iPhone 15 pro max latest iOS
Apple Watch Ultra 2
Do I need to pair the watch with the car?

**Comment by itsMeDavidV** [comment]
> Do I need to pair the watch with the car?

Hi @cghadden, yes you need to setup your Bluetooth key. You can do this in the Watchla watch app by going to the Home screen -> scroll down -> tap Setup Watch Key -> then follow the steps

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
