### ISSUE TITLE
Unable to setup virtual key

### ISSUE THREAD

**Issue by mtf169** [itsMeDavidV/Watchla-Support#239]
Virtual key setup is not working.  When I click to start the process, it bounces me out to the Tesla app for approval.  I tap approval, but it times out. 
![IMG_0225](https://github.com/itsMeDavidV/Watchla-Support/assets/20192424/353c9d03-bddd-4416-8671-ddf7dea01516)

**Comment by itsMeDavidV** [comment]
Hi this is an issue with the Tesla app, not Watchla. If this continues, I'd recommend reaching out to them if this issue persists

**Comment by mtf169** [comment]
Thanks for the reply.  Very frustrating for you as a developer and me as a customer.  After numerous retries it finally worked, so you’re 100% correct … this was something with their side of the process.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
