### ISSUE TITLE
Unable to sign into Watchla from authla 

### ISSUE THREAD

**Issue by RY2416** [itsMeDavidV/Watchla-Support#24]
Hello,

When attempting to connect my vehicle to the Watchla app, I’m asked to authenticate on the Autla app. When opening the Authla app and choosing to “Sign in to Watchla” I receive and error letting me know “unable to sign into Watchla try again later”. I’ve been attempting this sign in for multiple days without success. What steps can be taken to resolve? Thank you.

**Comment by itsMeDavidV** [comment]
Hi @RY2416 with the release of version 2.0 of Watchla, sign in with Authla has now been phased out. 

With Watchla v2.0 there is a new iOS companion app for Watchla that is now the default way of signing in with Tesla. From there, you can either sign in directly with Tesla or with a Tesla token. Once signed in your authentication status will automatically transfer over to the Watchla watch app. 

Hope this helps!

**Comment by RY2416** [comment]
Thanks David,

How do I access the new iOS companion app, and what is it called? Does it require a separate download?

Is the Watchla v 2.0 automatically update from the 1.0 app or is there an additional download required

**Comment by RY2416** [comment]
I’ve found the iOS companion app, what is the best method for receiving a Tesla token. Can this be done directly from Tesla or does it require a 3rd party API app?

**Comment by itsMeDavidV** [comment]
@RY2416 I'd recommend signing in with Tesla. This will allow Watchla to automatically refresh your token in the future so you don't have to.

Alternatively you can sign in with a token, however you will be responsible for providing a new Tesla token when the original one expires which could interrupt your Watchla experience. 

If you do decide to sign in with a token, I recommend Watchla's sister app, Authla, as a good place to get a token.

Here's the link: https://apps.apple.com/us/app/authla/id1546597644
