### ISSUE TITLE
No vehicle found

### ISSUE THREAD

**Issue by GizmoStu** [itsMeDavidV/Watchla-Support#241]
Hi. When first starting Watchla on my iPhone, I log into Tesla but it fails to find my vehicle. The Tesla app is correctly connected to my car. 
 Please help.

**Comment by GizmoStu** [comment]
Support code 
![IMG_1821](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/eff07dce-630d-44a6-a03d-a34d64ecd34e)
[redacted]

**Comment by GizmoStu** [comment]
![IMG_1821](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/5b55cb23-430d-4823-8842-3940e9f3d9e8)

Still can't get past the first stage. Please can I have my money back and I'll buy the Tesla for watch app?

**Comment by khbue** [comment]
I get the same comment!! - No vehicle found! -
Please help!!

**Comment by getnorm** [comment]
I updated to the latest version of the Watchla app and now it stopped working. 
I have been getting the exact same message above for the last week whenever I try to sign into the app.

**Comment by GizmoStu** [comment]
Ah ok. That makes sense that the update has broken it. I read all these great reviews so bought it and can't even get going with it. That happens a lot with new software releases. 🙄  I Really hope they can get it fixed quickly.

**Comment by GizmoStu** [comment]
Is anyone looking into this issue? It's pretty unacceptable to have had no feedback from the developer or estimate of when it might work again. 🫤

**Comment by mauricio2099** [comment]
They need to make a better job in the onboarding process.
I used to have the issue with the No vehicle found. 
I removed the app access in my Tesla Account and gave it access to Vehicle Information not just Vehicle commands and now I see it.
![CleanShot 2024-01-25 at 14 39 08@2x](https://github.com/itsMeDavidV/Watchla-Support/assets/17269897/6e2a6b73-f22e-436c-af83-a03ec8010029)

**Comment by itsMeDavidV** [comment]
This is a top priority for v3.5.5. In the meantime, a work-around for some facing this issue is to sign in -> get to the error message -> so not chose any option -> force close the app -> re-open

**Comment by GizmoStu** [comment]
Force closing and re-opening didn't work, however removing Watchla from the Tesla account and re-adding it did work. Yea!

**Comment by GizmoStu** [comment]
@mauricio2099 Thank you for your suggestion which seems to have worked. 👍🏼

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
