### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by Lukeonthehill** [itsMeDavidV/Watchla-Support#248]
After pressing the button to sign in with Tesla an error is presented for missing parameter client_id.

5d3d26b7d698425a8705a50782441203-1706226613252

**Comment by comraddan** [comment]
I'm getting the exact same error.

"Missing required parameter: client_id"

I updated to 3.5.4 and finally decided to do the API update the app was complaining about. It told me to sign out in the Watchla app, so I did and now I get the same error that Lukeonthehill is getting.

**Comment by DBuit** [comment]
Just bought the app and got the same error: Missing required parameter: client_id

**Comment by itsMeDavidV** [comment]
Hi all, thanks for reporting this issue. This issue originated from an update that was released earlier today and we have since corrected the issue and will be releasing a new update most likely in the morning (PST)

**Comment by glenncs** [comment]
Same issue 
66d93fea39194a7d8cdee57b21d665fd-1706267131814

**Comment by NoelJBR** [comment]
Hi

Any sign the fix coming out already?

Still similar issue:

aadf4f62be24461e801b7878e3c65667-1706268391881

Thanks

**Comment by itsMeDavidV** [comment]
This issue has since been fixed in v3.5.5, released earlier today! 

Sorry for the inconvenience!

**Comment by glenncs** [comment]
I had the same problem yesterday. Just uninstalled and reinstalled the app. Now able to login.
