### ISSUE TITLE
Enable Siri for Watchla?

### ISSUE THREAD

**Issue by RY2416** [itsMeDavidV/Watchla-Support#25]
“ To enable Siri for Watchla, goto the Settings app on your Apple Watch -> scroll down & select "Siri", scroll down & select "Use with Siri", and then turn on "Watchla".”

Watchla is not showing up as an option under the “Use with Siri” menu, does this need to be activated elsewhere? Any suggestions?

**Comment by itsMeDavidV** [comment]
Hi @RY2416 Siri instructions for Watchla are currently being changed. 

If you have version 2.0 just open the iOS app and from the main screen and goto Preferences (3 bars icon) -> Siri Shortcuts and then add the Siri Shortcuts you wish to use. 

Once added, you can add them to your Apple Watch as well by going to the Shortcuts app, tapping the 3 dots button on the Shortcut, then tap the settings button and switch on "Show on Apple Watch". 

Your Apple Watch might take a bit of time to process the Shortcut initially, but to circumvent this processing time I found that all you have to do is close and re-open the shortcut app on your Apple Watch.
