### ISSUE TITLE
Can not login with tesla account

### ISSUE THREAD

**Issue by Risbergg** [itsMeDavidV/Watchla-Support#253]
Hi

I just bought the app and can not login. 
error code bc8ab76539f245f99841d26957013d18-1706260676122

regards
Gunnar

**Comment by glenncs** [comment]
Same issue 
66d93fea39194a7d8cdee57b21d665fd-1706267131814

**Comment by bobbyrana** [comment]
Getting same issue after trying to login to tesla

**Comment by mstelz999** [comment]
Just bought this app and it isn’t working? Wtf? Should I get a refund or will this be fixed?

**Comment by glenncs** [comment]
I had the same problem yesterday. Just uninstalled and reinstalled the app. Now able to login.

**Comment by itsMeDavidV** [comment]
Hi, all sorry about that! This issue originated with an update released yesterday. We have since fixed this issue with a new update released today.
