### ISSUE TITLE
Remote Start does not work anymore

### ISSUE THREAD

**Issue by khbue** [itsMeDavidV/Watchla-Support#26]
At the beginning, all commands were working. Now, still all commands are working, except “Remote Start”.
After hitting “Remote Start”, this message appears:
“Error sending command to vehicle
Please check your internet connection & try again.
Okay”
After Pressing Okay, the following statement shows up:
“Remote start enabled.
You have 2 min to start driving”
But I cannot start the car.
WLAN is ok!!
Please help!
Thank you in advance! Karl

**Comment by khbue** [comment]
My car is a Model 3. Karl

**Comment by itsMeDavidV** [comment]
Hi @khbue thanks for reporting this I'll take a look into it and get back to you. What version of Watchla are you using?

**Comment by itsMeDavidV** [comment]
Hi @khbue so after investigating here's what I found:

- There are currently only 20 instances of Remote Start errors from 8 users in the current App Store version. 

- All but 1 are 401 errors which most likely means the Tesla API received an incorrect password. 

So now I just have a few questions to better get to the bottom of this:

- Is it possible that you entered the wrong password?

- After the failure were you at all able to enter another password? Or did you not have that option?

- Did you have any other issues communicating with the Tesla API via Watchla around the time that the Remote Start error occurred?

- (if you're a pre-v2.0 user) did you have issues with Remote Start before version 2.0 or did these issues start occurring after you updated to version 2.0?

**Comment by itsMeDavidV** [comment]
Given the time since a last response, I'm assuming this issue was resolved and closing this issue. If not, please feel free to re-open it.

Thanks,
-David
