### ISSUE TITLE
3.5.5 still no complications 

### ISSUE THREAD

**Issue by Gr1ss0m** [itsMeDavidV/Watchla-Support#264]
On phone and watch 3.5.5 but stlll no working complications. Not even showing. Black spaces only. When I press on them I get the command. But nothing showing.

**Comment by victortan20202** [comment]
same here on ultra

**Comment by skipcooney** [comment]
Fixed on v 3.6.1

**Comment by itsMeDavidV** [comment]
This should be mostly fixed by now, is anyone still experiencing this?
