### ISSUE TITLE
Display shortcut not accurate

### ISSUE THREAD

**Issue by tkrueger15** [itsMeDavidV/Watchla-Support#270]
Display Shortcut doesn’t update. Within the app it gives accurate percentage/mileage of battery, but not in watch face shortcut. Please let me know how to fix this issue.
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/158186363/8ed94caf-58c7-4c19-a268-17abc9657387)
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/158186363/185ad352-ddcf-46d9-97ae-64456dacdfb1)

**Comment by itsMeDavidV** [comment]
Hi @tkrueger15 we've addressed this in v3.5.7 and will continue to make improvements on this front. Have you gotten a chance to update your watch app to v3.5.7 yet?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
