### ISSUE TITLE
I also have homelink issues. I can’t get it working

### ISSUE THREAD

**Issue by Risbergg** [itsMeDavidV/Watchla-Support#273]
I also have homelink issues.
1) Pressing the button on my watch sends the command and watch shakes but no responce from homelink,
2) Using short cut and ask Siri to activate garage (my replaced command) sends the comand and the response is -there ins no homelink action defined. 
From Tesla app or geofencing it works as a charm.

_Originally posted by @Risbergg in https://github.com/itsMeDavidV/Watchla-Support/issues/170#issuecomment-1915649350_

**Comment by itsMeDavidV** [comment]
merging with #344
