### ISSUE TITLE
Question: virtual keys

### ISSUE THREAD

**Issue by claire078** [itsMeDavidV/Watchla-Support#276]
Hi @itsMeDavidV,
please explain to me. 
what is the different between “watch key” and virtual key? What they for?
Both need to have it?
Phone app also has a virtual key. All should have to be installed?

**Comment by itsMeDavidV** [comment]
Hi @claire078 A virtual key is a key used by your Tesla to verify incoming commands (sent over the internet) by apps you authorize like Watchla. A watch key in Watchla is a Bluetooth key that pairs to your car over Bluetooth and allows you to send commands and receive limited vehicle state data from you Tesla over Bluetooth
