### ISSUE TITLE
No longer on watch face 

### ISSUE THREAD

**Issue by Maisey1965** [itsMeDavidV/Watchla-Support#277]
After several days, I was able to reset it successfully as a virtual key.  Now the app doesn’t show on my watch face.  Tried a few different faces.  Turned off watch and phone. Continues to not show, even though on phone ‘display Watchla’ is toggled yes.
It’s a great app when it works.  Completely useless when it doesn’t

**Comment by claire078** [comment]
Today I experienced exactly the same!
My complications gone, completely blank. Until now they do not worked but at least they showed on watch faces.

**Comment by claire078** [comment]
3.5.7 nothing has changed ☹️

**Comment by Kennethol** [comment]
3.5.7 now IT Works perfekt

**Comment by claire078** [comment]
> 3.5.7 now IT Works perfekt

but not for me.
after new install, during watchface editing still there, but after gone:
Ultra watchos 10.3, Watchla 3.5.7
![incoming-F8B7C57F-48EF-4A5E-9D24-E5F22ACCA4A8](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/e8b0909a-3575-427a-9c6d-8ace1da706ef)
![incoming-1C85F6F2-A7F7-42FB-BA79-DEC4437D4753](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/f482f4b2-a166-4306-8ea3-d6c8d5915b13)
![incoming-FFF049F8-9CE9-4F3B-8EE0-DDDAA700D31D](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/f06ed099-5556-4ee6-bfd1-1bf1a1265fc3)

**Comment by GizmoStu** [comment]
![incoming-C02A90B8-73B0-4551-86F3-AC646DDC17C0](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/812552df-a5c0-4411-b552-c3d83c19e05f)
It's gone from my watch face too. I can add it again but only if I choose something like battery state. That's it at the bottom. The App icon to open Watchla is gone!

**Comment by itsMeDavidV** [comment]
There are some issues that are prevalent on the Relevant Vehicle Status complication that are not on other complications as RVS has a lot of assets and moving parts. We are working to specifically address this in v3.5.8

**Comment by claire078** [comment]
> There are some issues that are prevalent on the Relevant Vehicle Status complication that are not on other complications as RVS has a lot of assets and moving parts. We are working to specifically address this in v3.5.8

Interestingly it just getting works on this afternoon. 😳
RVS shows when ventilation or sentry is active, actually P(ark) doesn’t shows.

I have found another bug with sentry. I’m creating another issue to this.

**Comment by Maisey1965** [comment]
I was able to get mine working by removing app, then re-adding it and using battery state as the icon.

**Comment by claire078** [comment]
> I was able to get mine working by removing app, then re-adding it and using battery state as the icon.

Could you post a picture about RVS complication?
Mine shows a Watchla icon instead of P (parking), it showed in older versions. 
@itsMeDavidV is it OK now?
