### ISSUE TITLE
Cannot get Watchla to appear on watch.

### ISSUE THREAD

**Issue by pavila40** [itsMeDavidV/Watchla-Support#28]
I cannot find the watch app face on my watch.

**Comment by itsMeDavidV** [comment]
Hi @pavila40 here's how to get the Watchla watch app on your Apple Watch:

1: download the iOS app
2: navigate to the "Watch" app on your paired iOS device
3: goto the "My Watch" tab
4: scroll down to "Available Apps"
5: tap the install button next to Watchla

After the steps above the Watchla watch app should start downloading to your watch.

If you are having download/install issues, I recommend contacting Apple Support as they are best equipped to handle those issues.

Hope this helps!

**Comment by itsMeDavidV** [comment]
Hi @pavila40 here's a good how-to by Apple on how to customize your watch face: 

https://support.apple.com/guide/watch/customize-the-watch-face-apda6559ad78/watchos

I'd recommend scrolling down to the section titled: "Add complications to the watch face"
To get familiar with adding complications to your watch face.

Once familiar, you can find available Watchla complications for most complication families to add to your watch face.

Hope this helps!

-David

**Comment by itsMeDavidV** [comment]
@pavila40 Is this issue still occurring for you?

Given the time since your last comment, I'll assume it did and close this issue. But if it didn't please feel free to re-open the issue.
