### ISSUE TITLE
Unable to create virtual key

### ISSUE THREAD

**Issue by AgentBlonde** [itsMeDavidV/Watchla-Support#280]
I find myself continually trapped in a repetitive cycle of attempting to access the Tesla application. Regrettably, upon successfully gaining entry into the application, I am met with a disheartening lack of progress. To my dismay, I am unable to generate a virtual key as desired.

**Comment by itsMeDavidV** [comment]
Hi @AgentBlonde sorry to hear you're having trouble setting up a virtual key. To better help you, can you be a bit more specific on where exactly things go wrong? 

Are you not able to open the Tesla app via the setup link or are you seeing an error message from Tesla when attempting to setup your Virtual Key?

**Comment by AgentBlonde** [comment]
i’m able to open up the Tesla app no problem but doing so doesn’t result to any action.Nate BlondeOn Feb 5, 2024, at 1:07 AM, David Villegas ***@***.***> wrote:﻿
Hi @AgentBlonde sorry to hear you're having trouble setting up a virtual key. To better help you, can you be a bit more specific on where exactly things go wrong?
Are you not able to open the Tesla app via the setup link or are you seeing an error message from Tesla when attempting to setup your Virtual Key?

**Comment by itsMeDavidV** [comment]
Hi @AgentBlonde on your iOS device force close the Tesla app so that it's not running anymore, then open Watchla, goto Preferences -> Setup Virtual Key -> Setup with Tesla -> scroll all the way down -> choose "Setup with Tesla"

If that does not work for you, repeat the above steps but instead of choosing "Setup with Tesla", choose "Setup in Safari". A Tesla web page will appear with instructions, disregard the "Finish Setup" button and instead scroll up and tap the "Open" button on the top right of the screen.

**Comment by AgentBlonde** [comment]
Still nothingNate BlondeOn Feb 5, 2024, at 1:38 AM, David Villegas ***@***.***> wrote:﻿
Hi @AgentBlonde on your iOS device force close the Tesla app so that it's not running anymore, then open Watchla, goto Preferences -> Setup Virtual Key -> Setup with Tesla -> scroll all the way down -> choose "Setup with Tesla"
If that does not work for you, repeat the above steps but instead of choosing "Setup with Tesla", choose "Setup in Safari". A Tesla web page will appear with instructions, disregard the "Finish Setup" button and instead scroll up and tap the "Open" button on the top right of the screen.

**Comment by itsMeDavidV** [comment]
Hi @AgentBlonde you can also directly click the link here: https://tesla.com/_ak/watchla.app however be sure to either close out the Tesla app before opening the link or open the link in Safari. If you open the link in Safari, tap the open button in the top right. 

If that doesn't work for you, please send in a screen video of your attempt so we can better assist.

**Comment by AgentBlonde** [comment]
how can I make sure the Tesla app is shut down?Nate BlondeOn Feb 5, 2024, at 1:55 AM, David Villegas ***@***.***> wrote:﻿
Hi @AgentBlonde you can also directly click the link here: https://tesla.com/_ak/watchla.app however be sure to either close out the Tesla app before opening the link or open the link in Safari. If you open the link in Safari, tap the open button in the top right.

**Comment by itsMeDavidV** [comment]
Hi @AgentBlonde here's a helpful Apple Support article on how to close out an app: https://support.apple.com/en-us/HT201330

**Comment by AgentBlonde** [comment]
yes, that’s what I’ve been doing. I just wanted to make sure.Nate BlondeOn Feb 5, 2024, at 2:18 AM, David Villegas ***@***.***> wrote:﻿
Hi @AgentBlonde here's a helpful Apple Support article on how to close out an app: https://support.apple.com/en-us/HT201330

**Comment by AgentBlonde** [comment]
OK that resolve the issue. Thank you very much.Nate BlondeOn Feb 5, 2024, at 1:55 AM, David Villegas ***@***.***> wrote:﻿
Hi @AgentBlonde you can also directly click the link here: https://tesla.com/_ak/watchla.app however be sure to either close out the Tesla app before opening the link or open the link in Safari. If you open the link in Safari, tap the open button in the top right.

**Comment by itsMeDavidV** [comment]
You're very welcome! Hope you enjoy Watchla!
