### ISSUE TITLE
token expired (401)

### ISSUE THREAD

**Issue by Risbergg** [itsMeDavidV/Watchla-Support#282]
When turning climate on I get Command failed 
Token Expired (401)
.... (Error parsing responce error 0.)
Status code:401

I can lock and unlock the door. So app is not fully disconnected.

**Comment by Risbergg** [comment]
Heeld by it self.

**Comment by itsMeDavidV** [comment]
This is as a result of the recent authentication protocol change that happened last week. Working on enhancing the solutions put in place last week so that this gap does not happen anymore
