### ISSUE TITLE
How to grant permissions for Watchla in Tesla app?

### ISSUE THREAD

**Issue by GizmoStu** [itsMeDavidV/Watchla-Support#283]
I have been using Watchla successfully but there was a bug in a recent release so I was forced to remove and reinstall the app. Naturally I need to grant the app permissions via Security and Third party apps tab in the Tesla app but I can't find how to request access for third party apps. This used to be easy so I don't understand what has happened. Please help.

**Comment by itsMeDavidV** [comment]
Hi @GizmoStu, in order to see Tesla's access prompt again you'll need sign out of Watchla then go into your Tesla account and in the Third Party App access section remove Watchla's access. From there just sign back in to Watchla and you will see the access prompt.

**Comment by GizmoStu** [comment]
I can't see how to sign out. When I open the app this is what I see..
![IMG_1877](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/013b4e53-1bf6-473a-b3fe-0735f80cf70c)

**Comment by GizmoStu** [comment]
![IMG_1878](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/a8573be3-f865-492f-9671-69e35972d841)

**Comment by itsMeDavidV** [comment]
> ![IMG_1878](https://private-user-images.githubusercontent.com/157586068/302952952-a8573be3-f865-492f-9671-69e35972d841.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDMzMjksIm5iZiI6MTcwNzMwMzAyOSwicGF0aCI6Ii8xNTc1ODYwNjgvMzAyOTUyOTUyLWE4NTczYmUzLWY4NjUtNDkyZi05NjcxLTY5ZTM1OTcyZDg0MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMDUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhMTlmYzFhODgwOTc4ZjE4YWM5NDRjNTJmNTk2NjBmZmRkNjVmZjM2NDhiNGJhZTExMzY0NzQzNDcyZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hgcq5WO86NBDeqDvI2bI7ZYe5gWcsj1MHaxpBldlQLQ)

If you are seeing this screen, you are already signed out. Now you'll need to goto your Tesla account and remove access for Watchla under the Third Party App Access section and then re-sign in to Watchla

**Comment by GizmoStu** [comment]
Hi David. Sorry if I'm being dumb but that is exactly what I did. I can see where the app was removed but not how to add it. The Watchla app only gives the choice to sign in with Tesla, which takes me to the screen with the checklist.

**Comment by GizmoStu** [comment]
![IMG_1879](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/dbdabcea-08a2-4ad9-835b-6b2b613ef7b5)

**Comment by GizmoStu** [comment]
I'd really appreciate any further suggestions. Thanks.

**Comment by itsMeDavidV** [comment]
Hi @GizmoStu you're on the right track now all you have to do is sign in with Tesla and go through the permission prompt. When you complete Tesla's permission prompt you will have granted access for Watchla.

**Comment by itsMeDavidV** [comment]
We've requested that Tesla add the ability to edit permissions to avoid having to reset like this in the future.

**Comment by GizmoStu** [comment]
Morning David. I reinstalled Watchla on my iPhone and Watch, then went to my Tesla account but I still get no permissions prompt.

**Comment by GizmoStu** [comment]
How can I get to the permissions prompt in the Tesla app? I have tried everything I can think of. 😕 Completely stuck at the moment.

**Comment by GizmoStu** [comment]
![incoming-C217C6E7-1156-4977-99AF-48790611115A](https://github.com/itsMeDavidV/Watchla-Support/assets/157586068/d1c7d3ed-0a2b-42c5-a836-bd24178be380)

**Comment by GizmoStu** [comment]
Still stuck. Any other ideas?

**Comment by itsMeDavidV** [comment]
> I can't see how to sign out. When I open the app this is what I see.. ![IMG_1877](https://private-user-images.githubusercontent.com/157586068/302951835-013b4e53-1bf6-473a-b3fe-0735f80cf70c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1OTA3NTgsIm5iZiI6MTcwNzU5MDQ1OCwicGF0aCI6Ii8xNTc1ODYwNjgvMzAyOTUxODM1LTAxM2I0ZTUzLTFiZjYtNDczYS1iM2ZlLTA3MzVmODBjZjcwYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxODQwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWU3ZmFiYzU3MGZkNWJhMDcxYjMzOGIwZGFhNzcxYmI0ZDIzNDU2ZGZlNWJkNmMyNTQ3ZjY1YzA5YTY5MDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iKboDedDvnaKwk2f-mIQPWvlfOxOyQVcdFqaZJ3w7J8)

Hi @GizmoStu starting from this screen, scroll down and tap "Okay" you should be taken to the Tesla sign in web page

**Comment by GizmoStu** [comment]
This screen is static and doesn’t scroll down or up or move at all. The
only action is to swipe up to close it. 🫤

**Comment by itsMeDavidV** [comment]
Sorry about that! Just realized this is an issue on smaller screens. We will update this very soon. For now, you can tap the blue button appearing at the bottom edge of the screen and that should take you to the sign in screen.

**Comment by GizmoStu** [comment]
After a few goes at tapping the thin blue line it finally worked!
Thank you so much for your help.

**Comment by itsMeDavidV** [comment]
Awesome, very glad to hear that!
