### ISSUE TITLE
Watch app firmware version not updated?

### ISSUE THREAD

**Issue by Gr1ss0m** [itsMeDavidV/Watchla-Support#289]
With the new phone firmware 3.6.1 I don't see a corresponding version for the app on the watch. Still on 3.5.8. Watch App Store does not show available update. 
Is there a newer one? Or coming?
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/157122657/155e72ab-a3a8-48eb-ba54-b4c745105ad7)

**Comment by skipcooney** [comment]
My watch shows ver 3.6.1

**Comment by itsMeDavidV** [comment]
There is a new update out v3.6.1, sometimes the Apple Watch can lag behind iOS devices in terms of getting updates pushed to them. v3.6.2 should be out very soon, I'd hold off until that update comes around.

**Comment by Gr1ss0m** [comment]
Thx. Somehow the app did update.
Now it is in the same version as the phone.

**Comment by itsMeDavidV** [comment]
Also v3.6.3 is out, I'd recommend updating to that version
