### ISSUE TITLE
Watch App stuck on "To sign in..." but iOS app it's ok.

### ISSUE THREAD

**Issue by BrunCos** [itsMeDavidV/Watchla-Support#29]
Try to restart iOS and WatchOS, try to sign in and out, try to refresh watch app without results.

**Comment by itsMeDavidV** [comment]
@BrunCos If after the steps above the issue still does not resolve, then you most likely have a pairing issue between your Apple Watch and iOS device.

**Comment by itsMeDavidV** [comment]
@BrunCos Is this issue still occurring for you? 

Given the time since your last comment, I'll assume it did and close this issue. But if it didn't please feel free to re-open the issue.
