### ISSUE TITLE
With latest watchOS 10.3.1 doesn’t work

### ISSUE THREAD

**Issue by urkiata** [itsMeDavidV/Watchla-Support#293]
Hello,
I used Watchla for several months, it worked nice but since I updated to the latest watchOS 10.3.1 it stops to work: Watchla now show a prompt for Bluetooth connection required. Of course my Bluetooth is on and works normally but seems that Watchla doesn’t see Bluetooth is already available. By cellular connection doesn’t work too. 
Please fix this huge issue. 
Device Apple Watch Ultra 1.

**Comment by krsnan11** [comment]
Agreed… concordato …. Not funzionare watchla … molti problemi my friends! PLEASE ADDRESS… can’t open my Tesla anymore .. all of a sudden

**Comment by itsMeDavidV** [comment]
Hi @urkiata & @krsnan11 can you send over your Watchla support codes via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
