### ISSUE TITLE
App do not wake up the car.

### ISSUE THREAD

**Issue by Risbergg** [itsMeDavidV/Watchla-Support#299]
I have problem to wake up the car. I have to use the iPhone to wake up. Thereafter  all commands working as expected

**Comment by itsMeDavidV** [comment]
Hi @Risbergg we fixed a small bug that caused some wake issues in v3.6.4, please update to at least v3.6.6 or newer

**Comment by Risbergg** [comment]
Ok will try.
I notised in the release note that 3.6.6.should be available on watch. I only got 3.6.5. I will give it a try to see if it is available before testing to wake up the vehicle.
On iPhone I installed 3.6.6.
Is there a way to get iPhone to force the update or do I have to use appstore on Watch to get the update?

**Comment by Risbergg** [comment]
I performed some tests today after update the app. It looks so far working as expected.
Only glitch is that it takes long time to wake the vehicle.
We can close this issue.
