### ISSUE TITLE
Trunk bottom

### ISSUE THREAD

**Issue by Aicrag22** [itsMeDavidV/Watchla-Support#3]
Hi. It’s not possible to close the trunk. 
the app only permit to open. 
please check it

**Comment by itsMeDavidV** [comment]
Hi thanks for reporting this. I will look into it and report back with an update soon.

**Comment by itsMeDavidV** [comment]
Hi  @Aicrag22 , just wanted to let you know that this bug has been identified and fixed. The fix will be included in the next App Store update of Watchla, version 1.50. This update has been sent to Apple review and should be out within the coming day. Once it is out I will close this issue.

Thanks again for reporting this!

**Comment by itsMeDavidV** [comment]
Update 1.50 is now out on the App Store and in that update this issue has been fixed.

Thanks!
