### ISSUE TITLE
Apple watch issue

### ISSUE THREAD

**Issue by Rkhapa** [itsMeDavidV/Watchla-Support#30]
App on apple watch keep saying authenticate on the phone app. I have already done that and before you ask I have restarted both

**Comment by itsMeDavidV** [comment]
Hi @Rkhapa on the iOS app, goto Preferences and tap "Refresh watch app". This will force send your authentication details to your watch and allow it to sign in.

If the above does not work, be sure that
- both devices have bluetooth on
- are connected to each other
- and that your Apple Watch is not experiencing pairing issues with your iOS device.

**Comment by itsMeDavidV** [comment]
Given the time since a last response, I'm assuming this issue was resolved and closing this issue. If not, please feel free to re-open it. 

Thanks,
-David
