### ISSUE TITLE
why dosent IT not working again

### ISSUE THREAD

**Issue by Kennethol** [itsMeDavidV/Watchla-Support#300]
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/86203790/506a1bdc-207b-43cb-af75-f254001a25e4)

**Comment by Kennethol** [comment]
> ![image](https://github.com/itsMeDavidV/Watchla-Support/assets/86203790/506a1bdc-207b-43cb-af75-f254001a25e4)

App 3.6.3

**Comment by Risbergg** [comment]
I have to reboot watch and force logout and re/authenticate to solve this issue. Most annoying.

**Comment by Kennethol** [comment]
Its working now arter update

**Comment by itsMeDavidV** [comment]
Hi @Risbergg @Kennethol can you both send over your Watchla support code via https://watchla.app/contact so this issue can be investigated?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
