### ISSUE TITLE
The app not working 

### ISSUE THREAD

**Issue by beni75-tech** [itsMeDavidV/Watchla-Support#303]
The app refuse to work not on my iphone 15 pro max and not on my apple watch ultra, i reinstall it several times and no results. Now i can’t even install it on the watch and it’s doing nothing on the iphone. 
please resolve it.

**Comment by itsMeDavidV** [comment]
Hi @beni75-tech sorry to hear that have can you send over your Watchla support code via https://watchla.app/contact so this can be investigated? Please be sure to reference this issue if you do.

**Comment by beni75-tech** [comment]
Hi, now it’s seems to be ok, i did log out and sign in again, now it’s
working.
