### ISSUE TITLE
Not signing in

### ISSUE THREAD

**Issue by pssturges** [itsMeDavidV/Watchla-Support#304]
Ive been using watchla for a while. Since the changes, things haven't been working well. I had re-signed in when prompted. I can't remember the exact sequence of events, but I've ended up uninstalling, confirmed app data was gone from phone, made sure watch app removed, deleted icloud data and deleted access from tesla account. When I re-install the phone app, I get no opportunity to sign in and just get a spinning wheel, but can see my vin still showing in the background. This never ends and i have no opportunity to sign in or out. Any help appreciated. 
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/32161518/85d1f97b-fea6-4703-9821-c179fe76ec63)

**Comment by pssturges** [comment]
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/32161518/7f360a9d-50b8-411b-9047-5441e8518dc4)

**Comment by itsMeDavidV** [comment]
Hi @pssturges sorry to hear about this. It looks like the loading screen on the screenshot you provided was blocking you from performing actions like authenticating the watch app so in v3.6.6 we removed the full-screen loading screen for most cases. 

V3.6.6 is [available now for download](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747) and you should be able to authenticate your watch app in preferences on the iOS app.

Also keep in mind, if you have reset Watchla's permissions in your Tesla account you will need to sign out and sign back in to Watchla and accept the permissions  requests presented at sign in.

**Comment by pssturges** [comment]
Ok thanks. Yes that seems to have fixed it

**Comment by itsMeDavidV** [comment]
You're very welcome, glad to hear that!
