### ISSUE TITLE
Error code 403

### ISSUE THREAD

**Issue by andykab** [itsMeDavidV/Watchla-Support#305]
My wife and I both have each an iPhone 11 and each has iwatch9. My iwatch works fine with Siri commands as well direct taps on the iwatch Watchla app. 

However, my wife’s iwatch keeps getting error or status code 403. Siri commands don’t go through. Always says something went wrong. 

What are we doing wrong?

**Comment by itsMeDavidV** [comment]
Hi @andykab most likely your wife did not allow Watchla all the necessary permissions at sign in. If you'd like to send over her Watchla support code via https://watchla.app/contact I'd be happy to investigate. If you do, please be sure to reference this issue.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
