### ISSUE TITLE
Can’t install app on watch

### ISSUE THREAD

**Issue by ngkonchin** [itsMeDavidV/Watchla-Support#307]
Recent updates killed Watchla on my watch. The app won’t install, tap on install the icon spin then nothing. I tried a different app and it installed correctly.

**Comment by itsMeDavidV** [comment]
Hi @ngkonchin unfortunately developers have no control over how you Apple Watch downloads apps. But as a work-around, I'd recommend downloading Watchla from the App Store app directly on your Apple Watch.

**Comment by Risbergg** [comment]
Or backup your watch and do a new pairing of your watch from the backup. I had to do that twice to install watchla and other apps.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
