### ISSUE TITLE
Does not open anymore 

### ISSUE THREAD

**Issue by Claudehuot** [itsMeDavidV/Watchla-Support#31]
Get stock on : « to sign in » and the authla is stuck at the same place 

Claude Huot 

claudehuot@icloud.com 
514-513-8102

**Comment by itsMeDavidV** [comment]
@Claudehuot With the release of version 2.0, automatic sign in via Authla has been discontinued. 

Instead use Watchla's new iOS companion app to sign in with Tesla. Once signed in your authentication status will automatically transfer over to the watch app where you will be signed in there as well.

You can download Watchla's new iOS companion app here: https://apps.apple.com/us/app/watchla-for-tesla/id1546599747

**Comment by Claudehuot** [comment]
Yes thanks , its working fine now 

The only thing left is the SIRI commands 

Siri does not recognize these commands ? Example « lock my Tesla «  ?



Claude Huot 
***@***.***
514-513-8102

**Comment by itsMeDavidV** [comment]
@Claudehuot good I'm glad to hear that!

To use Siri Shortcuts open Watchla's iOS app then goto Preferences -> Siri Shortcuts and then add the ones you'd like to use!

There's also a lot of helpful info on Siri Shortcuts and more found on our FAQs here: https://watchla.app/faqs/

Hope this info helps!
