### ISSUE TITLE
Cannot sign my watch in 

### ISSUE THREAD

**Issue by AlexLxv** [itsMeDavidV/Watchla-Support#311]
As others have stated. V3.6.6(377)

![IMG_8555](https://github.com/itsMeDavidV/Watchla-Support/assets/49344643/8aa4fce2-3c36-46f8-80e6-489f7e85258a)

**Comment by itsMeDavidV** [comment]
Hi @AlexLxv there are only 2 reasons why this occurs if you have signed into the watch app on the iOS app:

1: Your Apple Watch and paired iOS device are not communicating properly or have mismatching versions of Watchla installed.
2: iCloud is not enabled for your Apple Watch or for Watchla ( you can check this on your iOS device in Settings > Apple ID > iCloud > Apps using iCloud > (Watchla should be toggled on).

Please let me know if you can't get this issue resolved as I can take a look at any error logs that might point to an issue related to this via your Watchla support code.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
