### ISSUE TITLE
Watch complication showing empty bar without any data

### ISSUE THREAD

**Issue by Lovegodtesla** [itsMeDavidV/Watchla-Support#319]
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/157220220/0c493684-2df5-4d51-807d-63fb3fcebc71)

**Comment by itsMeDavidV** [comment]
Hi @Lovegodtesla sorry to hear about that. We're constantly re-iterating on complications to provide the most data, the most reliably under the strict limitations that watchOS's battery management system imposes. As more updates come you should see this less and less. 

Currently are you seeing any other errors in the watch app? Also, if you'd like to send over your Watchla support code via https://watchla.app/contact, I'd be happy to take a look and see if you are experiencing any underlying errors that might contribute to this issue.

**Comment by Lovegodtesla** [comment]
Hi David, I just sent you the support code. There are no other operating problems, the Apple watch is connected to the tesla and everything works fine. Except for the problem of complications. The strange thing is that for about 10 days the complication worked correctly by showing the right values. Then something went wrong and I don't see the values anymore (as in the photo)

**Comment by Lovegodtesla** [comment]
Hi David, I updated to version 3.6.8. Now everything works. Well done![image](https://github.com/itsMeDavidV/Watchla-Support/assets/157220220/03f1d377-69da-40b7-93c2-5dc133ea5722)

**Comment by itsMeDavidV** [comment]
@Lovegodtesla Awesome glad to hear that and thank you!
