### ISSUE TITLE
Siri commands not recognized on iPhone or Apple Watch

### ISSUE THREAD

**Issue by aembermoon** [itsMeDavidV/Watchla-Support#32]
Unfortunately, when I voice command something like “Hey Siri, open charge port”, Siri doesn’t recognize it as a Watchla command. Initially, it would say I need Home Kit to use the command. Now, saying the command on the watch, it tells me I don’t have an app called “charge port”.  Saying it on iPhone results in a view of my phone battery status. I have an iPhone 13 Pro Max running iOS 15.3.1. I did verify on the app that the Siri commands are active.

![Uploading 621A1F1B-D42A-4651-9F2E-AC7F882BCB12.jpeg…]()
![Uploading 83EBB882-400A-4367-A70C-CC7C7808E6A2.png…]()
![Uploading 09DAE9ED-E5DD-42B6-9256-CA46DF9DA471.png…]()

**Comment by itsMeDavidV** [comment]
@aembermoon Sorry for the frustration, sometimes Apple makes onboarding Siri Shortcuts a bit of a hassle in the beginning.

Here's what you should expect (example):

-> (on your phone) goto the Watchla iOS app
-> goto Preferences -> Siri Shortcuts
-> scroll to Open charge port, then tap "Add to Siri"
-> it will prompt you to confirm a voice phrase (Eg: "Hey Siri, Open charge port") This will be the phrase that Siri will identify as the trigger for that particular shortcut. You can edit it to be anything you like.
-> once confirmed, you can begin to call that voice phrase to Siri and she will respond. L
-> the very first call to Siri for this shortcut will prompt a privacy question from Siri saying something like "Allow Watchla to...?" Tap or say allow. This will allow this shortcut to be used in the future.

Now to enable this Siri shortcut on your watch, goto the Shortcuts app on your phone and find the shortcut you just added (Eg: open charge port).

From there, 
-> tap the 3 dots button
-> then tap the settings button
-> and toggle the switch that reads "Show on Apple Watch"

You can then begin to use that Siri shortcut on your Watch as well. It will prompt you again for the privacy question on the watch. It might take a bit for the Siri Shortcut to install on your watch. To speed up the process, just goto the shortcuts app on your watch and force close it then re-open. Your shortcut should then populate on the screen.

I hope this info is helpful, please don't hesitate to reach out with any questions.

-David

**Comment by itsMeDavidV** [comment]
Also if Siri doesn't like a particular phrase you can always change it to anything you'd like so she can better detect the shortcut.

**Comment by itsMeDavidV** [comment]
Hi @aembermoon  is this issue still occurring for you?

**Comment by itsMeDavidV** [comment]
Closing this. Feel free to re-open if the issue still persists.
