### ISSUE TITLE
IOS app crashes on launch

### ISSUE THREAD

**Issue by jasmee1979** [itsMeDavidV/Watchla-Support#320]
The IOS app crashes as soon as it is opened.
The list of issues with this app seems to be getting worse rather than better which each update since the API change.

**Comment by itsMeDavidV** [comment]
Hi @jasmee1979 sorry about that. We've fixed this issue and will be releasing an update with the fix soon.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
