### ISSUE TITLE
Please for heavens sake ! Stop pushing the updates 

### ISSUE THREAD

**Issue by rgurrala** [itsMeDavidV/Watchla-Support#327]
Each time you push an update the app wants  me to re authenticate..
Can’t take this any more .

**Comment by itsMeDavidV** [comment]
Hi @rgurrala this shouldn't be happening. Can you send over your Watchla support code via https://watchla.app/contact so we can investigate? Thanks.

In the meantime, I'd recommend turning off automatic app updates for Watchla as we obviously cannot stop updates.

**Comment by rgurrala** [comment]
Sorry didn’t mean to be rude there ! The app was working fine till the latest update.  So vented out , apologies !

**Comment by rgurrala** [comment]
Ok will do

**Comment by itsMeDavidV** [comment]
Hi @rgurrala no worries, totally understand that this can be frustrating.

To get your Watchla support code, goto Preferences > Support/Feedback > Support code
