### ISSUE TITLE
 Can’t add complications to watch face

### ISSUE THREAD

**Issue by mlhw** [itsMeDavidV/Watchla-Support#34]
I can’t find and add watch face face complications from the Watchla app. I have the watch app up and  running and that works, but there is no complications for Watchla available in the list of possible complications to add to my watch face. 

![E1E5A0FC-3D61-44E8-AAC7-FB64C1530996](https://user-images.githubusercontent.com/13869815/155854565-c413be4e-f493-416f-af76-d4f3c432472e.png)

Do I need to do anything for them to be available?

I’m running iPhone 13 pro max with iOS 15.2.1
And an Apple watch 7 with watchOS 8.4.2

**Comment by itsMeDavidV** [comment]
Hi @mlhw sorry to hear that you're experiencing this issue. Is the issue still occurring?

Also can you confirm with me which version of Watchla you have installed on your watch? You can find version info by going to the Preferences screen and scrolling all the way down. 

Given that you have Watchla's watch app installed and have initially opened it, you should still be able to add/edit complications from your Apple Watch itself (an alternative option to doing so on your iOS device). If you aren't familiar, there's a helpful guide on how to do that here: https://support.apple.com/guide/watch/customize-the-watch-face-apda6559ad78/watchos

Now as for recommendations on how to remedy this, here are a few things I'd try:
(note: list in order of "If this doesn't work, then try this")

- Restart the "Watch" app on your paired iOS device
- Confirm that your Apple Watch is paired correctly with the iOS device and that it shows on the "Watch" app that Watchla is installed.
- Restart your Apple Watch
- Restart your iOS device
- Delete Watchla from your Watch and reinstall it
- Repair your Apple Watch to your iOS device

Please let me know whether this works or not.

Thanks,
-David

**Comment by itsMeDavidV** [comment]
Going to assume this issue was remedied due to no response and am closing. If the issue persists, feel free to re-open.

**Comment by mlhw** [comment]
Unpairing and pairing the watch with my iPhone again fixed the issue.

**Comment by itsMeDavidV** [comment]
@mlhw ah ok, good to hear it worked out!
