### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Ianhed** [itsMeDavidV/Watchla-Support#340]
App crashes when you try to starting it, just a quick flash of the logo. iPhone 15 plus, iOS 17.4. 

Watchla version 3.7.1 but it was the same issue with 3.6.9. I've tried to delete and reinstall the app twice.

**Comment by Ianhed** [comment]
Am I the only one having this problem. I need tips how to get Watchla working again. Unusable for almost a week now.

**Comment by itsMeDavidV** [comment]
Hi @Ianhed thanks for reporting this. Can you reach out to us via https://watchla.app/contact with your support code?

**Comment by Ianhed** [comment]
Hi!

I think already did this earlier today. But I can do it again

**Comment by Ianhed** [comment]
After a fourth try to reinstall the app it suddenly works.

**Comment by itsMeDavidV** [comment]
Hi @Ianhed I sent you an email.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
