### ISSUE TITLE
Battery level is not synchronized with Apple Watch widget

### ISSUE THREAD

**Issue by Jerome8620** [itsMeDavidV/Watchla-Support#341]
Apple Watch battery level widget show 69% level while it’s 45% since 2 days… 
Sentry mode On/off doesn’t work.

**Comment by itsMeDavidV** [comment]
Hi @Jerome8620 thanks for reporting this. It could be that you need to re-authenticate the watch app. To do this open the iOS app and goto Preferences > authenticate watch app. 

Additionally if you send over your Watchla support code via https://watchla.app/contact we can investigate and report back on what might be going wrong here. If you do send your support code, please be sure to link to this issue.

**Comment by chensotte** [comment]
Hi, same problem after reauth. Christophe

**Comment by chensotte** [comment]
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/42737207/106d9f3f-8ea3-4e41-8989-dda217e54a4b) actually 85% on my new Tesla

**Comment by CassandraMarie** [comment]
Hi @chensotte, Can you please send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out. Thank you

**Comment by chensotte** [comment]
Hi,

It’s ok now! 😉👍
You can close this case.

Regards,
Christophe


Christophe HENSOTTE
Rue du Centre, 12
B-5530 Mont-Godinne (Namur)
***@***.***
00 32 (0) 498 90 88 12


Le jeu. 2 mai 2024 à 23:36, Cassandra Marie ***@***.***> a
écrit :

**Comment by CassandraMarie** [comment]
@chensotte Happy to hear that! Thank you

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
