### ISSUE TITLE
Please respond to issue #323.

### ISSUE THREAD

**Issue by tophermiller** [itsMeDavidV/Watchla-Support#342]
I filed support issue #323 over 2 weeks ago and nobody has responded.    Please help!   So far, I have paid for the Watchla app and it is useless to me because of this issue.    If I can't get help I will have to resort to leaving a negative review.

**Comment by itsMeDavidV** [comment]
Hi @tophermiller sorry about that, with everything going we must've missed your issue. I'll close this and respond there to prevent duplicate issues.
