### ISSUE TITLE
Siri & shortcut not a friend with homelink

### ISSUE THREAD

**Issue by Risbergg** [itsMeDavidV/Watchla-Support#344]
Since latest app upgrade Siri is not able to trigger homelink. Finally I managed to get the shortcut to apple watch. When activate either manually or with Siri the homelink is trigged but no action is taken.
Trying to use other shortcut like flash light works perfectly well.
How do I get the shortcut to trigger homelink and run the action (open door) defined at the geo position?
Regards Gunnar.

**Comment by itsMeDavidV** [comment]
Hi @Risbergg thanks for reporting this. Can you send over your Watchla support code via https://watchla.app/contact so that we can investigate and report back? Please be sure to link to this issue.

**Comment by Risbergg** [comment]
Done. Hope it helps solving

**Comment by Risbergg** [comment]
Is there any uppdate on this issue?

**Comment by Risbergg** [comment]
@itsMeDavidV , how is it going? Do you find any logic why homelink is trigged but no action is sent from the vehicle?

**Comment by Risbergg** [comment]
@CassandraMarie , I have not heared from you regarding homelink issue. Is there any progress?

**Comment by itsMeDavidV** [comment]
Hi @Risbergg sorry for the delay, we're in the process of auditing our location-dependent related Shortcuts commands (eg: Homelink). We will update back here soon.

**Comment by itsMeDavidV** [comment]
Hi @Risbergg we've identified the root of the issue and implemented a fix. I've had a TestFlight invite to Watchla's beta emailed over to you, in case you would like to test the solution. Otherwise, the fix for this issue will be included in Watchla's next update.

**Comment by Risbergg** [comment]
Hi @itsMeDavidV thanks for letting me try it. Unfortunately I did not get it to work. First I downloaded the app and verified version on both phone and watch. No progress. Then I reenabled the shortcut on watch. No change. Third I upgraded whatchOS that was pending and refreshed the chortcut. Finally I removed and recreated the shortcut.
Now I did two tests 1) added shortcut to siri in the app and refresh watch app. Error: an unexpected error occured. Then I went in to shortcut on phone and added it to watch. Now the shortcut is trigged by siri with positive message on the watch. Unfortunately homelink is not trigged by the car.
As usuall other shortcut works fine and homelink works from the watch face.
Can I do some other tests? Am I missing any step in the enablement?

**Comment by itsMeDavidV** [comment]
Hi @Risbergg thanks for reporting this, it's very helpful. We've made additional changes based on your feedback that should solve this issue for you in v3.8.1 (443).

Can you retry triggering Homelink from both Siri Shortcuts and from the Homelink complication on the new beta update? Thanks!

**Comment by Risbergg** [comment]
Hi @itsMeDavidV Yes. Now it works perfectly. I fried it with Siri both on watch and iPhone. The complication also works as expected.

Than you for all good work.
Gunnar

**Comment by itsMeDavidV** [comment]
Hi @Risbergg that's great to hear, you're very welcome! I apologize for the delay in getting this fixed as its been quite a busy time at Watchla.

I'll close this issue after the release of this update to the App Store so that anyone else facing this issue can reference this thread.

**Comment by Risbergg** [comment]
Hi @itsMeDavidV It's me again :) 
Homelink works as designed both on complication and Siri shortcut. 
There is a smal glitch. Even if I activares watchla on the watch and wait for the vehicle to wake up, a majority of the time the shortcut takes to long and time out. Pressing the icon on watch face works there after the shortcut use to work.
It is some intermittent timing issues and time out problems.
//Gunnar

**Comment by Risbergg** [comment]
@itsMeDavidV , @CassandraMarie 
Believe or not...
Now I have tried to use siri and homelink after latest sw upgrade.
Siri,shortcut+Homelink now works as expected the latest couple days.

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
