### ISSUE TITLE
Car's appearance is different

### ISSUE THREAD

**Issue by claire078** [itsMeDavidV/Watchla-Support#345]
Today I have changed my tires and car's appearance have not changed in Watchla app.
![9FC70E31-F758-4BB7-A5E6-EBE22DCB0312_1_201_a](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/cc4347af-83f1-4596-a15b-850ae8b16333)
![86DA39BF-2302-483A-88B4-C0C983CB95C0_4_5005_c](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/0f925311-5fad-41f1-99d9-7dd1188ed38c)
![EE94D30A-FB7D-4E45-A346-13B4A9EF1AAE_4_5005_c](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/5ebf4ba9-87c6-4128-a50b-a61f494d1853)

**Comment by itsMeDavidV** [comment]
Hi @claire078, unfortunately these in-app/vehicle appearance changes are only accessible by Tesla and Tesla does not share these changes with developers :(

However we are considering implementing our own version of this.
