### ISSUE TITLE
Sentry control does not work

### ISSUE THREAD

**Issue by claire078** [itsMeDavidV/Watchla-Support#346]
Simple, I can not switch off Sentry.
Tap on Turn off but makes nothing. App restart have not helped.
![520B79E6-8FC4-4C5F-AA6E-1B8C701B4BC7_4_5005_c](https://github.com/itsMeDavidV/Watchla-Support/assets/46406097/50235d76-31aa-492a-9653-592bc90bdb0b)

**Comment by itsMeDavidV** [comment]
Hi @claire078 is this issue still occurring for you on version 3.7.2?

**Comment by claire078** [comment]
> Hi @claire078 is this issue still occurring for you on version 3.7.2?

yes, it does.
now tried.

**Comment by CassandraMarie** [comment]
Hi @claire078, we apologize for the delayed response, this issue has been fixed.
