### ISSUE TITLE
apple watch ultra screen blanking out when accessing the watchla app

### ISSUE THREAD

**Issue by rgurrala** [itsMeDavidV/Watchla-Support#347]
what seems to be the issue- apple watch screen blanks out intermittently when accessing the watchla app. i am using the apple watch as sole key

mobile phone details-
 iPhone 13 pro max
IOS version-17.4.1
watchla app version- 3.7.2(409)

watch details
apple watch ultra
variant -1 
IOS- 10.4 
watchla app- 3.7.2(409)

**Comment by CassandraMarie** [comment]
Hi @rgurrala, we are sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out. Thank you!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. If the problem continues or arises again, please feel free to reopen the issue or reach out for more help.

**Comment by rgurrala** [comment]
Apologies for the late reply. This issue is fixed after I replaced my watch under warranty.

**Comment by CassandraMarie** [comment]
No worries, glad to hear everything is working for you!
