### ISSUE TITLE
Siri Issue

### ISSUE THREAD

**Issue by WillowFarm** [itsMeDavidV/Watchla-Support#35]
When I try and use a Siri command I get this on my watch...
'I'll need to access your watch for Tesla data to do this. Please do this on your iPhone'
I can't see where to do this on my iPhone so please help. Thanks!  (my iWatch is not a cellular iWatch although it's very new)

**Comment by WillowFarm** [comment]
Don't worry, over figured it out! 😃

**Comment by itsMeDavidV** [comment]
@WillowFarm Glad to hear that! Let me know if there are any other issues.

**Comment by WillowFarm** [comment]
Hi David

Thank you for coming back to me. Only a day into using the app and already loving it!

Regards

ERIC

________________________________

Eric Riley
Sales & Marketing Director, Illuma Lighting
T: +44(0)1332 818200M: +44(0)7798 767 767
E: ***@***.***: Eric_Riley
 W: www.illuma.co.uk
A: Sills Road, Willow Farm Business Park, Castle Donington, Derbyshire, 
DE74 2US, United Kingdom
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender and delete the e-mail entirely from your system. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by itsMeDavidV** [comment]
@WillowFarm that's awesome, I'm really glad to hear that you're loving the app! Please do consider giving an app review or rating as they really help Watchla grow!
