### ISSUE TITLE
Watchla not switching vehicle

### ISSUE THREAD

**Issue by lisa143103** [itsMeDavidV/Watchla-Support#352]
Watchla app not letting me select my Tesla but will only default to my husbands. Unable to use the commands

**Comment by itsMeDavidV** [comment]
Hi @lisa143103 we'll take a look into this. Can you send over your Watchla support code via https://watchla/app/contact so we can investigate? Thanks!

**Comment by fairdocument** [comment]
I have the same issue. Is there a good resolution?

**Comment by lisa143103** [comment]
> I have the same issue. Is there a good resolution?

I just emailed “Hi @lisa143103 we'll take a look into this. Can you send over your Watchla support code via https://watchla/app/contact so we can investigate? Thanks!” And it resolved on its own in a couple days before they emailed me back so not sure what the issue was. It still can be glitchy but last I checked was letting me switch vehicles.

**Comment by CassandraMarie** [comment]
Hi @fairdocument, Can you send over your Watchla support code via https://watchla/app/contact so we can investigate? Thanks!

**Comment by CassandraMarie** [comment]
This issue has been resolved with update 3.8.3. Please update your devices.
