### ISSUE TITLE
Not getting vehicle info nor listing vehicles but commands work

### ISSUE THREAD

**Issue by mezzomix23** [itsMeDavidV/Watchla-Support#354]
Greetings,

Since last update, the watch complications do not work, when the app is opened on the watch, shows vehicle as 0% battery, and I cannot select the vehicle, just get the circle looping, trying to retrieve the list.

Commands, from the watch, when tapping on them in the app work.

**Comment by mezzomix23** [comment]
Anyone? It's been 3 weeks now and no resolution.

This is how the complication looks like (I've removed the car name):
![incoming-146778BE-CEA4-4E7C-A19A-8276F07AC24B](https://github.com/itsMeDavidV/Watchla-Support/assets/16504992/62bb4112-9c3f-4b63-86e4-5e6228be455f)

And inside the app, showing 0% and not the actual %:
![incoming-F9B03DC3-29B9-4CE3-9052-1861D14731B8](https://github.com/itsMeDavidV/Watchla-Support/assets/16504992/0818de15-8ad2-480e-baf1-8652345a5d1b)

Finally when trying to list the vehicles:
![incoming-2D586CC6-2748-4473-8021-A729F9502D57](https://github.com/itsMeDavidV/Watchla-Support/assets/16504992/cc71ede2-d036-4057-8dea-1b36ea1fc99d)

I've the latest version from the App Store. Tried signing out, reinstalling, nothing.

The information displayed in the app on the phone is correct, right % and range and statuses, only the watch app is not working properly anymore.

**Comment by itsMeDavidV** [comment]
Hi @mezzomix23 sorry about that. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by mezzomix23** [comment]
Thanks for the reply. I just sent it, as requested.

**Comment by itsMeDavidV** [comment]
Hi @mezzomix23 thanks for sending that over, we appreciate it. After reviewing the error logs associated with your support code I can confirm that these issues stem from an authentication issue bug. We are currently testing a fix to this issue in beta that has so far demonstrated very positive results. 

I have gone ahead and had a TestFlight invite to Watchla's beta app emailed over to you in case you would like to help validate the solution. 

If not, that's all good, rest assured the solution to this issue will be available in a new update in the coming days.

**Comment by mezzomix23** [comment]
Hi David!

Thank you for the beta invite, I love being part of them 😊

Just installed it, re-authenticated the Apple Watch and now the information is correct 😊

If there is anything else you'd like me to test, let me know.

Should I close this issue now?
