### ISSUE TITLE
Apple Watch Ultra no symbol coming out *Blank*

### ISSUE THREAD

**Issue by alvintiong** [itsMeDavidV/Watchla-Support#355]
After the latest 2024.8.9 update from the car, watchla broke again.

Anyone having the same issue? Watchla icon not showing up.

Why it kept broken for the past few month.

**Comment by alvintiong** [comment]
Just realised watchla removed the widget in apple watch. No longer able to add anything to watch face but app still installed within the watch.

**Comment by CassandraMarie** [comment]
Hi @alvintiong, we are sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by alvintiong** [comment]
Hi,

My support code is [redacted].

Hopefully you are able to help. Currently there are still no widget available on my watch ultra. It is completely gone. Can’t even find it. I can only go from the app list.

Cheers.

Regards,
Alvin

On 3 May 2024, at 4:06 AM, Cassandra Marie ***@***.***> wrote:

﻿

Hi @alvintiong<https://github.com/alvintiong>, we are sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by itsMeDavidV** [comment]
Hi @alvintiong sorry for the late reply. Can you send over your updated support code from the watch app? From your prior support code we can see that Watchla was connecting to your vehicle mostly fine from the widgets extension of the app (responsible for complications). Can you also identify what particular widget is no longer appearing?

**Comment by alvintiong** [comment]
Hi David,

Please refer to the attached photo.

The first photo is the code and the second is the complication that we adjust in Apple Watch app on iPhone but can’t find it as you can see on the photo.
Please help.
[image0.jpeg][image1.png]
Regards,
Alvin

On 4 May 2024, at 5:06 AM, David Villegas ***@***.***> wrote:

﻿

Hi @alvintiong<https://github.com/alvintiong> sorry for the late reply. Can you send over your updated support code from the watch app? From your prior support code we can see that Watchla was connecting to your vehicle mostly fine form the widgets extension of the app (responsible for complications). Can you also identify what particular widget is no longer appearing?

**Comment by CassandraMarie** [comment]
Hi @alvintiong, It seems your image failed to upload properly.

**Comment by alvintiong** [comment]
Hi, please refers to the attached photo. There are no watchla complication showing in my Apple Watch. It is gone. Used to be there. 
![IMG_6366](https://github.com/itsMeDavidV/Watchla-Support/assets/166688635/20897664-b7b0-4f99-8985-448dc60fee73)

**Comment by CassandraMarie** [comment]
Hi @alvintiong, thank you for your patience and support, we understand how frustrating this may be. 

Complications on the Watch OS are currently facing strict limitations by Apple Watch's battery management system on when and how frequently apps like Watchla can update complications. 

Recently, Watchla underwent significant changes to authentication management that have hindered its current protocol for updating complications. 

Good news, we are currently developing a solution to improve and enhance the reliability of complication updates.
In the meantime, we recommend staying up to date with the latest version.

**Comment by itsMeDavidV** [comment]
Hi @alvintiong additionally by the image your provided it seems as though you faced a watchOS bug where your Apple Watch did not register the complications provided by Watchla. You will most likely need to delete and re-install the Watchla watch app to correct this issue. You can first try restarting your Apple Watch, but you might ultimately have to re-install Watchla.

**Comment by alvintiong** [comment]
> Hi @alvintiong additionally by the image your provided it seems as though you faced a watchOS bug where your Apple Watch did not register the complications provided by Watchla. You will most likely need to delete and re-install the Watchla watch app to correct this issue. You can first try restarting your Apple Watch, but you might ultimately have to re-install Watchla.

Thanks. I uninstall and restart the watch then reinstall. Seem to fix the problem now.
Cheers.

**Comment by CassandraMarie** [comment]
Great news!! I am going to close this issue. Should the problem persist or reoccur, please don't hesitate to reopen it.
