### ISSUE TITLE
Watchla issue

### ISSUE THREAD

**Issue by Sidbahl1** [itsMeDavidV/Watchla-Support#356]
Hello, I purchased your app a few days ago. Through the app, I have a function on my Apple Watch screen set up so I can see range/battery. However, it is not updating automatically. I have to click the function (which opens the Watchla app on my watch) in order for it to update. Please advise on how to fix this. Thanks.

**Comment by CassandraMarie** [comment]
Hi @Sidbahl1 I have replied to you via email.

**Comment by CassandraMarie** [comment]
We're currently handling this issue via email.  If the problem persists or arises again, please feel free to reopen the issue or reach out for further assistance.
