### ISSUE TITLE
Constantly need to reauthenticate

### ISSUE THREAD

**Issue by bradleyjwatson** [itsMeDavidV/Watchla-Support#357]
I need to sign in to Tesla account in Watchla app at least every few days  to reauthenticate

**Comment by CassandraMarie** [comment]
Hi @bradleyjwatson, we are sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by bradleyjwatson** [comment]
Best RegardsBrad WatsonSent from my iPhoneOn 3 May 2024, at 06:04, Cassandra Marie ***@***.***> wrote:﻿
Hi @bradleyjwatson, we are sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?
Support codes can be found by going to Preferences > Support/ Feedback > Support code
Please be sure to link to this issue when you reach out.

**Comment by CassandraMarie** [comment]
Hi @bradleyjwatson, I have sent you an email.

**Comment by bradleyjwatson** [comment]
This email or another one?Best RegardsBrad WatsonSent from my iPhoneOn 21 May 2024, at 02:11, Cassandra Marie ***@***.***> wrote:﻿
Hi @bradleyjwatson, I have sent you an email.

**Comment by CassandraMarie** [comment]
You should have received an email from cassandra@watchla.app. I sent it on Friday, May 3rd. Please let me know if you received it.

**Comment by bradleyjwatson** [comment]
If you mean to try the trial version and test flight, yes I received that email… I didn’t realise you were waiting on a replyBest regardsBradley WatsonSent from my iPadOn 21 May 2024, at 9:05 AM, Cassandra Marie ***@***.***> wrote:﻿
You should have received an email from ***@***.*** I sent it on Friday, May 3rd. Please let me know if you received it.

**Comment by CassandraMarie** [comment]
If the problem persists or arises again, please feel free to reopen the issue or reach out for further assistance
