### ISSUE TITLE
Watchla App not working properly 

### ISSUE THREAD

**Issue by boardman7** [itsMeDavidV/Watchla-Support#358]
My Watchla app has version 3.7.4
I had this app for about two years but from the recent updates, my app is almost non usable. My battery charge percent always says 0% even though it’s charged to 80% and I receive a notification time to time I need to charge the battery soon.  Also there are some commands that do not work. 
This issue has been around for about a month now. And if it does not resolve I need to ask for the refund. 
My Apple Watch and iPhone have the latest updates. 
I’ve deleted the app from my phone and the watch and reinstalled it but no luck.

**Comment by mezzomix23** [comment]
Opened similar issue 2 weeks ago now, but yet to get an answer or see an update addressing it ☹️

**Comment by CassandraMarie** [comment]
Hi @boardman7, 

We are sorry to hear you have been experiencing difficulties with Watchla. Could you please send your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by CassandraMarie** [comment]
Hi @mezzomix23, we have received your support code! We will investigate your issue and follow up with you soon.

**Comment by CassandraMarie** [comment]
As we haven't received a response from the original creator, we will be closing this issue. If the problem persists or arises again, please feel free to reopen the issue or reach out for further assistance.
