### ISSUE TITLE
Blue icon not working When active

### ISSUE THREAD

**Issue by JappieKa** [itsMeDavidV/Watchla-Support#359]
Hi,

Don't know if it's a bug. But why don't the icons turn blue when you:

- Vent windows (open)
- open trunk (if open)
- open frunk (if open)
- maybe more...

Climate, lock, charge, charge port and again maybe more are visible if these are active. I think the above should at least be visible, right?

**Comment by CassandraMarie** [comment]
Hi @JappieKa,

Regarding the active icon states, when a button is engaged in the main screen of Watchla's watch app, it should undergo a color change. 

If you are witnessing this behavior could you please send us a video of the behavior occurring so we can better assess what might be going wrong?

**Comment by JappieKa** [comment]
Hi,

It is not clear to me why I also have to make a video of the issues raised earlier. I can't make a video of every issue/bug listed, can I? I think it is very simple, and you confirm that, if something is active, the function should turn blue. And that doesn't happen. Don't get me wrong, I'm not your software tester. You can do this very well too, I hope even better than me.

I also notice this very regularly, for example when my car is locked. And I look at Watchla and the lock icon shows as unlocked. And the car is really locked. It seems that the data from the Tesla API via Watchla needs a performance upgrade. Because with the Tessie app I don't have any of those things.

When do you expect to fix these "bugs"?

**Comment by CassandraMarie** [comment]
We're requesting a video of the behavior because it's not reproducible on our end. It's crucial for us to understand precisely what's happening on your end to prevent others from encountering the same bug. If you're unable to provide a video, we kindly ask for your support code to check any relevant error logs related to this issue.

**Comment by JappieKa** [comment]
My support code is [redacted]

Do you have a video of how it works then? So I could check.
