### ISSUE TITLE
App in watch is not signing in

### ISSUE THREAD

**Issue by sarselvaraj** [itsMeDavidV/Watchla-Support#36]

**Comment by itsMeDavidV** [comment]
Hi @sarselvaraj sorry to hear you're having sign in issues. 

To clarify, are you saying that you're signed in on the iOS app, but not the watch app? If this is the case just open the iOS app, goto preferences and then tap "Refresh watch app". This should force update the watch app to receive your sign in status. If there is no sign in update after a few seconds, be sure to close out the watch app and re-open.

If that does not work, ensure that your Apple Watch and iOS device are properly paired and that you have updated your iOS app and Watch app to be version 2.0 or above. Then sign out of the iOS app, close both the iOS & watch apps, and then try signing in again. 

Hope this helps! Please update me on the outcome.

**Comment by itsMeDavidV** [comment]
Going to assume this issue was remedied due to no response and am closing. If the issue persists, please feel free to re-open.
