### ISSUE TITLE
Complication not synchronized on watch

### ISSUE THREAD

**Issue by Pjbillus** [itsMeDavidV/Watchla-Support#361]
Impossible to synchronize the car batterie level on the watch. It keeps previous level
[redacted]
Thanks
Pj

**Comment by CassandraMarie** [comment]
Hi @Pjbillus, are you referring to your watch face complications or battery level inside the watch app?

**Comment by Pjbillus** [comment]
Hi, I am referring to the watch complication that’s not being updated. On the iPhone app it is correct. On the watch it is not and stuck to old battery level. I have to change the complication setting on the watch (via the phone) to get the updated status. Then it will get stuck to that % level at that time.

**Comment by CassandraMarie** [comment]
@Pjbillus, I have a few troubleshooting options for you, however, we are currently facing strict limitations by Apple Watch's battery management system on when and how frequently complications can be updated by apps like Watchla. 

We are in the process of developing a solution to improve and enhance the reliability of complications updates. 

In the meantime, follow the steps below:

1: Check to see what version BOTH your iOS and watch app you are currently using. You can check both your iOS and watch OS by navigating to preferences and scrolling down to the bottom of the screen **on each device.** 

If you are on an older version please update the apps and follow the steps below. 

2: Sign out of your iOS app and re-sign in
3: Re-authenticate your watch OS. You can re-authenticate from your iOS app by going to **preferences > authenticate watch app.**

4: Refresh your watch app. You can do this within the app via **preferences > refresh watch app**

Please let me know if this helps. If not we will check the logs and follow up with you.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
