### ISSUE TITLE
Battery charge complication stuck

### ISSUE THREAD

**Issue by kempfsc** [itsMeDavidV/Watchla-Support#364]
The battery charge complication on my watch face is stuck at 76% regardless of the actual charge of my Model X battery. If I touch the complication the watch shows the various controls with the correct battery charge, but when I return to the watch face the charge continues to be shown as 76%.

**Comment by CassandraMarie** [comment]
Hi @kempfsc, sorry to hear this. Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to Preferences > Support/ Feedback > Support code

Please be sure to link to this issue when you reach out.

**Comment by kempfsc** [comment]
Support code is [redacted].  Thank you

**Comment by CassandraMarie** [comment]
Hi @kempfsc, complications on watchOS face strict limitations by the Apple Watch’s battery management system on when and how frequently they can be updated by apps like Watchla.

This causes Watchla to have to be very strict and methodical on when and how it updates complications. 

Recently Watchla underwent some significant changes to authentication management that has hindered its current protocol for updating complications. We are currently in the process of adapting Watchla to these changes so that it can better and more reliably update complications without reaching the Apple Watch’s strict limitations on complications.
 Be sure to stay tuned with updates.

**Comment by kempfsc** [comment]
Hi Cassandra,

Am I correct in assuming that what you said in your last email means that the problems I am experiencing with the complications on my Apple watch are in the process of being corrected and will be taken care of at some point in the future?

Initially my problem was that the complication that shows the % charge of my Tesla Model X wasn’t updating. As a result my watch kept showing the same state of charge in the complication, regardless of what the actual charge in the battery was.

Now things have changed. The complication on the watch face now shows no state of charge; however, if I touch the complication the watch will show the correct state of charge and the various controls for opening the frunk, trunk, etc.

Support code – [redacted]

Backup code - [redacted]
Thank you,

Steve



From: Cassandra Marie ***@***.***>
Date: Monday, May 13, 2024 at 1:13 PM
To: itsMeDavidV/Watchla-Support ***@***.***>
Cc: Stephen Kempf ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [itsMeDavidV/Watchla-Support] Battery charge complication stuck (Issue #364)
CAUTION: Email Originated Outside of Auburn.

Hi @kempfsc<https://github.com/kempfsc>, complications on watchOS face strict limitations by the Apple Watch’s battery management system on when and how frequently they can be updated by apps like Watchla.

This causes Watchla to have to be very strict and methodical on when and how it updates complications.

Recently Watchla underwent some significant changes to authentication management that has hindered its current protocol for updating complications. We are currently in the process of adapting Watchla to these changes so that it can better and more reliably update complications without reaching the Apple Watch’s strict limitations on complications.
 Be sure to stay tuned with updates.

**Comment by kempfsc** [comment]
Hi Cassandra,

I don’t know if you did something at your end, but this morning Watchla is working on my Apple watch as it should.

Thank you,

Steve

From: Cassandra Marie ***@***.***>
Date: Monday, May 13, 2024 at 1:13 PM
To: itsMeDavidV/Watchla-Support ***@***.***>
Cc: Stephen Kempf ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [itsMeDavidV/Watchla-Support] Battery charge complication stuck (Issue #364)
CAUTION: Email Originated Outside of Auburn.

Hi @kempfsc<https://github.com/kempfsc>, complications on watchOS face strict limitations by the Apple Watch’s battery management system on when and how frequently they can be updated by apps like Watchla.

This causes Watchla to have to be very strict and methodical on when and how it updates complications.

Recently Watchla underwent some significant changes to authentication management that has hindered its current protocol for updating complications. We are currently in the process of adapting Watchla to these changes so that it can better and more reliably update complications without reaching the Apple Watch’s strict limitations on complications.
 Be sure to stay tuned with updates.

**Comment by CassandraMarie** [comment]
Great news!! I am going to close this issue. Should the problem persist or reoccur, please don't hesitate to reopen it.
