### ISSUE TITLE
Watch watchla complication - nothing displayed for charge

### ISSUE THREAD

**Issue by pescokid1** [itsMeDavidV/Watchla-Support#368]
Hi. I have an Apple Watch Ultra (v1) running WatchOS 10.5. My watch watchla app is 3.8 (438). My problem is lately there is nothing being displayed for the charge (see pic). It may have started when I upgraded to WatchOS 10.5. I tried killing the app, replacing/placing the complication and rebooting the watch. Same problem. Weird thing is when I edit the watch face, the charge shows up in the edit screen, but goes blank again after 
leaving edit. The charge is also displayed when I launch the watchla app. Any ideas?

![IMG_7627](https://github.com/itsMeDavidV/Watchla-Support/assets/51890846/47fcdd80-e0e1-4ef9-8540-a2b125bc8bb8)
![IMG_7629](https://github.com/itsMeDavidV/Watchla-Support/assets/51890846/b0d5e4fb-3bc0-4f90-957f-41cc568c8c66)

**Comment by d34vbd5** [comment]
Same combination (Watch Ultra v1) same issue for me since weeks if not month. I have already removed Watchla multiple times

**Comment by CassandraMarie** [comment]
Hi @pescokid1 & @d34vbd5, we are sorry to hear this. It is possible that you may be using an outdated version of the **watch OS.** The latest version is 3.8. You can check the watch OS by navigating to preferences and scrolling down to the bottom of the screen. It should say 3.8

If you are on an older version please follow the steps below. 

Step 1: Re-authenticate your watch OS. You can re-authenticate from your iOS app by going to preferences > authenticate watch app. 

Step 2: Refresh your watch app. You can do this within your iOS app via preferences > refresh watch app.

Let me know if this helps!

**Comment by pescokid1** [comment]
Hi. Thanks for responding. As I stated in my initial post, my watchla app is at 3.8 (438). However, I did try your suggestions, and, no changes, the problem is still there.

**Comment by CassandraMarie** [comment]
Have you tried signing out and re-signing in? 

If so, Can you send over your support code via https://watchla.app/contact so we can investigate your case?

Support codes can be found by going to **Preferences > Support/ Feedback > Support code**

**Please be sure to link to this issue when you reach out.**

**Comment by pescokid1** [comment]
Yes, I tried signing out and in, and just did it again, and the problem is still there. I will submit it.

**Comment by CassandraMarie** [comment]
@pescokid1, We have received your support code. We will look into the issue and follow up with you shortly.

**Comment by CassandraMarie** [comment]
@pescokid1, after looking into the error logs it seems you're facing a known complication issue. We're actively working on a solution, stay tuned.

**Comment by pescokid1** [comment]
Hi. My watch load Watchla version 3.8.1 (446), and the complication charge number is back. Thanks!

**Comment by pescokid1** [comment]
Hi. My watch loaded Watchla version 3.8.1 (446) overnight,  and the complication charge number is back. Thanks!TerryOn May 20, 2024, at 12:17 PM, Cassandra Marie ***@***.***> wrote:﻿
@pescokid1, after looking into the error logs it seems you're facing a known complication issue. We're actively working on a solution, stay tuned.

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.

**Comment by pescokid1** [comment]
Hi. For some inexplicable reason, the charge is again missing in the complication. The Watch OS version (10.5) has not changed, and the version of the Watchla app has not changed (3.8.1). Very strange…Terry Pescosolido On May 28, 2024, at 7:36 PM, Cassandra Marie ***@***.***> wrote:﻿
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
