### ISSUE TITLE
Won’t let me sign in. Says my credentials are wrong

### ISSUE THREAD

**Issue by davidwu503** [itsMeDavidV/Watchla-Support#370]

**Comment by CassandraMarie** [comment]
Hi @davidwu503, are you encountering an error from Tesla or Watchla? If you are experiencing an error with Watchla, could you please provide the error code?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
