### ISSUE TITLE
ICON missing on iwatch pro

### ISSUE THREAD

**Issue by vandermolen** [itsMeDavidV/Watchla-Support#371]
The lock unlock icon does not show up on the iwatch, please fix it - thanks!
![incoming-EEF597E6-D93C-4DCD-9D2E-AE92AD4E93FC](https://github.com/itsMeDavidV/Watchla-Support/assets/170193986/1f664599-c711-4a86-9885-1e8a757ad1a3)

the icon is missing from the lower left hand corner

**Comment by vandermolen** [comment]
sorry, lower right hand corner!

**Comment by CassandraMarie** [comment]
Hi @vandermolen, we are sorry to hear you have been experiencing difficulties with Watchla. What version of Watchla are you currently using? 

You can check which version you are currently using on BOTH DEVICES by navigating to preferences and scrolling down to the bottom of the screen (on each device). The latest version is 3.8.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
