### ISSUE TITLE
Watch not connecting 

### ISSUE THREAD

**Issue by randycpmoore** [itsMeDavidV/Watchla-Support#372]
Not able to connect Watchla to Tesla to be used as a key.

**Comment by CassandraMarie** [comment]
Hi @randycpmoore, are you on the latest update of Watchla, v 3.8? Also, have you set up a Watch Key/Bluetooth on your watchOS?

**Comment by randycpmoore** [comment]
Thank you for responding. I have the latest version of the app. However in attempting to connect the watch to the car via the Watchla app it was unsuccessful. It just showed installing but nothing happened after  about half hour.  How do I go about setting up watch key / Bluetooth ? I believe I was attempting that via instructions given in Watchla app. On May 22, 2024, at 16:37, Cassandra Marie ***@***.***> wrote:﻿
Hi @randycpmoore, are you on the latest update of Watchla, v 3.8? Also, have you set up a Watch Key/Bluetooth on your watchOS?

**Comment by CassandraMarie** [comment]
On your watch navigate to Watchla, scroll down, and press "Manage Watch Key". Have your Tesla keycard ready, get in your vehicle, and press "Setup Watch Key".

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
