### ISSUE TITLE
Cannot sign in on watch 

### ISSUE THREAD

**Issue by dkesla** [itsMeDavidV/Watchla-Support#373]
Just installed onto new Apple watch, phone app ok, cannot sign into watch app (version 3.8.1) 

iCloud sync is switched on for watchla. 

![IMG_2797](https://github.com/itsMeDavidV/Watchla-Support/assets/170606049/2b906e74-0dd9-4ec2-b93d-c21f66f8b2fb)

**Comment by Tigertanz3** [comment]
I have the same problem

**Comment by dkesla** [comment]
It’s working now.  I just tapped the above watch screen a few times whilst sitting in the car and re-connecting the watchla iOS app as a key.

**Comment by CassandraMarie** [comment]
@dkesla Glad to hear that!

**Comment by CassandraMarie** [comment]
Hi @ Tigertanz3, can you try signing out and signing back in?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
