### ISSUE TITLE
Watchla constantly ask to authenticate 

### ISSUE THREAD

**Issue by Patrick063** [itsMeDavidV/Watchla-Support#374]
I use Watchla. After a few days my watch as for authentication. It does not matter how many time I do it, it asks again and again

my support code is : [redacted]

I look forward to your instruction how to fix it. 

Cheers 

patrick063

**Comment by CassandraMarie** [comment]
Hi @Patrick063, could you tell me which version of Watchla you are currently using? The latest version is 3.8. You can check both devices by navigating to preferences and scrolling down to the bottom of the screen.

**Comment by Patrick063** [comment]
Hello Marie,On my iPhone 14, iOS 17.4.1,  the Watchla version is 3.8.1 (448)On my Apple Watch, watchOS 10.5, the Watchla version is 3.8.1 (446)Cheers, Patrick Bravard +61 419 330 497On 29 May 2024, at 07:19, Cassandra Marie ***@***.***> wrote:﻿
Hi @Patrick063, could you tell me which version of Watchla you are currently using? The latest version is 3.8. You can check both devices by navigating to preferences and scrolling down to the bottom of the screen.

**Comment by CassandraMarie** [comment]
Great, can you try signing out of Watchla completely and then signing back in?

**Comment by Patrick063** [comment]
Hello Marie,I have tried that and it still failed. But I’ll give it another go and let you know.Cheers,Patrick Bravard +61 419 330 497On 29 May 2024, at 09:35, Cassandra Marie ***@***.***> wrote:﻿
Great, can you try signing out of Watchla completely and then signing back in?

**Comment by Patrick063** [comment]
Hi Marie,I have logged out and logged back in.On my watch, the complication in the bottom left corner is supposed to show me the internal temperature of the car… When I’m setting the complication, it shows 72ºF. I cannot change it to ºCWhen I return to normal mode on the watch the complication only shows —- . When I touch that area,  the Watchla opens properly and syncs. So it is an improvement, but I would like to get the complication to show me the ºC. Maybe you can help me…Thank you for your patience.Cheers,Patrick Bravard +61 419 330 497On 29 May 2024, at 09:35, Cassandra Marie ***@***.***> wrote:﻿
Great, can you try signing out of Watchla completely and then signing back in?

**Comment by CassandraMarie** [comment]
Hi @Patrick063, you will need to adjust this directly in your vehicle. The temperature setting in your vehicle is reflected in the app.

**Comment by Patrick063** [comment]
Hello David,Yes, I managed to restore the complication is Cº by changing it first to kms and charge level, then returning it to temperature. Now all is well with the Watchla !Thank you for your support.Cheers,Patrick Bravard +61 419 330 497On 4 Jun 2024, at 03:26, Cassandra Marie ***@***.***> wrote:﻿
Hi @Patrick063, you will need to adjust this directly in your vehicle. The temperature setting in your vehicle is reflected in the app.

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
