### ISSUE TITLE
New watch: issue with Siri shorcuts

### ISSUE THREAD

**Issue by mezzomix23** [itsMeDavidV/Watchla-Support#376]
Just got a new Apple Watch and everything works except Siri Shortcuts.

The app is installed on the watch.

The shortcuts are there.

And I can run them manually, they work.

However, when using Siri and ask to run the shortcuts, I get that error message:
"You'll need to download an app for your car, or add a car key to the Wallet app."

Any idea what I'm missing?

Thank you 😊

**Comment by CassandraMarie** [comment]
Hi @mezzomix23, On each shortcut (in the Shortcuts app) select the 3 dots button, select the setting button (see image below), and select "Show on Apple Watch". Additionally, to speed up the time it takes to transfer the Siri Shortcut to your Apple Watch, force close and restart the “Shortcuts” app on your Apple Watch.
You can force close the “Shortcuts” app by tapping the long button on your Apple Watch and then sliding left on the “Shortcuts” app. When you re-open the “Shortcuts” app you should see your new shortcut populated on the screen. You’re all set from there and can start using that shortcut in Siri on your Apple Watch.
![IMG_7105](https://github.com/itsMeDavidV/Watchla-Support/assets/127701470/4128017f-1aba-4ad8-af99-e55c64dcf237)

**Comment by mezzomix23** [comment]
Hi @CassandraMarie. This has already been done. I have the shortcuts on the watch. I can open the shortcuts app on the watch and run it from there and it works fine. It's only when I use Siri to invoke the shortcut that it gets me the error:
![incoming-932DB70D-0361-4819-A9FD-0A407BBD992B](https://github.com/itsMeDavidV/Watchla-Support/assets/16504992/d94a2dbe-6555-4442-957e-8125f49785ea)

You can see the shortcuts are visible on the watch too:
![Uploading incoming-B020E62B-DD5D-4CB2-9E2C-EF6749E1C117.png…]()

Any other idea?

**Comment by CassandraMarie** [comment]
Siri may not be picking up the voice phrase, try changing the words.

**Comment by mezzomix23** [comment]
I can try, but according to my screenshot, Siri understood the command and it's the same than the shortcut.

**Comment by mezzomix23** [comment]
Tried to change from "Open the trunk" to "Open the boot" while Siri understands the command, still asks for an app on the watch or a key in the wallet app.

Deleted the shortcuts and re-added them from the Watchla app, not better.

Un-installed the app from the watch and reinstalled it, still not better.

I'm still using the beta version. Can this impact anything?

**Comment by CassandraMarie** [comment]
We recommend restarting your watch and ensuring that both your iOS and watch app have the same command ( "Open the Trunk").

**Comment by mezzomix23** [comment]
Restated the watched and tried again, still the same message.

The names of the shortcuts are the same, since they sync between the phone and the watch.

Somehow, decided to try the command "Close the trunk" instead of "Open the trunk", since they do the same action eventually and this one worked!

Tried "Open the trunk" right after and this time it worked too.

I don't know what happened, but it looks like Siri can execute Watchla commands without complaining now.

I'll keep monitoring and either close this issue or report back if issue is back.
