### ISSUE TITLE
Watchla just doesn’t work 

### ISSUE THREAD

**Issue by jasonvagner** [itsMeDavidV/Watchla-Support#377]
App won’t select vehicle

App won’t do virtual key

App complications don’t work

I had all of this setup and working before. If app doesn’t work it shouldn’t be listed as production ready. 

This doesn’t feel like a proper support feedback channel either. 

Support code:
[redacted]

**Comment by CassandraMarie** [comment]
Hi @jasonvagner, we are sorry to hear you have been experiencing difficulties with Watchla. 

We have looked into your support code and you will need to authenticate your watch app from your iOS app. You can reauthenticate from your iOS app by going to preferences > authenticate watch app. Please keep your watch app open during the re-authentication process. 

If it doesn't automatically sign in, you will need to refresh your watch app. You can do this within your iOS app by going to Preferences > Refresh App.

I hope this helps. If the issue persists, please reach out directly via email at cassandra@watchla.app

**Comment by jasonvagner** [comment]
Re-authenticated both of those, and yet..
That did not resolved the watch face battery status issue. Still thinks vehicle isn't selected.

![IMG_9838](https://github.com/itsMeDavidV/Watchla-Support/assets/47865826/0b3442a1-2098-4159-b526-9a39052ed37f)
![IMG_9837](https://github.com/itsMeDavidV/Watchla-Support/assets/47865826/45f273a5-0f16-429c-9c48-0239b18e53b1)

**Comment by CassandraMarie** [comment]
Just to confirm, have you refreshed your watch app within the iOS app while ensuring your watch app is open?

**Comment by jasonvagner** [comment]
Yes, I also refreshed watch app. One suggestion: an acknowledgement from the iOS app or the Watch when this occurs would be helpful. As it is, you hit "refresh" and there's no acknowledgement or response confirming that it has happened.

In preferences it seems to see that the battery for the MY is at 80%, but the battery state complication -- which had worked before -- still shows per the screenshot.

I had also, before posting here, deleted the apps, re-installed the apps, and had tried to install the digital key (which had also worked before). Alas, this is where things stand ATM.

**Comment by CassandraMarie** [comment]
Hi @jasonvagner, after reviewing error logs associated with the support code you gave, I can confirm you are facing a known auth related issue in Watchla. Good news is that we are testing a working solution to this issue in beta with very promising results. 

If you would like to help validate the solution in beta and have this issue fixed for you sooner, please reach via [https://watchla.app/contact/](url) and we will have an invite to the beta sent over to you.

**Comment by jasonvagner** [comment]
Great news, and thanks for the update!

**Comment by CassandraMarie** [comment]
We are closing this issue as it is being addressed through email communication.
