### ISSUE TITLE
Feature request : use the iPhone app with the same commands

### ISSUE THREAD

**Issue by user858753257** [itsMeDavidV/Watchla-Support#38]
Hey , 

is it possible to enable the in app watch to work ? 😅

Thanks

**Comment by itsMeDavidV** [comment]
The iOS app is currently dedicated to a support role for the watch app. Think: easy sign in, settings/customizations management, Siri Shortcuts, etc. However you actually can perform a ton of Watchla commands on iOS through Siri Shortcuts ;)

For now though, Watchla will be focused on creating an amazing watch experience. Currently there is another huge watch-related flagship feature in the pipeline that is very close to beta.

Not ruling out adding more commands in the iOS app in the future though!
