### ISSUE TITLE
Siri command failure to execute: "too long to respond"

### ISSUE THREAD

**Issue by mezzomix23** [itsMeDavidV/Watchla-Support#382]
Hi there,

I've been having this issue a lot, both on my old and new watch. When I ask Siri, from thr watch, to open the trunk, it takes about 10-15 seoncds, then I get that error message:
![incoming-EBD76CD5-498E-4D44-942C-2B23B63D4E6F](https://github.com/itsMeDavidV/Watchla-Support/assets/16504992/91ecf51a-6b2e-446e-b1dd-5aed36a529cd)

If I open the app on the watch, and either try again or use the open trunk button in the app on the watch, it works.

I take a short drive, like 5 min, I get out of the car and ask to open the trunk with Siri, same error.

Is there a way to add a delay or something to ensure the app can connect to the car to execute the command? It used to work good when the old authentication method was in use.

The virtual key is set up and Bluetooth activated on the watch too, if that matters.

**Comment by CassandraMarie** [comment]
Hi @mezzomix23, we are sorry to hear this. Have you attempted restarting both your iPhone and your watch?

**Comment by mezzomix23** [comment]
Yes, restarted both many times, to see if it works better and other reasons too.

It's still doing it and a gamble as to if the command will execute when using the watch. It's very unreliable compared to when the old authentication and APIs were in use.

**Comment by CassandraMarie** [comment]
@mezzomix23, Can you send over your updated support code via https://watchla.app/contact so we can investigate your case?
Support codes can be found by going to Preferences > Support/Feedback > Support Code.

**Comment by mezzomix23** [comment]
> @mezzomix23, Can you send over your updated support code via [https://watchla.app/contact so](https://watchla.app/contact%C2%A0so) we can investigate your case? Support codes can be found by going to Preferences > Support/Feedback > Support Code.

I'm gonna close this one for now. Recently it's been working pretty good. Don't know what kind of logs you would be able to collect. If you still want my support code, let me know.
