### ISSUE TITLE
IOS Gadget for opening the trunk opens the frunk

### ISSUE THREAD

**Issue by yvedebuysscher** [itsMeDavidV/Watchla-Support#383]

**Comment by CassandraMarie** [comment]
Hi @yvedebuysscher, we are sorry to hear this. Could you please send over your support code via [https://watchla.app/contact/](url) so we can investigate your case?

**Comment by CassandraMarie** [comment]
As we haven't received a response for some time, we will be closing this issue. If the problem continues or arises again, please feel free to reopen the issue or reach out for more help.
