### ISSUE TITLE
Can’t get Watchla face to show on iwatch!

### ISSUE THREAD

**Issue by bmbrock** [itsMeDavidV/Watchla-Support#385]
Watch face complication will not show on iwatch… did previously

**Comment by CassandraMarie** [comment]
Hi @bmbrock we are sorry to hear this. Could you tell which complications aren't showing up for you? Additionally, please ensure that you have the latest version (3.8) of Watchla installed on both of your devices. You can verify your current version by navigating to Preferences and scrolling to the bottom of the screen on each device.

**Comment by CassandraMarie** [comment]
As we haven't received a response for some time, we will be closing this issue. If the problem persists or arises again, please feel free to reopen the issue or reach out for further assistance.
