### ISSUE TITLE
Authentifikation

### ISSUE THREAD

**Issue by physi123** [itsMeDavidV/Watchla-Support#389]
Das iPhone arbeitet perfekt. 
die Apple Watch meldet, dass die Authentifizierung erforderlich ist. Trotz mehrfacher Versuche kein Erfolg. 
was läuft schief?
[redacted]

**Comment by CassandraMarie** [comment]
Hi @physi123, I believe you are encountering a known authentication issue in Watchla. The good news is that we are testing a working solution in beta with very promising results.

If you would like to help validate this solution in beta and have the issue resolved sooner, please contact us via [https://watchla.app/contact/](https://github.com/itsMeDavidV/Watchla-Support/issues/url) and mention this thread.

**Comment by CassandraMarie** [comment]
Watch authenticate issues have been resolved with version 3.8.2. Please update your app.
