### ISSUE TITLE
Can set up Apple Watch to connect to the car

### ISSUE THREAD

**Issue by Teslaguy01** [itsMeDavidV/Watchla-Support#391]
Hello, I have downloaded the app on my phone. I  am now stuck at the point where I can not get the watch to be used as the key. Help

**Comment by CassandraMarie** [comment]
Hi @Teslaguy01, we are sorry to hear you have been experiencing difficulties using Watchla. 
Have you attempted to set up a Watch Key? You can set up your Watch Key by following the steps below:

Step 1: Have your vehicle keycard in hand and get into your vehicle.
Step 2: On your Apple Watch, open Watchla
Step 3: Scroll down, select "Setup Watch Key," and follow the prompts.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
