### ISSUE TITLE
Watch Key Does Not Work - Bluetooth Won’t Connect

### ISSUE THREAD

**Issue by OhRobbyG** [itsMeDavidV/Watchla-Support#392]
I’m using the 3.8.1 version of Watchla w an Apple Watch Series 6 cellular and a 2023 Model Y Long Range AWD. Phone is an iPhone 13mini running latest iOS. Remote watchle functions work, but only when I am outside with a cellular connection. The watch as key function (which I need in my underground garage) does not work. Watch is already set up as a key in Tesla locks menu. Bluetooth is on, but no matter what I do (restarts the watch etc) all I get is the message below. The watch also never appears in the cars list of available Bluetooth connections either. I already have BT enabled in iOS Watchla settings too.

![IMG_2598](https://github.com/user-attachments/assets/6b4ef263-0b9d-4b0a-95e0-8803c27d5463)

**Comment by CassandraMarie** [comment]
Hi @OhRobbyG, we are sorry you have been experiencing difficulties using Watchla. 

We recommend deleting your watch key and setting up a new one. Please follow the steps below:

Step 1: Delete your Watch Key. To delete the key: in your vehicle go to Controls > Locks > Keys then tap the trash can next to the key.

Step 2: Delete Bluetooth data in Watchla. To delete Bluetooth data: in watchOS go to Preferences > Manage Watch Key > Delete BLE data. 

Step 3: Set up a new Watch Key. Have your vehicle keycard ready and get into your vehicle. On your Apple Watch, open Watchla. Scroll down select Setup Watch Key and follow the prompts. 

Let me know if this helps!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
