### ISSUE TITLE
Error code 200 when attempting to start A/C on the watch

### ISSUE THREAD

**Issue by bvillasen** [itsMeDavidV/Watchla-Support#393]
I can log in and the car status shows correctly on the watch app but when I try to execute any command from the watch like starting the A/C or turning on a heated seat I get the unknown keyID error Status code:200

![IMG_5497](https://github.com/user-attachments/assets/d027a567-f1ac-4f60-aad7-a65af59b8c13)

**Comment by jclagreca** [comment]
I have the same problem when trying to open my frunk.

**Comment by CassandraMarie** [comment]
Hi @bvillasen & @jclagreca, we are sorry to hear you have been experiencing difficulties using Watchla. 
Do you have your Virtual Key set up?

**Comment by jclagreca** [comment]
Honestly, the app hasn't worked for me since the whole API change stuff.
I've been trying to be patient, but as of right now,  I have all kinds of
problems, with this being a few:

[image: IMG_7486.PNG]


[image: IMG_7484.PNG]



Joe LaGreca
Mobile:  (619) 318-3246

**Comment by CassandraMarie** [comment]
Hi @jclagreca, it appears that your attachment did not come through. Could you try sending it again?

Could you verify if you have set up your Watch Key & Virtual Key?

**Comment by bvillasen** [comment]
I missed the step of adding the virtual key, my bad.

After adding the virtual key the commands are working for me.

Thank you

**Comment by jclagreca** [comment]
I just added the virtual key and will test.

Joe

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I will close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
