### ISSUE TITLE
Cannot Unlock Tesla

### ISSUE THREAD

**Issue by kunalraiker** [itsMeDavidV/Watchla-Support#394]
What to do to get this app to work.
The car shows in the app but yet I cannot unlock the car.

**Comment by CassandraMarie** [comment]
Hi @kunalraiker, we are sorry to hear you are experiencing difficulties using Watchla. To better assist you, could you verify if both your iOS and watchOS are updated to Watchla 3.8? 

You can check both devices via Preferences and scrolling to the bottom.

**Comment by CassandraMarie** [comment]
If both of your devices are up to date, you will need to set up a virtual key and a watch key. I can walk you through the steps if needed.

**Comment by kunalraiker** [comment]
Hi,
The version is 3.8.1
Thanks,Kunal
    On Tuesday 6 August 2024 at 08:25:59 am AEST, Cassandra Marie ***@***.***> wrote:  
 
 


Hi @kunalraiker, we are sorry to hear you are experiencing difficulties using Watchla. To better assist you, could you verify if both your iOS and watchOS are updated to Watchla 3.8?

You can check both devices via Preferences and scrolling to the bottom.

**Comment by CassandraMarie** [comment]
@kunalraiker, okay great! Can you verify if you have set up a virtual key and watch key?

**Comment by kunalraiker** [comment]
I haven't, are there any instructions on what to do?
Thanks,Kunal
    On Tuesday 6 August 2024 at 09:57:29 am AEST, Cassandra Marie ***@***.***> wrote:  
 
 


@kunalraiker, okay great! Can you verify if you have set up a virtual key and watch key?

**Comment by CassandraMarie** [comment]
I can certainly help! 
 
Virtual Key Setup: 
Step 1: Force close your Tesla app.
Step 2: Open Watchla, go to Preferences > Setup Virtual Key
Step 3: Select Setup with Tesla 
Step 4: Allow third-party access 

** If you see "Unable to Share Vehicle", take your Tesla Keycard, go into your vehicle, select "Use Key Card" and follow the prompts. **

Watch Key Setup:
Step 1: Have your vehicle keycard ready and get into your vehicle.
Step 2: On your watch, open Watchla
Step 3: Scroll down select 'Setup Watch Key' and follow the prompts. 

*** If you own a newer Tesla, place the key card near the card reader located in the wireless phone charger on the center console ** 

Please let me know if you need any further assistance.

**Comment by kunalraiker** [comment]
Hi Cassandra.
I get the error attached.
Thanks,Kunal 



Sent from Yahoo Mail for iPhone


On Tuesday, August 6, 2024, 11:29 AM, Cassandra Marie ***@***.***> wrote:




I can certainly help!

Virtual Key Setup:
Step 1: Force close your Tesla app.
Step 2: Open Watchla, go to Preferences > Setup Virtual Key
Step 3: Select Setup with Tesla
Step 4: Allow third-party access

** If you see "Unable to Share Vehicle", take your Tesla Keycard, go into your vehicle, select "Use Key Card" and follow the prompts. **

Watch Key Setup:
Step 1: Have your vehicle keycard ready and get into your vehicle.
Step 2: On your watch, open Watchla
Step 3: Scroll down select 'Setup Watch Key' and follow the prompts.

*** If you own a newer Tesla, place the key card near the card reader located in the wireless phone charger on the center console **

Please let me know if you need any further assistance.

**Comment by CassandraMarie** [comment]
It appears that your attachment did not come through. Could you please try sending it again?

You can also send the attachment here [https://watchla.app/contact/](https://watchla.app/contact/).

**Comment by kunalraiker** [comment]
Try now?



Sent from Yahoo Mail for iPhone


On Tuesday, August 6, 2024, 11:51 AM, Cassandra Marie ***@***.***> wrote:




It appears that your attachment did not come through. Could you please try sending it again?

You can also send the attachment here https://watchla.app/contact/.

**Comment by CassandraMarie** [comment]
We're currently handling this issue via email. Should the issue persist or reoccur, please don't hesitate to reopen it.
