### ISSUE TITLE
Vented windows status not showing

### ISSUE THREAD

**Issue by jclagreca** [itsMeDavidV/Watchla-Support#395]
When the windows are vented, it does not update and show in the Apple Watch app icon for vented windows.  I can however tell that they are vented because if I push the vent window button, it asks me to confirm if I’d like to close them. But I would think the icon should show highlighted/selected while they are vented.

**Comment by jclagreca** [comment]
![incoming-7EA513A0-67C5-4CF8-B04F-D204D69DC6F8](https://github.com/user-attachments/assets/be2246cb-b0cd-4975-be12-f724935df1a8)
![incoming-9E3385E4-8AD4-482E-867C-74032775A35C](https://github.com/user-attachments/assets/e6b22059-1b6e-4e31-93c1-4370f5f1de56)

**Comment by CassandraMarie** [comment]
Hi @jclagreca, thank you for bringing this to our attention. we will work on fixing this issue.

**Comment by CassandraMarie** [comment]
The vented window state has been fixed with Version 3.8.2. Please update your app!
