### ISSUE TITLE
Battery state complication not uodating

### ISSUE THREAD

**Issue by jclagreca** [itsMeDavidV/Watchla-Support#396]
The complication doesn’t update to the most up to date information shown in the app. 

![incoming-4FB1588A-42EA-4722-B0DE-A5149C57DCB7](https://github.com/user-attachments/assets/56ac9145-fa82-4358-a24b-a51c69853150)
![incoming-189F17E3-BC35-4898-8555-EB36969C67D0](https://github.com/user-attachments/assets/d5da8c7f-2197-4941-84cb-34b6f467d862)

**Comment by jclagreca** [comment]
The bottom image is the accurate most up to date information shown. The top image shows the complication that shows out of date info.

**Comment by CassandraMarie** [comment]
Hi @jclagreca, could you please verify if both your iOS and watchOS are updated to Watchla 3.8.1? You can check both devices via Preferences and by scrolling to the bottom.

**Comment by jclagreca** [comment]
ios app is 3.8.2 (469) and watch app is the same.

**Comment by CassandraMarie** [comment]
Hi @jclagreca, we recommend signing out of Watchla on both devices and signing back in.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
