### ISSUE TITLE
Watchla app issue 

### ISSUE THREAD

**Issue by Paobron23** [itsMeDavidV/Watchla-Support#399]
My Watchla app is not downloading on Apple Watch, I've had it on there previously

**Comment by Paobron23** [comment]
![Uploading IMG_5463.jpeg…]()

**Comment by Paobron23** [comment]
![IMG_5463](https://github.com/user-attachments/assets/dd0a9f46-1cdf-4ee4-bf06-ea3db3aac506)
![IMG_5463](https://github.com/user-attachments/assets/f23762a2-05f1-4c93-915d-d0be415de5c1)

**Comment by Paobron23** [comment]
It's been spinning for half an hour and not downloading

**Comment by Paobron23** [comment]
![IMG_5464](https://github.com/user-attachments/assets/7e21aa14-74e8-400e-87d7-78e85ca9b8d3)
![IMG_5465](https://github.com/user-attachments/assets/220eba18-f764-47ef-8f7a-d49372b24a8e)

**Comment by Paobron23** [comment]
That's my software details for watch and phone

**Comment by Paobron23** [comment]
Can you help here

**Comment by CassandraMarie** [comment]
Hi @Paobron23, sorry you're experiencing difficulties installing Watchla on your device. The fastest and most reliable way to download and install an app is on your Apple Watch. 

Below are the steps on how to install the Watchla app on your watch. 

Step 1: Open the app store on your watch.
Step 2: Search for "Watchla" in the search bar
Step 3: Once you locate the app, tap on it to open its details.
Step 4: Select "Download" or "Install" to begin the installation process. 
Step 5: Follow any on-screen prompts to complete the installation. 

Once Watchla is installed on your watch, navigate back to Watchla on your iOS device. Open Preferences > Set Up Watch app and follow the prompts.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
