### ISSUE TITLE
Relevant Vehicle Status Icons?  (P, Wifi)

### ISSUE THREAD

**Issue by KurtSanders** [itsMeDavidV/Watchla-Support#4]
The symbol 'P' and other status icons are not documented on the Apple watch or [Watchla website](https://watchla.app/decoded/statuses.html) for 'Relevant Vehicle Status' in the watch face complication.  Please document or let me know what it denotes.  

Great app so far, very clean interface and easy to install using the QR codes.  I replaced the 'Stats' watch app for Watchla.  

Fyi, the 'loading' screen takes forever to complete initially on Apple Watch 6, but finally did after a watch power off/on restart.    It also spins forever when trying to obtain status from 'P' icon....

I would also like to help with testing & feedback and join the beta.

![IMG_9526](https://user-images.githubusercontent.com/12133562/114353043-92e7b800-9b3a-11eb-89d7-2d0e9f954962.jpg)
![IMG_9527](https://user-images.githubusercontent.com/12133562/114359349-d98ce080-9b41-11eb-95b6-6daf767b8f88.jpg)
![IMG_9528](https://user-images.githubusercontent.com/12133562/114359873-69cb2580-9b42-11eb-9611-d77f1febda17.jpg)

**Comment by itsMeDavidV** [comment]
@KurtSanders 

Hi Kurt! 

I'm really glad to hear that you're enjoying Watchla!

So P,R,N,D denote the current shift state of the vehicle and they respectively stand for:

Park
Reverse
Neutral 
Drive

If there are no other relevant modes to report, the 'Relevant Vehicle Status' complication will default to display the vehicle's shift state.

The no-wifi looking icon actually denotes that Watchla is having issues connecting to your vehicle.

And you make a good point! I will be adding no-connection & shift state icons to https://watchla.app/decoded/statuses.html tonight!

Also, I would be more than happy to welcome you the beta! I'm sure you would make a great addition to the beta program. Send your email to my email: david@villegasventures.co and I will have a beta invite sent to you asap!

Once I add the above to [Watchla's website](https://watchla.app/decoded/statuses.html) I will update this thread and close it out.

PS: I will be addressing the other issue #5 that you submitted here shortly

**Comment by itsMeDavidV** [comment]
@KurtSanders also, I will definitely look into the extended loading issue (after tapping the shift state) and get back to you if a bug is discovered.

**Comment by itsMeDavidV** [comment]
Hi Kurt @KurtSanders 

I have added Park, Reverse, Neutral, Drive, and no-connection to https://watchla.app/decoded/statuses.html as promised above. Thanks again for bringing this up.

I also want to note that I did see your App Store review and in your review you claimed that I did not respond to you here on the issues that you submitted on GitHub. Obviously I have made multiple responses to both of your GitHub issues (#5 & #4) and I even extended my email out to you for the beta all before your review was even published.

I have yet to hear back from you on both GitHub and email. So it is quite disappointing that you would make a claim like that, unless you were having issues accessing GitHub to see my numerous responses?

Let me know.

Closing this issue.

**Comment by KurtSanders** [comment]
Dear @itsMeDavidV, 

I did not see your responses to my issues on the support page of your GitHub site.  It was not being being assigned, projects, milestones, etc..and no notifications when I checked back   I am a regular developer on GitHub with Hubitat and Smartthings and familiar with using GitHub as a means for providing support.  I am guessing that GitHub's flaky notifications might be the culprit for our mis-communications?  I have turned on all GitHub notifications so hopefully I can get these updates. 

I have deleted and re-added the Watchla to my Apple Watch model 6.  I also signed out and re-authenticated the app using your companion iPhone Authla app which refreshed the API token.  It was able to connect to the car afterwards but I did get these screen shots before performing these steps above.  

#### I will update my feedback in App Store since I was not seeing any responses on GitHub as I mentioned above.  I submitted a 4 star update and will move to a 5 star once I get a few more days of testing.

Sorry for the confusion!

**Comment by KurtSanders** [comment]
Sounds great and again sorry for my "quick to judge" on the app.  Being a developer, I too, have not gotten back to all my users in their expected level of "free" support.  I appreciate your tireless effort to create a low cost all watch app, and handle all the errors that can happen with a totally watch app, internet, and Tesla API's being hammered by millions of vehicles...  

I will be constructive in my feedback on beta testing when you add me.
