### ISSUE TITLE
*URGENT* if on v2.1, please update to v2.2 (see issue for more details)

### ISSUE THREAD

**Issue by itsMeDavidV** [itsMeDavidV/Watchla-Support#40]
Edit: v2.2 has been released, if affected by this issue please update!

Original: Hi Watchla users, this morning a critical bug that can cause disruption between the iOS app and the watch app has been discovered. It can affect your ability to sign in and transfer settings to the watch app.

A fix has been made and included in an update for Watchla that has been submitted to Apple for expedited review.

Normally expedited reviews take 1-4 hours, but can take as long as 1-2 days. I will update this issue when it is approved by Apple. For now avoid updating to version 2.1.

**Comment by itsMeDavidV** [comment]
**Update:** beta users can now access version 2.2 which fixes this issue.

**Comment by itsMeDavidV** [comment]
**Update:** Version 2.2 which contains a fix for this issue has been released to the App Store. Please update if you are experiencing this issue.

**Comment by user858753257** [comment]
Working again . Thanks 👍
