### ISSUE TITLE
Auto lock doesn’t work

### ISSUE THREAD

**Issue by ilkerderya** [itsMeDavidV/Watchla-Support#400]
Hello,

Since I started using the watch app, Generally, if I have an apple watch on my wrist, the car does not automatically lock after I exit the vehicle. If there is no watch, it locks without any problem. Since this situation creates a serious security weakness, I kindly request your attention. 

BR

**Comment by CassandraMarie** [comment]
Hello @ilkerderya, We have a detailed explanation of this in our FAQ, which also provides steps on how to address it. You can find the information here: [Does Watchla offer Walk-Away Lock](https://watchla.app/faqs/)

If you have any further questions or need additional assistance, please don’t hesitate to reach out.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
