### ISSUE TITLE
Cannot select correct vehicle 

### ISSUE THREAD

**Issue by Mariusk3112** [itsMeDavidV/Watchla-Support#401]
Unfortunately I cannot select the correct car the app shows the old car given the fact that I have used the app with my old car as well

**Comment by tr-nukala** [comment]
I have this issue too

**Comment by CassandraMarie** [comment]
Hi @Mariusk3112 and @tarunreddy92, is your new vehicle appearing in the app but cannot be selected, or is it missing altogether? Additionally, could you please confirm if you are using the latest version of Watchla, 3.8.2?

**Comment by Mariusk3112** [comment]
I can see the car but cannot select it. Yes the newest version

**Comment by Mariusk3112** [comment]
@CassandraMarie yes I can see it but selection doesn’t work

**Comment by tarunreddy92** [comment]
I see the new vehicle but cannot switch. This attachment might help. Sent from my iPhoneOn Aug 20, 2024, at 1:20 PM, Mariusk3112 ***@***.***> wrote:﻿
@CassandraMarie yes I can see it but selection doesn’t work

**Comment by tr-nukala** [comment]
I see the new vehicle but cannot switch. This attachment might help. 

https://github.com/user-attachments/assets/a1a8d5d8-6072-4aa5-9b96-11ec4f6d75a1

**Comment by darghouze** [comment]
I also have the same issue. I used the app with a previously owned vehicle which I no longer have. I am trying to get it to work with my new vehicle. The app is showing my old vehicle in the main menu. When I try to change vehicles, it shows my new vehicle as the only option, however when I select and confirm that, it still shows my old vehicle on the home page.

I tried logging out, deleting and reinstalling the app, and removing the connection to my Tesla account through the Tesla website. I also tried on another phone. Same problem kept reoccurring. Interestingly the problem doesn't appear when installing the app on an iPad.

**Comment by teslaaa1111** [comment]
Same issue! I traded in my old 3 and got a new Y.
I tried deleting and reinstalling the app, removed the access and regranted, I still my old 3.

please help

**Comment by zllllo** [comment]
Exact same problem as described by the others above. My old model 3 shows on the home page, selecting a different vehicle only shows my new model 3, selecting it and confirming does nothing but loop back to the old vehicle on the home page. 

This bug needs to be prioritized up. It is making the paid watch app completely useless.

Are there any workarounds? Where is the old vehicle metadata being stored? Is Tesla sending this information to the app dynamically (the old and the new, an array of 2 with attributes for each vehicle .. like is the vehicle valid), and the app is smart enough to only show valid vehicles in the selection list, but the app is simply not able to select the new one because of a logic error, like you had one vehicle before, and the selection list only has one vehicle, so a null op seems to be the assumption .. even though they are entirely different VINs and the first one is no longer valid?

**Comment by CassandraMarie** [comment]
Hi! We have developed a solution to the issue you are experiencing and would like to invite you to join our beta program to test this solution. Please contact us via [https://watchla.app/contact/](https://watchla.app/contact/) and mention this thread. Thank you for your patience and support.

**Comment by teslaaa1111** [comment]
> this solution. Please contact us via

Beta test app downloaded but the problem still persists.

**Comment by Mariusk3112** [comment]
The same on my side it’s not working. New car cannot be selected and old car appears.Von meinem iPhone gesendetAm 31.08.2024 um 03:57 schrieb teslaaa1111 ***@***.***>:﻿

this solution. Please contact us via

Beta test app downloaded but the problem still persists.

**Comment by zllllo** [comment]
The Beta app version 3.8.3 (480) is working for me. Note that after I installed it over my previous version, it appeared to show my old vehicle on the home screen initially if I recollect. I clicked around, signed out and signed in, don't quite remember what all I clicked, but then it seemed to refresh and my new vehicle showed up on the home screen, and thereafter, it's been working on both the phone and the watch.

**Comment by tr-nukala** [comment]
Sign out and signing in again worked. On the beta version of the app. On Aug 31, 2024, at 11:03 PM, zllllo ***@***.***> wrote:﻿
The Beta app version 3.8.3 (480) is working for me. Note that after I installed it over my previous version, it appeared to show my old vehicle on the home screen initially if I recollect. I clicked around, signed out and signed in, don't quite remember what all I clicked, but then it seemed to refresh and my new vehicle showed up on the home screen, and thereafter, it's been working on both the phone and the watch.

**Comment by Mariusk3112** [comment]
Working thanks. But cannot download watchla app on watch, any tips?Von meinem iPhone gesendetAm 01.09.2024 um 07:58 schrieb Tarun Reddy Nukala ***@***.***>:﻿
Sign out and signing in again worked. On the beta version of the app. On Aug 31, 2024, at 11:03 PM, zllllo ***@***.***> wrote:﻿

The Beta app version 3.8.3 (480) is working for me. Note that after I installed it over my previous version, it appeared to show my old vehicle on the home screen initially if I recollect. I clicked around, signed out and signed in, don't quite remember what all I clicked, but then it seemed to refresh and my new vehicle showed up on the home screen, and thereafter, it's been working on both the phone and the watch.

**Comment by CassandraMarie** [comment]
@Mariusk3112, the fastest and most reliable way to download and install an app is on your Apple Watch. Open the app store on your watch and download Watchla. If you're still unable to download Watchla, please email us at [https://watchla.app/contact/](https://watchla.app/contact/).

**Comment by CassandraMarie** [comment]
@teslaaa1111, were you able to select your vehicle on the beta app?

**Comment by Mariusk3112** [comment]
It’s working thanks Von meinem iPhone gesendetAm 03.09.2024 um 18:23 schrieb Cassandra Marie ***@***.***>:﻿
@Mariusk3112, the fastest and most reliable way to download and install an app is on your Apple Watch. Open the app store on your watch and download Watchla. If you're still unable to download Watchla, please email us at https://watchla.app/contact/.

**Comment by teslaaa1111** [comment]
Ok, after downloading the beta app from the developer and resetting from Tesla app (Third App Access), my Watchla finally works!

**Comment by darghouze** [comment]
Same here, works now for me too. Thank you.

Daniel

On Sep 3, 2024, at 6:54 PM, teslaaa1111 ***@***.***> wrote:


Ok, after downloading the beta app from the developer and resetting from Tesla app (Third App Access), my Watchla finally works!

**Comment by CassandraMarie** [comment]
Version 3.8.3 has just been released, addressing the issue of vehicles no longer associated with your Tesla account continuing to appear. Please update for a smoother experience!

**Comment by CassandraMarie** [comment]
This issue has been fixed in version 3.8.3, if you are still experiencing this issue please update your app.
