### ISSUE TITLE
Error code 

### ISSUE THREAD

**Issue by Rille2005** [itsMeDavidV/Watchla-Support#403]
When I use my Apple Watch Ultra 2 and Watchla app and push „vent windows” the windows goes down but when I push „ close windows” I get a error code: 
Command failed Statuscode 200.
Why? Can you please fix this ? 
it’s a Tesla MS 2020 LR Raven edition .

**Comment by CassandraMarie** [comment]
Hi @Rille2005, could you send over your support code via [https://watchla.app/contact/](https://watchla.app/contact/) so we can investigate your case? Also, could you verify if both of your devices are updating to version 3.8.2? You can check both devices via Preferences and by scrolling to the bottom.

**Comment by CassandraMarie** [comment]
Hi @Rille2005, I’m following up to see if you’ve had a chance to send in your support code?

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
