### ISSUE TITLE
Problem with app

### ISSUE THREAD

**Issue by Cafe2Racer** [itsMeDavidV/Watchla-Support#404]
![IMG_2995](https://github.com/user-attachments/assets/d307c5ae-44a3-480a-a41e-7ca6862d7234)

Hello, i have this problem..

**Comment by CassandraMarie** [comment]
Hi @Cafe2Racer, Watchla requires access to certain scopes to ensure proper functionality when interacting with your vehicle. You can manage these permissions in your Tesla account by navigating to Account Settings > Security & Privacy > Security > Third-Party Apps > Manage Watchla. Watchla needs access to your profile information, vehicle info, vehicle commands, and vehicle charging management. 

Let me know if you need any further assistance.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
