### ISSUE TITLE
Siri command not working and wrong battery level display on watch screen

### ISSUE THREAD

**Issue by Mathieumasclez** [itsMeDavidV/Watchla-Support#405]
I cannot command the car via Siri Shortcuts. Battery level is showing the right information on watch except when opening it. When closing back, the battery level is still not updated on watch screen complication
[redacted]

**Comment by Mathieumasclez** [comment]
Hi, here is my support code [redacted] 
Any feedback?
Thanks

**Comment by CassandraMarie** [comment]
Hi @Mathieumasclez, thank you for reaching out. I can certainly walk you through the steps to set up Siri Shortcuts. You should already have the Shortcuts app downloaded on both of your devices, but you may need to redownload it to your Apple watch. 

Here's a step-by-step guide to setting up Siri Shortcuts on your iPhone and Apple Watch using the example "Unlock my Tesla": 

Step 1. Make sure the shortcuts app is installed on both your iPhone and Apple Watch. 
Step 2: Open Siri Shortcuts via Watchla and select "Unlock my Tesla" to be added to Siri ( You completed this step).
Step 3: Open the "Shortcuts" app on your iPhone. 
Step 4: Select the 3 dots on your "Unlock my Tesla" command 
Step 5: Click the information button at the bottom of the screen in the center ( 'I with a circle around it' symbol) 
Step 6: On the details page, select "Show on Apple Watch" 

After adding your commands, open the "shortcuts" app on your watch. Your new shortcuts should now be visible on the screen. From there, you're all set and can start using the "Close my trunk" shortcut with Siri on your Apple Watch. 

Additionally, if you do not see your commands right away force close the shortcuts app on your watch and restart the app on your Apple Watch. I have also attached our FAQs on [https://watchla.app/faqs/](https://watchla.app/faqs/).

**Comment by CassandraMarie** [comment]
Regarding Complications, could you verify if you are using the latest version of Watchla, 3.8.3? You can verify your current version by navigating to Preferences and scrolling to the bottom of the screen on **each device**.

**Comment by Mathieumasclez** [comment]
Hi, I confirm I am using the right version.BestMathieu Masclez Le 12 sept. 2024 à 21:01, Cassandra Marie ***@***.***> a écrit :﻿
Regarding Complications, could you verify if you are using the latest version of Watchla, 3.8.3? You can verify your current version by navigating to Preferences and scrolling to the bottom of the screen on each device.

**Comment by Mathieumasclez** [comment]
Hi, I processed all your recommandations,
Both devices are using the same version 383 but now the complication displays “vehicule data error” . Last connexion was on sept 9 so 4 days ago
Best

**Comment by Mathieumasclez** [comment]
Hi, after following your recommandations, I now have vehicule data error on the complication and when opening the app on the watch, no status battery is displayed. Watch and phone are both using the latest version of Watchla 383 (485).BestMathieu Masclez Le 12 sept. 2024 à 23:10, Mathieu Masclez ***@***.***> a écrit :﻿Hi, I confirm I am using the right version.BestMathieu Masclez Le 12 sept. 2024 à 21:01, Cassandra Marie ***@***.***> a écrit :﻿
Regarding Complications, could you verify if you are using the latest version of Watchla, 3.8.3? You can verify your current version by navigating to Preferences and scrolling to the bottom of the screen on each device.

**Comment by CassandraMarie** [comment]
Hi @Mathieumasclez, based on the support code you provided, you will need to sign out and sign back into Watchla. Please reach back out if the issue persists.

**Comment by Mathieumasclez** [comment]
Hi, thank you. I signed out and I have now in the app the right information. Nevertheless on the complication, it is still not showing the charge level.What else to do?ThanksMathieu Masclez Le 17 sept. 2024 à 01:41, Cassandra Marie ***@***.***> a écrit :﻿
Hi @Mathieumasclez, based on the support code you provided, you will need to sign out and sign back into Watchla. Please reach back out if the issue persists.

**Comment by Mathieumasclez** [comment]
Hi, it is all ok now with the new Apple update (IOS18 and watch 11).

 

Many thanks for your support

 

De : Cassandra Marie ***@***.***> 
Envoyé : mardi 17 septembre 2024 01:42
À : itsMeDavidV/Watchla-Support ***@***.***>
Cc : Mathieumasclez ***@***.***>; Mention ***@***.***>
Objet : Re: [itsMeDavidV/Watchla-Support] Siri command not working and wrong battery level display on watch screen (Issue #405)

 

Hi @Mathieumasclez <https://github.com/Mathieumasclez> , based on the support code you provided, you will need to sign out and sign back into Watchla. Please reach back out if the issue persists.

**Comment by CassandraMarie** [comment]
Great to hear! Should the issue persist or reoccur, please don't hesitate to reopen it.

**Comment by Mathieumasclez** [comment]
Thanks. I had a big later but it seems okBestMathieu Masclez Le 17 sept. 2024 à 19:05, Cassandra Marie ***@***.***> a écrit :﻿
Great to hear! Should the issue persist or reoccur, please don't hesitate to reopen it.
