### ISSUE TITLE
My Watch aplicativos does’n work. Gives me 401 code

### ISSUE THREAD

**Issue by cmagasan** [itsMeDavidV/Watchla-Support#417]

**Comment by CassandraMarie** [comment]
Hi @cmagasan, We apologize for the inconvenience. Watchla is currently experiencing an intermittent outage, which may be causing 401 to appear. Our team is actively working to resolve the problem as quickly as possible.


Additionally, please verify you are using the latest version of Watchla, 3.8.4.  To verify, open the Watchla app on your iPhone, go to the 'Preferences' screen, and scroll down past the 'Sign Out' button until you see the 'app version' label.
The app version will be displayed in the following format: version (build number).

I will keep you updated once we develop a solution

**Comment by CassandraMarie** [comment]
Also, we recommend signing out and signing back in.

**Comment by CassandraMarie** [comment]
Also, we recommend signing out and signing back in.

**Comment by cmagasan** [comment]
Nothing hapens. App watch didn’t recognize my car.Carlos Magalhães SantosNo dia 04/10/2024, às 15:49, Cassandra Marie ***@***.***> escreveu:﻿
Also, we recommend signing out and signing back in.

**Comment by CassandraMarie** [comment]
If you are on the latest version of Watchla, we recommend signing out and signing back in. 

We are working on a solution and will update you as soon as we develop a solution.

**Comment by cmagasan** [comment]
It seems to be working well now with the watch app. Thank you for your attention.Maybe it was a Bluetooth issue.Carlos Magalhães SantosNo dia 04/10/2024, às 20:47, Cassandra Marie ***@***.***> escreveu:﻿
If you are on the latest version of Watchla, we recommend signing out and signing back in.
We are working on a solution and will update you as soon as we develop a solution.

**Comment by CassandraMarie** [comment]
Glad to hear that! Should the issue persist or reoccur, please don't hesitate to reopen it.
