### ISSUE TITLE
Watchla on watch 10 not working.

### ISSUE THREAD

**Issue by rorocui** [itsMeDavidV/Watchla-Support#422]
Hi

the app on iOS works fine, but no response on any functionalities of watch app, like lock/unlock, open trunk, etc.
I tried to remove apps on both iOS and watch, and reinstall, doesn’t help.
Please advise. Thanks

**Comment by CassandraMarie** [comment]
Hi Roro, thank you for sending in your support code via email. We will get back to you shortly. Thank you for your patience and support.
