### ISSUE TITLE
Door open does not work (complication)

### ISSUE THREAD

**Issue by claire078** [itsMeDavidV/Watchla-Support#426]
Left door open (I think others neither) does not work as complication on a Watch face. 
After tapping just open the Watchla app.

Question related to complications: 
Watchla will support “offline” commands like Tesla app does? Tesla app does not wakes vehicle, commands just work with bluetooth without first wake vehicle. It works insanely fast! 😊

**Comment by CassandraMarie** [comment]
Hi @claire078, have you set up a Watch Key? Also, we recently released an update, please update your devices to version 3.9.3.  

The Watchla app can connect to your vehicle over Bluetooth while it is in background. Keep in mind however, that Apple Watch apps like Watchla are heavily limited by watchOS in the amount of time (per day) that they have to communicate over Bluetooth while in background. This is to preserve your Apple Watch's battery life. You can read more about Bluetooth here in [FAQs ](https://watchla.app/faqs/).

**Comment by claire078** [comment]
I have set bluetooth key of course. 
And sure I’m using latest version of the app, 3.9.3. 
I have talked about new features of Tesla app: 
“Offline commands are faster and more reliable. When you press the button to open the frunk, it’ll now do this instantly, instead of waking up the vehicle first. ”

**Comment by CassandraMarie** [comment]
Yes, we are currently working on that now. These features will be released soon.

**Comment by CassandraMarie** [comment]
I have a solution for you. You will need to delete your Bluetooth data, force close the Watchla app, and set up a new Watch Key.

To delete Bluetooth data: In Watch OS go to preferences > manage Watch Key > Delete BLE data.

**Comment by claire078** [comment]
> I have a solution for you. You will need to delete your Bluetooth data, force close the Watchla app, and set up a new Watch Key.
> 
> To delete Bluetooth data: In Watch OS go to preferences > manage Watch Key > Delete BLE data.

There was a question before, yes, in Watchla app Open door works like other commands as well.

**Comment by claire078** [comment]
It just works in 3.9.4. 👌
After touching opens the All doors screen also a good idea. 👍 
Thanks!
