### ISSUE TITLE
Siri shortcuts

### ISSUE THREAD

**Issue by markpassin** [itsMeDavidV/Watchla-Support#429]
my siri Tesla shortcuts work on my iphone, but not my watch.  I get the messae that I have to download an app to my car or add a car key to the wallet app.  How do I fix it?  Thanks.

**Comment by CassandraMarie** [comment]
Hi @markpassin, sorry to hear about your troubles.

It looks like Siri isn't recognizing the shortcut you're trying to use. I just want to confirm that everything is set up correctly, do you see your shortcut on your Apple Watch's Shortcuts app and if so, does tapping the shortcut open the truck? If yes, that's good, that means that the Siri shortcut transferred to your watch successfully.

From there you will want to make sure you are using the exact phrase that is attributed to the shortcut (eg: "Open the trunk"). You can check which phrase is attributed to which shortcut, as well as edit the phrase in the Watchla iOS app by going to Preferences > Siri Shortcuts.

I hope this helps, please don't hesitate to reach out if you have any questions.

**Comment by markpassin** [comment]
Thanks it is working now. I may not have been saying the exact command.
Best regards.


Mark D. Passin

Information contained in this e-mail transmission may be privileged,
confidential and covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521. If you are not the intended recipient, do not
read, distribute, or reproduce this transmission. If you have received this
e-mail transmission in error, please notify us immediately of the error by
return email and please delete the message from your system.  Thank you in
advance for your cooperation.

**Comment by markpassin** [comment]
I was mistaken. It worked because I had my phone in my hand. Any other
ideas.

Mark D. Passin

Information contained in this e-mail transmission may be privileged,
confidential and covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521. If you are not the intended recipient, do not
read, distribute, or reproduce this transmission. If you have received this
e-mail transmission in error, please notify us immediately of the error by
return email and please delete the message from your system.  Thank you in
advance for your cooperation.

**Comment by markpassin** [comment]
Now it says taking too long to respond. Also, watch does not always open
up door when I approach it.

Mark D. Passin

Information contained in this e-mail transmission may be privileged,
confidential and covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521. If you are not the intended recipient, do not
read, distribute, or reproduce this transmission. If you have received this
e-mail transmission in error, please notify us immediately of the error by
return email and please delete the message from your system.  Thank you in
advance for your cooperation.

**Comment by markpassin** [comment]
Sorry for so many emails. Fixed the Siri. Was not using exact words in app
vs shortcuts.  Still have problem door does not automatically unlock.
Thanks.


Mark D. Passin

Information contained in this e-mail transmission may be privileged,
confidential and covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521. If you are not the intended recipient, do not
read, distribute, or reproduce this transmission. If you have received this
e-mail transmission in error, please notify us immediately of the error by
return email and please delete the message from your system.  Thank you in
advance for your cooperation.

**Comment by CassandraMarie** [comment]
Hi @markpassin, it's great to hear Siri shortcuts are working for you! 

Apple Watch apps like Watchla have certain limitations in how long they can communicate over Bluetooth in the background. This helps preserve battery life but sometimes means the app may not consistently unlock the vehicle passively when you approach.

Opening the Watchla app can help reestablish the connection if Bluetooth hasn’t engaged automatically. 

Hope this helps!

**Comment by markpassin** [comment]
Thanks for all your help and responsiveness.

Mark D. Passin

Information contained in this e-mail transmission may be privileged,
confidential and covered by the Electronic Communications Privacy Act, 18
U.S.C. Sections 2510-2521. If you are not the intended recipient, do not
read, distribute, or reproduce this transmission. If you have received this
e-mail transmission in error, please notify us immediately of the error by
return email and please delete the message from your system.  Thank you in
advance for your cooperation.

**Comment by CassandraMarie** [comment]
Of course, we are here to help! I’m going to close this issue for now, but please feel free to reopen it if the problem persists.
