### ISSUE TITLE
Remove virtual key prompts 

### ISSUE THREAD

**Issue by Noneedforaname33** [itsMeDavidV/Watchla-Support#430]
Don’t want to add virtual key but on the watch screen it keeps asking and has info about it if I scroll down. Its annoying, can you remove that?

**Comment by Noneedforaname33** [comment]
> Don’t want to add virtual key but on the watch screen it keeps asking and has info about it if I scroll down. Its annoying, can you remove that?

Never mind! My error!

**Comment by CassandraMarie** [comment]
I'm glad everything is working for you. Please don't hesitate to reach out if you have any questions.
