### ISSUE TITLE
No vehicles found 

### ISSUE THREAD

**Issue by normanmaurer** [itsMeDavidV/Watchla-Support#45]
When trying to use the token it always says no vehicles found

**Comment by itsMeDavidV** [comment]
@normanmaurer this may be due to brand new change in the authentication flow for the Tesla API. For more info see issue #46 

Rest assured I am working on a fix ASAP.

**Comment by itsMeDavidV** [comment]
Hi @normanmaurer recently a sign in bug was fixed in version 2.3 of Watchla. I recommend updating your Watchla app so this issue can be solved.
