### ISSUE TITLE
the app doesn’t open 

### ISSUE THREAD

**Issue by remonma** [itsMeDavidV/Watchla-Support#47]

**Comment by remonma** [comment]
i put the email, the password and the code but it didn’t opened the app

**Comment by itsMeDavidV** [comment]
Hi @remonma there has been a critical change made by Tesla in the last 24 hours that has led to sign in issues. 

Please see issue #46 for more info.

This issue should be fixed within 24 hours.

**Comment by itsMeDavidV** [comment]
Hi @remonma this bug has now been fixed. Please update Watchla to version 2.3 on the App Store!
