### ISSUE TITLE
Watch app 

### ISSUE THREAD

**Issue by abitsoylu** [itsMeDavidV/Watchla-Support#49]
I am having problem with watch app keep asking me to Authenticate my Tesla account

**Comment by abitsoylu** [comment]
Unable to install app to my watch. I restarted my iPhone and watch still no luck. https://user-images.githubusercontent.com/6740501/159901686-7b002606-18b0-464f-838b-07f2431ffdf4.MOV

**Comment by itsMeDavidV** [comment]
Hi @abitsoylu from your video it's seems you are most likely having pairing issues between your iOS device and Apple Watch.

Here's a helpful link on how to tell if you're experiencing pairing issues: https://support.apple.com/en-us/HT205025

If the issue persists, I'd recommend re-pairing your Apple watch.

**Comment by abitsoylu** [comment]
I fix it. I had download Watchla app from Apple Watch App Store seems like it’s working now. But past few days I had same problem where watch keep asking me to authenticate my Tesla from iOS app

**Comment by itsMeDavidV** [comment]
@abitsoylu That's good to hear, however if your Apple Watch is experiencing pairing issues, it will also disrupt communication between the Watchla watch and iOS app. For the best experience I'd recommend ensuring there are no pairing issues.

**Comment by abitsoylu** [comment]
Sounds good thank you
