### ISSUE TITLE
Can’t authenticate Watchla or Authla

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#50]
I get the error message shown in attached screenshot on both apps. 

![136E4EFF-77B1-4678-9C2D-8F8E8B2897FB](https://user-images.githubusercontent.com/9358980/160657593-a4c2769c-e826-4525-9f95-0122c7a576be.jpeg)

(It’s possible the Reference # differs between apps)

**Comment by ttwajsb** [comment]
Here's what happens when I try to get my token using Authla. 

https://user-images.githubusercontent.com/9358980/160659512-83f28ea8-7f1f-4669-ad29-c0950b43f1c5.MOV

Not clear if screencast uploaded. Here's the iCloud link:
https://share.icloud.com/photos/041WeTvzJkM-xqWw18LQMIcUg

**Comment by ttwajsb** [comment]
Discovered that the issue arose because I was running a VPN (Surfshark). It would be ideal if your interface alerted users that they must (or may need to) disconnect any running VPNs before attempting to get a token.

**Comment by itsMeDavidV** [comment]
Hi @ttwajsb so in my experience this 'Access Denied' page is actually relatively new and it normally targets one specific account for too many sign ins and/or failed sign in attempts within a short period of time. 

If you get this screen you will have to reset the connection (eg: switch to a different network or reset your current network connection). It's important to note that you should be able to use VPN and/or your original network after reseting your connection.

It's also important to note that if your VPN connects to a Chinese IP or on the contrary if you're a Tesla China user and your VPN connects outside of China, your chances of encountering a sign-in disruption similar to this might be higher as they use separate authentication servers all-together for China vs non-China accounts.

This might not apply to you personally, but in the situation above, Tesla China users are encouraged to toggle their selected region to China if outside of China. Similarly if you are **not** a Tesla China user connecting to a Chinese IP, remember to toggle to 'Global'. In Watchla, this can be done in the Support screen.

**Comment by ttwajsb** [comment]
A couple observations FWIW:
- The error occurred on my first attempt to connect, so in that instance it would not have been a case of too many attempts.
- Interesting that the only difference between not getting access and then getting access was simply to disconnect my VPN. I've encountered a similar issue when trying to use my Tesla app to see my car, and when attempting to log in to Bank of America, Amazon and a couple other apps.
- I tried switching between Global and China just to see what would happen but got the same results. My VPN was connecting via Los Angeles at the time. 
I say these not to be disputative by simply to contribute to awareness of interaction with the app.
Looking forward to trying out, and ultimately using, Watchla. Thanks, David.

**Comment by itsMeDavidV** [comment]
@ttwajsb Interesting. I would hope that platforms aren't blocking IPs associated with VPN use. Have you tried using another VPN (not Surfshark)?

Thanks for sharing btw, this is very useful info. I will have to include in-app messaging that tips off users to the fact that VPNs might hinder their sign in experience.

Also just curious, once signed in, did you try re-connecting to Surfshark's VPN? If so, did everything in Watchla work as intended?

**Comment by ttwajsb** [comment]
A few more observations:
- When I tried to open Watchla after turning on Surfshark it wanted me to log in again. So I went to Authla to get a token. 
- Curiously, on the Authla main page there's a prominent CopyToken button, so that's what I tried to use in Watchla. I took me several attempts to stumble across the fact that I had to go to Authla's SeeFullResponse in order to locate the two separate tokens needed for Watchla. Could you split the bottom button on Authla's main page into CopyAccessToken and CopyRefreshToken (maybe along with a sentence or two explaining them; there's plenty of space on the page)?
- After trying multiple times and getting an error code, I switched off the VPN and it sailed right on thru the process. Clearly, the key variable was whether VPN was connected. 
- Once that was the case, though, I immediately saw that all my CustomLayout settings had reverted to the default. 

I'll try the process again with a different VPN and let you know how that goes. In the meantime, pretty disappointing if I lose both my ability to use Watchla, and all my settings, every time I turn on my VPN. :/

**Comment by ttwajsb** [comment]
Okay, just reset everything and it's working as intended even after testing on two separate VPN's (Surfshark and my work VPN).
I noticed, though, in Authla it says “Expires in 7 hours” so I'll check back later to see if all's still well. 
How can I get a persistent, rather than quickly-expiring, token? Or is the token only needed briefly (ie, up to 7 hrs) when setting up the connection, and then the connection persists after that?

**Comment by ttwajsb** [comment]
BTW, when Watchla is running (fingers crossed the VPN issue doesn't end up throwing things off), I'm delighted to see that I can tap RemoteStart on my Watch instead of having to enter my PIN to drive. And I'll use my frunk a lot more now that I can so easily open it without reaching for my iPhone and navigating to then opening the Tesla app. Thankfully, due to Family Sharing I was able to help her get to the trunk, too. If VPN settles well I'll be glad to submit a glowing review on the App Store. Definitely appreciate seeing the version history, how consistently you're enhancing things.

**Comment by itsMeDavidV** [comment]
@ttwajsb

> How can I get a persistent, rather than quickly-expiring, token? Or is the token only needed briefly (ie, up to 7 hrs) when setting up the connection, and then the connection persists after that?

Recently, Tesla has deprecated the use of JWT tokens--which lasted about 45 days--for security reasons. Watchla/Authla held on as long as possible, but now both apps are forced to support only the new SSO tokens that last only 8 hours. Not to worry though, these are automatically refreshed for you in Watchla.

> * Curiously, on the Authla main page there's a prominent CopyToken button, so that's what I tried to use in Watchla. I took me several attempts to stumble across the fact that I had to go to Authla's SeeFullResponse in order to locate the two separate tokens needed for Watchla. Could you split the bottom button on Authla's main page into CopyAccessToken and CopyRefreshToken (maybe along with a sentence or two explaining them; there's plenty of space on the page)?

Yes. This was set up during the time that JWT access tokens were the only thing you needed to authenticate your Tesla account. Authla is currently undergoing updates to address this and add copy refresh functionality right on the main screen. 

> * Once that was the case, though, I immediately saw that all my CustomLayout settings had reverted to the default.

Custom Layout and other preferences are saved with the user and should reflect every time you use the app. However, if the user signs out, those preferences are reset to allow for the next signed in user to start with essentially a blank slate (preferences-wise). For security, Watchla does not attribute preferences to previously signed in users or keep any old data from previously signed in users in any way, shape or form. Once you sign out all data is erased--including preferences.

> Okay, just reset everything and it's working as intended even after testing on two separate VPN's (Surfshark and my work VPN)

Sweet! Very glad to hear that. VPNs are big and I'd hate to see Tesla block their use. Calls to the Tesla API are direct (there are no intermediaries) so if a VPN doesn't work, it's most likely because Tesla is blocking it :(

> BTW, when Watchla is running (fingers crossed the VPN issue doesn't end up throwing things off), I'm delighted to see that I can tap RemoteStart on my Watch instead of having to enter my PIN to drive. And I'll use my frunk a lot more now that I can so easily open it without reaching for my iPhone and navigating to then opening the Tesla app. Thankfully, due to Family Sharing I was able to help her get to the trunk, too. If VPN settles well I'll be glad to submit a glowing review on the App Store. Definitely appreciate seeing the version history, how consistently you're enhancing things.

Thank you! I'm constantly updating Watchla, hoping to make it as good as I can with the time and resources I have. I hope you and the family enjoy it! Also thank you for your feedback, it's very helpful. A lot of the time when you create something, there is a limited scope of the possible scenarios you can think of to address. Feedback really helps supplement that as well as highlight things that can be improved. Things can always be better ;)

It's funny, I to find myself using the Frunk way more bc of Watchla. When I'm in a hurry, the frunk just doesn't seem worth it if I have to dig in my pocket for my phone just to open it.

Anyways, I'm really glad to hear you can use VPN now, please let me know if that changes.  Enjoy Watchla!!

**Comment by ttwajsb** [comment]
Appreciate your thorough and thoughtful responses to the several issues. 

Adding one that's so unimportant I didn't want to open a new thread for it, but I wonder if you would consider refining the lightning image inside the complication. All others on my Infograph face are crisp, but that portion of the Watchla icon looks fuzzy and pixelated. 
![image](https://user-images.githubusercontent.com/9358980/161305511-335e2800-0ddf-4a10-b616-3621598e1133.png)

Also, I'm eager to post a five-star review on the App Store but have decided to wait until I've had extended real-life experience with it on a cross-country 22-day drive I'm taking, Santa Barbara to Philly and back departing 4/14. Just wanted you to know why I didn't quickly follow up on my expressed intent to submit a review for you.

**Comment by ttwajsb** [comment]
Just had a difficult time using Remote Start. Was able to “see” the car via the phone app (unlocked doors from Watchla iOS app) but Watchla on Watch asked three times for my password. Then when it finally said Remote Start was enabled on the Watch, I still needed to enter my PIN. 

Could we start a generic Closed thread where I could report stuff like this, or would you prefer I open new cases for everything that comes up?

**Comment by itsMeDavidV** [comment]
@ttwajsb In this case where an issue occurs feel free to start a new issue. That really helps organize things. For suggestions/edits I'll look into starting a discussion section here in this GitHub repository.

**Comment by itsMeDavidV** [comment]
#@ttwajsb I haven't tested with pin myself, but i wouldn't doubt that the pin barrier would still present even after remote start is enabled. If your'e close enough the Tesla app will actually use a completely different way of enabling remote start (via BLE) that doesn't require a password. Watchla will soon also offer this functionality.

What error messages were you seeing during the times that you had to re-input your password?
