### ISSUE TITLE
Refresh token error

### ISSUE THREAD

**Issue by user858753257** [itsMeDavidV/Watchla-Support#51]
Hi ,

today I have seen this error in my watch app . 

How can I get a new token ?

**Comment by itsMeDavidV** [comment]
Hi @F3000 have you tried re-signing in on Watchla's iOS app? 

If you signed in with a token before v2.3 you will need to provide a new token when your old token expires. The good news is that, unlike before, with the new auth system Tesla implemented you will only have to do this once. Thereafter, Watchla will automatically refresh the token for you.

If you signed in with Tesla from the iOS app and are getting a refresh token error, please send me your Support Code via https://watchla.app/contact as that would be an indicator of a possible bug.

**Comment by itsMeDavidV** [comment]
Hi @F3000 is this issue still occurring for you?

**Comment by itsMeDavidV** [comment]
Due to the long time between responses, I'm going to assume this issue was resolved and will close it. If it's still occurring, please feel free to re-open this issue and reach out in the comments.
