### ISSUE TITLE
Watchla.app site down

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#53]
Tried several times, using different browsers, but can't access your site this morning.  Watchla comes up on Google search but all links fail. Here's a screencast:
https://user-images.githubusercontent.com/9358980/161067054-500c5733-bceb-416a-a762-ef469a5f0703.MOV

**Comment by itsMeDavidV** [comment]
Weird, thanks for reporting this. Looks to be up now. Prob just a temp server issue.

https://watchla.app

**Comment by ttwajsb** [comment]
Must be something intermittent. Just tried it five times (Safari, Chrome) and got the error once. Tested with wireless, cellular data, and combo. The once it didn't work was combo, using Safari on iPhone. 
Here's hoping it'll stabilize soon. No reply awaited.
