### ISSUE TITLE
Feature Request: Enable Camp Mode

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#54]
The Tesla app doesn't allow users to turn on Camp Mode. You have to reach to the car's screen to do so. This is a bother when you're already laying in the back and realize you forgot to turn it on. It's happened to me, then I saw a YouTube about Tesla-camping where the guy alerted campers to that limitation. If the API enables you to add this feature it's one that could be hilited (or commented) on YouTubes.

(Plus, I leave 4/14/22 for a 24-day cross country camping excursion in my Model 3, so it'd be extra cool if that was an easy fix for you! :)

**Comment by itsMeDavidV** [comment]
Unfortunately, the Tesla API isn't capable of remotely activating a climate keeper mode (eg: camp, dog, etc) and a custom alternative wouldn't be much better than just turning on climate remotely :(

**Comment by ttwajsb** [comment]
Thanks for trying!
