### ISSUE TITLE
Not on watch app list

### ISSUE THREAD

**Issue by Jesstes** [itsMeDavidV/Watchla-Support#55]
Hey! I paid for the app & downloaded yesterday, but the app doesn’t show up on my apps for Apple Watch list in the watch app. I’ve restarted, re-paired…still no way to get the app on my watch. All software is up to date.

**Comment by itsMeDavidV** [comment]
Hi @Jesstes sorry to hear that.

I would try deleting the iOS app and then re-downloading. Then, hopefully after restarting the 'Watch' app on your iOS device you should see the Watchla watch app under 'available apps'.

As an alternative, you can also download Watchla's watch app from the App Store app on your Apple Watch itself. 

It's important to note however, that if your Apple Watch and iOS device are experiencing pairing issues the iOS & watch app might not be able to communicate with each other properly which will disrupt the Watchla experience. So it's important to ensure that your Apple Watch is not facing issues with pairing. Here's a helpful link on how to tell if your watch is experiencing pairing issues: https://support.apple.com/en-us/HT205025

**Comment by itsMeDavidV** [comment]
@Jesstes were you able to resolve the issue? Given the time since last response, I'm going to assume it was resolved and close the issue. However, feel free to re-open if the issue persists.
