### ISSUE TITLE
Remote Start vs PIN to Drive

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#56]
Just noted that, having gotten in the car and tapped the brake to bring up the PIN pad, then tried to use Remote Start in Watchla (hoping to avoid tapping the PIN), after crown is spun it shows the following. There may be a better screen/message to display in that instance. (The arc blinked blue a few times before graying out.) 
![image](https://user-images.githubusercontent.com/9358980/161171034-57511e8a-4bc3-47a6-97b8-723900de88d8.png)

**Comment by itsMeDavidV** [comment]
@ttwajsb  sorry for the late reply, it's actually not meant to go gray like that, it's supposed to blink blue and green while communicating with vehicle. When it says talking to vehicle it is actually sending a command to the vehicle and waiting for response on next steps.
