### ISSUE TITLE
Apple watch does not sign in

### ISSUE THREAD

**Issue by StrictMario** [itsMeDavidV/Watchla-Support#57]
Hi, I signed in with my phone, but the watch is still not signed in. My support code is NTBc7BB6zg

**Comment by itsMeDavidV** [comment]
Hi sorry to hear about this. I'll take a look at any error logs that may be attached to your support code and get back to you here with next steps or any relevant info.

**Comment by itsMeDavidV** [comment]
Hi @ldkmarius so after looking at your error logs it looks like you aren't experiencing any issues with the Tesla api itself which leads to me believe that there was an issue between the communication from the iOS app to the watch app.

Currently the App Store version of Watchla does not have error logging for these kind of communication disruptions, however the beta does. If you'd like, I can add you to the beta to see those logs as well. If you do wish to be a part of the beta, you can drop your email here and I'll send you an invite: https://watchla.app/contact

Going forward, I'd recommend refreshing the watch app. To do that just open the iOS app, goto preferences, then tap "Refresh watch app". This will resend your authentication details to the watch app and should force a sign in.

If that doesn't work, I'd recommend re-signing in altogether.

And if the above 2 don't work I would probably venture to say you might be experiencing pairing issues between your watch and iOS device. This is something we can detect in beta.

Here's a helpful article on how to detect and address pairing issues with your Apple Watch: https://support.apple.com/en-us/HT205025

**Comment by StrictMario** [comment]
Hi @itsMeDavidV, after updating the phone, the watch, full reinstalling the app on both devices it works now. Thank you for your fast response.

**Comment by itsMeDavidV** [comment]
I'm glad to hear that! You're very welcome. Please don't hesitate to reach out if you have any questions.
