### ISSUE TITLE
Iwatch stopped connecting

### ISSUE THREAD

**Issue by adzborowski1234567890** [itsMeDavidV/Watchla-Support#59]
I watch stopped connecting after a few months of use. When tried restarting the apps did not accept my correct login

**Comment by itsMeDavidV** [comment]
Hi @adzborowski1234567890 sorry to hear that. Can you send over your Watchla support code to https://watchla.app/contact so I can see if there are any error logs that might explain why this issue is occurring for you?

Support codes can be found in the "Support" screen.

**Comment by adzborowski1234567890** [comment]
﻿Thank you, for your quick response.
Acctually i fixed it. Several minutes later i made this working. I reloaded Watchla and reset my password to Tesla
I like your apps.
Thank you.

**Comment by itsMeDavidV** [comment]
Very glad to hear that and you're very welcome. Also, thank you! Please do consider leaving a review as it really helps Watchla grow :)

Please don't hesitate to reach out if you have any other questions or feedback.
