### ISSUE TITLE
Iwatch Not Syncing with iOS App

### ISSUE THREAD

**Issue by tojayng** [itsMeDavidV/Watchla-Support#62]
My Watchla app continues to ask me to authenticate with my iOS app. Even though I have already signed on and tried refreshing several times. Also restarted all devices. Continues to not sync and requires authentication on my watch.

**Comment by itsMeDavidV** [comment]
Hi sorry to hear about this. Have you checked to see if your Apple Watch and paired iOS device are experiencing pairing issues? If so, this could explain why your Apple Watch and iOS device are not communicating your authentication status properly.

Here's a helpful article on how to detect and address pairing issues with your Apple Watch: https://support.apple.com/en-us/HT205025

Also, If you'd like to send your support code to https://watchla.app/contact I can take a look at any error logs you might have and better advise.

**Comment by itsMeDavidV** [comment]
@tojayng Are you still experiencing this issue? If so, please feel free to re-open this issue and reply back. Thanks!
