### ISSUE TITLE
Model Y requests key card for driving

### ISSUE THREAD

**Issue by Cactus1906** [itsMeDavidV/Watchla-Support#65]
Watchla installed everything locks ok. Using watchla i am able to do commands like open, close the car, open close trunk, open frunk and so on. But if i want to drive, the car requests to see the key card.

**Comment by itsMeDavidV** [comment]
Hi @Cactus1906 sorry for the late reply. Currently Watchla offers Remote Start which you can use to gain access to drive your vehicle. Just simply select the Remote Start command and follow the prompts to initiate driving capabilities.
