### ISSUE TITLE
Won't wake up

### ISSUE THREAD

**Issue by IanBurrows** [itsMeDavidV/Watchla-Support#66]
Tesla won't wake up.

**Comment by itsMeDavidV** [comment]
Hi @IanBurrows sorry to hear this and sorry for the late reply.

There could be a number of reasons why the Tesla API reports that your Tesla won't wake up. The most common are: your vehicle doesn't have a good connection to the internet or your vehicle was in deep sleep and did not wake before the Tesla API or the client app (ie: Watchla) timed out the request.

If you send me your Watchla support code here: https://watchla.app/contact I'd be happy to look at any error logs you might have and report back.

**Comment by IanBurrows** [comment]
I’ve got it working. It does take a long time to wake!

Sent from 
Ian Burrows

**Comment by itsMeDavidV** [comment]
Sweet! Good to hear. 

Wake times can take a bit longer depending on the internet connection to the vehicle.

Please don't hesitate to reach out if you experience any issues!
