### ISSUE TITLE
Entering Tesla password on Watch

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#68]
My passwords are 15 jumbled characters and it'sa real pain to have to scribble them whenever this (attd image![image](https://user-images.githubusercontent.com/9358980/181383827-0fceea14-c55c-4df3-a012-6a25df78f69b.png)) appears. Is there no way to do this authentication on the iPhone?

**Comment by itsMeDavidV** [comment]
@ttwajsb yeah that's annoying--sorry about that. One of my top priorities before v3 is to make it absolutely impossible to be signed out unintentionally. 

Did you get this error alert by chance?

![signout-error](https://user-images.githubusercontent.com/12491192/181652318-81314a53-c378-4813-983f-a1d4edc7152c.jpeg)

**Comment by itsMeDavidV** [comment]
Also going to add the ability to input RS password in iOS app

**Comment by itsMeDavidV** [comment]
> ![signout-error](https://user-images.githubusercontent.com/12491192/181652318-81314a53-c378-4813-983f-a1d4edc7152c.jpeg)

Just completely eradicated this 👆🏽 from alpha build. Still needs new messaging & adaptation, but main directive here is -> don't sign out, unless told to. This change will reflect in next App Store update.

In almost all cases, an unintentional sign out like this occurs because of a lapse in internet connectivity to the Apple Watch when trying to update/refresh one's expired token (exp happens every 8 hrs). Now you will just be told of this error but not signed out-> consistent with behavior of official Tesla app.

**Comment by ttwajsb** [comment]
I think one of the complications has to do with VPN. I find myself having to disconnect VPN every time I want to use the Tesla app. It was happening so often on my current road trip that I've finally turned off VPN for the time being—even though the protection from VPN is even more important while traveling than when at home. Anyway, you might check into whether VPN on/off is affecting the Watchla sign-in/connection situation.

**Comment by itsMeDavidV** [comment]
Good to know. Unless your VPN is in China and are a non-China user (or vice versa) you shouldn't be affected by VPN. However I'll still investigate to see if there are any other VPN related conflicts with the Tesla API.

**Comment by itsMeDavidV** [comment]
@ttwajsb quick update: looks like Tesla has taken off the password requirement for Remote Start. Watchla beta has adapted to this. Once current beta passes, no passwords will be needed in new App Store update :)

I'll close this issue when that update gets released.

**Comment by ttwajsb** [comment]
Cool. Thanks for the update.
Troy

**Comment by itsMeDavidV** [comment]
As of the [v2.96 update](https://apps.apple.com/us/app/watchla/id1546599747) passwords are no longer required for Remote Start, so closing this :)

**Comment by ttwajsb** [comment]
Great news! Thanks, David.

**Comment by itsMeDavidV** [comment]
You're very welcome!
