### ISSUE TITLE
Auto-revert from Keyless Enabled

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#69]
Please have the Watch revert to the main screen after either the keyless has been enabled on the car or the two minutes has elapsed. It's annoying that even much later when I look at my watch again it's still displaying the now-obsolete and thus useless screen instead of showing the options I may next want to use. 
Thanks as always for listening. I've been telling my Tesla pals about Watchla.

**Comment by itsMeDavidV** [comment]
Thanks for the support! And good call, I'll fix that 👍

**Comment by ttwajsb** [comment]
Still looking forward to seeing this in the Release Notes. 
T

**Comment by itsMeDavidV** [comment]
@ttwajsb sorry for lack of updates on this issue. As of version 2.96 (released mid October) Watchla now proactively updates Remote Start active/inactive states. If your Remote Start activation period ends or Remote Start has been confirmed in the vehicle, Watchla's UI will reflect that change within seconds.

**Comment by ttwajsb** [comment]
I'm on 2.98 now and at 6:50am this morning I spun the wheel to activate Remote Start. I then went out and started the car, put it in Drive, put it in Park, and 21 minutes later at 7:11am I'm still seeing the “Remote Time expired...” screen on the Watch. 
![image](https://user-images.githubusercontent.com/9358980/201695475-20cc50f4-7f16-4015-bd27-f4319dc174f7.png)

**Comment by ttwajsb** [comment]
And as you'll see here, I'm still seeing the same thing 55 minutes later. 
![image](https://user-images.githubusercontent.com/9358980/201713442-08215505-2490-426b-8d46-122da77c474a.png)

**Comment by itsMeDavidV** [comment]
@ttwajsb Yes, this is normal behavior. When you're on the Remote Start screen and your previously active Remote Start session expires, the Remote Start screen will show this message to reflect that. 

When you take the car out of park, your RS session automatically expires even if there was still time left.

**Comment by itsMeDavidV** [comment]
I suppose Watchla could also indicate an actively driving state in this screen as well--will consider that.

**Comment by ttwajsb** [comment]
This doesn't make sense to me, David. Once the car has been put in Drive, it seems that Watchla should return to its Home Screen and be available for whatever next action I want to take. What reason is there—at all—for it to remain in this state, or a similar state even if that similar state shows actively driving. What might I want or be expected to do with this screen once it's completed its action of enabling the keyless driving? Why should I have to tap to close this screen when the next thing I want to do is, say, open the frunk. I see absolutely zero advantage from keeping this in view after I've successfully enabled keyless and put the car in Drive. I made two drives yesterday and today doing errands, and when I arrived at both places and put the car in Park I was still seeing the "session expired" screen. What benefit/value/advantage is that supposed to offer me? (Well, unless I always and only want to use Watchla for remote start, in which case having that be, in effect, always and only what I see is fine—but that's not my reality.)

**Comment by itsMeDavidV** [comment]
@ttwajsb I see where you're coming from, but in addition to executing the command, the Remote Start acts as a value indicator and a full screen confirmation of whether RS is active or not. Many people don't fully understand how RS actually works and what to anticipate. After RS is initiated, it indicates auth status, how much time you have to start driving and in iOS's case how to confirm RS in car. Many users find this helpful. More-so, automatically changing screens post command execution would break continuity and disorient some users. If the user came from All Commands, how are we to assume that the user did not want to stay in All Commands and complete other tasks? This alone is something that out-weighs the value of skipping 1-2 back taps.

Now we could have an explicit setting that says on RS confirm (Shift state not park) automatically go back to home. I would definitely not be opposed. But for those that are unfamiliar, we cannot *automatically* skip the easing of confusion (with a status and time est) during the time between RS initiation and RS confirmation.

One very popular use case for RS is using RS to grant another person driving privileges from a remote location. I can only imagine that one would not want to automatically skip through RS status updates in this scenario.

I do think that reflecting RS confirmation is very much needed and not doing so is a very big misstep right now in Watchla. I'll work that in and update the UI for this.

But for advanced users, how would you feel about a setting that auto reverts back after RS initiation? 

Those like yourself, who are well familiar with RS, would have the option to skip the fluff but still rely on an active RS button state for minimal confirmation that RS is active.

**Comment by ttwajsb** [comment]
I like your statement: “... we could have an explicit setting that says on RS confirm (Shift state not park) automatically go back to home. I would definitely not be opposed.”. 

And as you indicated later in that message, enabling that as a Preference, rather than automatically, could be a good solution. 

Now that VPN no longer auto-connects to trusted networks (see update on related case sent shortly ago this morning), I thankfully experience less annoyance about this feature. However, practically speaking I'd still very much appreciate being able to have RS revert to Home once I've taken the car out of Park.

**Comment by ttwajsb** [comment]
I'll officially withdraw this request. While enabling a config option to allow user preference would still be useful, I've noticed over time that when I'm out doing errands the fact that it persists in this state reduces the number of actions required of me to resume driving. 

Thanks as always. 

PS - Just referred Watchla to another friend yesterday who got his Performance Model 3 a couple weeks ago.
