### ISSUE TITLE
Shortcuts don’t work on Apple Watch

### ISSUE THREAD

**Issue by InElonWeTrust** [itsMeDavidV/Watchla-Support#74]
Although I marked “show on Apple Watch” in my shortcut settings, my watch still doesn’t recognise any Siri command for Watchla. So for me, it makes the application rather uniseful.  All commands work on iPhone and also I can send comments by tapping on Apple Watch complications. I tried to close Shortcuts application on iPhone and also on Apple Watch and even did a hard reset. I have to mention that every other shortcut from many different apps on my iPhone works with no problem I’m Apple Watch. The only problem is with Watchla
![96A7F71C-5D8E-406F-9EBE-E8D73725F7A6](https://user-images.githubusercontent.com/114582005/192768780-a8935ff8-255f-4db3-81d2-4fa0e7609723.png)

**Comment by itsMeDavidV** [comment]
Hi @InElonWeTrust sorry to hear that. Do the Watchla Shortcuts that you added at least show up on the "Shortcuts" app on the watch?

And by chance did you look over the FAQs (https://watchla.app/faqs) and follow the instructions regarding Siri Shortcuts on Apple Watch?

I'll investigate this issue and get back you as soon as I can.

In the meantime, can you send over your support code so I can see if there are any relevant error logs that may be of any help?

**Comment by itsMeDavidV** [comment]
Hi @InElonWeTrust  just wanted to follow up with you and see if this issue is still occurring and if so were you able to locate your support code?

**Comment by InElonWeTrust** [comment]
Support code caIV46jMmjWiadomość napisana przez David Villegas ***@***.***> w dniu 01.10.2022, o godz. 00:12:﻿
Hi @InElonWeTrust  just wanted to follow up with you and see if this issue is still occurring and if so were you able to locate your support code?

**Comment by itsMeDavidV** [comment]
@InElonWeTrust I have just a few questions for you as I investigate this issue further:

- Have you tried calling the "Lock my Tesla" Siri Shortcut on your Watch? If so, any success? 
- Also is there a specific Siri Shortcut that you have tried and doesn't work or is it all Siri Shortcuts?
- You mentioned that Siri doesn't recognized the Shortcut, have you tried changing the voice phrase for the Shortcut to something different?
- Do the Watchla Shortcuts show up in the "Shortcuts" app on your watch?
- When a Siri Shortcut fails to work, do you see any error messages? If so, what are they?

**Comment by InElonWeTrust** [comment]
Apple Watch Didn’t react to any command. There were also no commands in shortcut application on Apple Watch at all, but marking Shortcuts application in iCloud settings solved the problem.The question is why the other shortcuts but the Watchla that I have, worked properly and were visible on Apple Watch. Wiadomość napisana przez David Villegas ***@***.***> w dniu 04.10.2022, o godz. 03:33:﻿
@InElonWeTrust I have just a few questions for you as I investigate this issue further:

Have you tried calling the "Lock my Tesla" Siri Shortcut on your Watch? If so, any success?
Also is there a specific Siri Shortcut that you have tried and doesn't work or is it all Siri Shortcuts?
You mentioned that Siri doesn't recognized the Shortcut, have you tried changing the voice phrase for the Shortcut to something different?
Do the Watchla Shortcuts show up in the "Shortcuts" app on your watch?
When a Siri Shortcut fails to work, do you see any error messages? If so, what are they?

**Comment by itsMeDavidV** [comment]
@InElonWeTrust I'm glad to hear that you were able to sort this out. So from what I gather, you got them to show up on Apple Watch after you did an iCloud sync?  

Unfortunately the Shortcuts app is known to be unpredictable and syncing from iOS to WatchOS sometimes does fail. This is a known issue that doesn't discriminate between Shortcuts or the apps that provide them. And apps, like Watchla, have no control over the syncing process as this is a process handled by the Shortcuts app. Hopefully Apple address this soon.
