### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by LexNastin** [itsMeDavidV/Watchla-Support#75]
Hey @itsMeDavidV! I was wondering your app Watchla has any Bluetooth support. (also, might try it within a few months if remember, bc gonna switching Android -> iPhone soon :D)

**Comment by itsMeDavidV** [comment]
Sent ya an email :)

**Comment by sheng168** [comment]
I want to know if there's "PhoneKey" support as well

**Comment by itsMeDavidV** [comment]
@sheng168 Remote Start is available on Watchla. Unfortunately I'm not at liberty to speak on the original subject matter of this issue quite yet 😉
