### ISSUE TITLE
Siri Shortcut as automation doesn't work

### ISSUE THREAD

**Issue by dlfx** [itsMeDavidV/Watchla-Support#76]
Not sure if it should become a feature request or if it's actually a bug on watchla side or even iOS...

I tried setting up an automation from the iPhone Shortcut app to "Turn On Climate" based on day of the week & time so that I don't have to manually do it in the tesla app twice a day (morning and afternoon).

When it's running the automation, it's returning this error:
INCExtensionErrorDomain error 1307

Thanks

**Comment by itsMeDavidV** [comment]
Hi @dlfx I suspect this could be a bug with the Shortcuts app.

To rule out any Watchla issues can you manually try the "Turn on Climate" Shortcut by itself without any automations, both in the Shortcuts app and via Siri?

Once you get back to me with the results of this, I should have the info necessary to investigate this further.

PS: There also could be another scenario where Shortcuts/iOS is not letting the Shortcut execute when your device is in a inactive and locked state. However, this should NOT be the case.

**Comment by dlfx** [comment]
The Turn On Climate (or any other) shortcuts I tried are working, both manually in the Shortcut app and through Siri.

As you suspected, it's not working because I was asking it to execute the automation without asking for confirmation, I just tried by telling the automation to ask before executing, and then it worked.

Apparently it has to do with trying to run without getting a confirmation in the background. Might be an iOS issue - If you rule it out on your end as not an issue, I'll try to report a bug at Apple.

**Comment by itsMeDavidV** [comment]
@dlfx yeah that's what I suspected and that most certainly would indicate a bug with iOS. 

App provided shortcuts are supported by app intents and these intents are configurable. One of the things you can configure is whether or not the intent needs user confirmation to run. The intents behind Watchla's shortcuts **Do Not**  need user confirmation to run. 

Now you can always toggle user confirmations on/off via the Shortcuts app, but by default if you don't explicitly set up a user confirmation requirement for a Watchla shortcut there should be no need to confirm.

**Comment by dlfx** [comment]
Closing as it looks to be iOS related.
