### ISSUE TITLE
(Feature request) Display charge indicator in battery state widget

### ISSUE THREAD

**Issue by user858753257** [itsMeDavidV/Watchla-Support#78]
Is this possible ?

**Comment by itsMeDavidV** [comment]
Hi @F3000 were you referring to something like this (see screenshot) or a different type of indicator?

![image](https://user-images.githubusercontent.com/12491192/200421870-180bcac6-3e09-4892-9606-5787b14eee6d.jpeg)

**Comment by user858753257** [comment]
I mean the left one in this picture . 

Maybe you can include an "flash" symbol during charging

**Comment by user858753257** [comment]
BTW: can the cat sleep with activated Homescreen widgets ?

**Comment by itsMeDavidV** [comment]
@F3000 ah okay sorry I was confused at first, but now I know what you mean. Yes I can totally add a charging active indicator.

Also just like complications on your watch, widgets will have to periodically wake your vehicle to refresh the data that is displayed. 

You can turn on Do Not Wake or Do Not Wake in Background. In the event that Widgets are not allowed to wake your vehicle, they will rely on last known data. Keep in mind though that eventually Do Not Wake being turned on might disrupt widget's ability to display up to date vehicle data

**Comment by itsMeDavidV** [comment]
@F3000 Happy to report this has been implemented in beta last week and will be pushed to the App Store app!

**Comment by itsMeDavidV** [comment]
Closing this as this has been added months ago :)
