### ISSUE TITLE
VPN must be paused to connect

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#79]
Lately I've had to switch over to Surfshark and pause my VPN in order to have Watchla work. Can anything be done to work around this? Very inconvenient. :/

**Comment by itsMeDavidV** [comment]
@ttwajsb Could be because the VPN is routed through China or another country that Tesla Servers have special considerations for. Can you send in your latest support code?

**Comment by ttwajsb** [comment]
13LbK9ztMf
I see no indication that Surfshark is sending me outside the US. I've been selecting a Los Angeles hub, and it displays my location as US. However, just now I decided to try out using a static IP in New York, and that initially seems to be allowing me to log in to Watchla even in VPN mode (though I still had to pause VPN in order to get to the Support > Other page).
So I'll leave Surfshark pointed to the NY static IP for coming days and see if I have any better luck using the Watch.
Just yesterday it worked great as I was leaving the place I'm staying, but then I had to back up 30 yards to grab my coffee cup and when I tried to use the Watch to resume driving it failed again. So weird, so damn inconsistent. I never know when it's gonna work and when not.

**Comment by itsMeDavidV** [comment]
In general, changing IPs can really throw off Tesla servers, especially while using the same auth token set. Also, as I said before there are really big factors at play here, vehicle, Tesla Servers, your watch/its paired device (& their own signal strength). Haven't gotten a chance to investigate as of yet (really backed up) but I will get to it ASAP

**Comment by ttwajsb** [comment]
I've found a nearly complete solution, David. I discovered that in Surfshark I can prevent the VPN from interrupting Watchla's connection to the car. 

In Settings > VPN Settings > [Auto-connect enabled] > Preferences > Trusted Networks I simply add the wireless networks I'm usually tapped into—including, importantly, my “Mobile network”.

Thus, in/at all these places VPN doesn't connect (which is pretty much everywhere, especially since my Verizon Cellular Data is available practically wherever I go). In at least 90% of instances Watchla is now functioning as intended and expected. Occasional/rare missed beats. 

I'm loving Watchla like I've so very much wanted to!

Perhaps you'll want to include in your Help content the advice to ensure your VPN service does not auto-connect to trusted networks?

What a relief!
![image](https://user-images.githubusercontent.com/9358980/210081211-d7e2a1b6-7b34-4aa0-a7d1-177c2fa7d991.jpeg)

You can close this ticket.
