### ISSUE TITLE
Charge status incorrect

### ISSUE THREAD

**Issue by JeremyWaring** [itsMeDavidV/Watchla-Support#8]
Hi, I thought it would be useful having the range & charge status showing on my watch face.
The app connects ok with the car & the functions all appear to work, but the range & % charge is wrong. It showed 42% this morning while I was playing with the app & waking the car up ok. Got into the car & the car was actually at 36%. Went for a run out & got back with the car at 30%. Checked the watched once back in the house & connected to Wi-fi, that had gone down to 40%, so it has moved but in no way correct.
Charge value on my phone in the Tesla app is correct at 30%.
So why is charge status not updating correctly on Watchla, or does the car have to be plugged in on charge?

**Comment by KurtSanders** [comment]
@JeremyWaring 

I just checked my Watchla (beta 1.70 (67)) and it is reflecting slightly different estimates and percentages of 2021 MY  charge/range when compared to the Tesla and Stats iPhone Apps.  Although they are not off as much as you are reporting.  I think that Watchla gets car stats from Tesla's Cloud API endpoint, I wonder if it is a API bug, car model reporting issue or Watchla app. It will be interesting to see what @itsMeDavidV determines.

**Rated Range (Percent of Battery)**
- Watchla 255 (80%)
- Tesla 256 (na%)
- Stats 243 (79%)

Here are my photos of the 3 reports of MY charge.
![IMG_9596](https://user-images.githubusercontent.com/12133562/115957234-1ad0a900-a4cf-11eb-9491-1fcf047a5f4d.PNG)
![IMG_9597](https://user-images.githubusercontent.com/12133562/115957238-1d330300-a4cf-11eb-9f55-3e01ea7c0910.JPG)
![IMG_9598](https://user-images.githubusercontent.com/12133562/115957239-1e643000-a4cf-11eb-85ad-eb2a5a218ecd.PNG)

**Comment by itsMeDavidV** [comment]
@JeremyWaring I suspect that your Tesla center display is showing estimated range. As @KurtSanders pointed out, there is a slight difference between rated and estimated range. Watchla by default shows rated range as that is the common standard. However I would be happy to add the option to toggle between the 2 in the next update of Watchla. 

Also @KurtSanders I suspect your default on the Tesla app is rated, so no problems there in regards to syncing the same endpoint with Watchla, but I'm curious as to how there's a +/- 1 mile difference. Definitely an issue in Watchla's part. 

Addressing this in next build!

**Comment by JeremyWaring** [comment]
@itsMeDavidV @KurtSanders 

Thanks for your input & suggestions.
David I think that’s the answer. In retrospect I’m sure I made an assumption regarding the relative percentage charge rather than actually checking so percentages are probably the same, but yes I always rely on estimated range rather than rated range (particularly with the battery now being several years older) so an option in the next update to select estimated range would be great for me. Please let me know when you are likely to roll this out.

Just for interest, here’s the difference between Watchla & Tesla - maybe I should drive with a lighter foot! 🙂

![C94892CE-4314-4128-BF01-33E97BD4E3EC](https://user-images.githubusercontent.com/83119150/115988731-f817c080-a5b2-11eb-96c4-e2fbb88b4dbe.jpeg)

**Comment by itsMeDavidV** [comment]
@JeremyWaring Good news, just added est. range compatibility to Watchla. Instead of a toggle, Watchla will automatically know which type of range to display based on your vehicle's GUI settings. 

This new feature will be included in the next beta build and will hopefully be out in the App Store update (v 1.70) either Monday or Tuesday, if everything goes well with App Store review. I'll close this issue when the update passes review and the update is released.

Thanks for pointing this out!

**Comment by JeremyWaring** [comment]
@itsMeDavidV
That is good news! Great work & thanks for the quick response.
I look forward to the update. 👍

**Comment by KurtSanders** [comment]
Dear @itsMeDavidV 

I really like all the enhancements you have added to version 1.70 (68).  The Tesla App and Watchla Charge Rated Range for the MY are within 1 mile of each other (good enough for me 🥇 ) and charge % are identical.

One thing I noticed this morning with the new version is that the Watchla's charge status icon (which I like ) appears to indicate that the MY's charge port is 'locked' when the MY is charging.  Does that match what you expected so that one can "unlock the charge port" remotely from Watchla?  

![Library - 1 of 3](https://user-images.githubusercontent.com/12133562/116079523-e3483500-a665-11eb-9599-b4860fb756c5.jpeg)
![Library - 2 of 3](https://user-images.githubusercontent.com/12133562/116079525-e4796200-a665-11eb-8226-e9cbe8844d48.jpeg)

**Comment by itsMeDavidV** [comment]
@KurtSanders Really glad to hear that!

So you are right, that lock icon on the charge port button denotes that the charge port is engaged and tapping that button would unlock the charge port. Also if the car is actively charging when you tap that button, Watchla will automatically stop charging and unlock the charge port in sequence. This was a huge must-have request by a lot of users.

I laid the ground work for these alert bubbles in the this update, so there will be more to come for different command buttons. Currently, if you put the windows down, the windows home screen command button will show a bubble that states the percentage that the windows are down. More to come!

**Comment by itsMeDavidV** [comment]
@JeremyWaring Thank you and you're very welcome!

**Comment by itsMeDavidV** [comment]
Just updating this thread to say that the update (v1.70) was released yesterday!

**Comment by JeremyWaring** [comment]
Hi David,

Thanks for the status update (& Watchla update!)

I’m still getting a discrepancy with the typical range shown on the car & Tesla app, and that shown on Watchla.

For some reason the Watchla range isn’t as shown on the GUI, but it’s now showing less than the typical estimated range shown on Tesla per the photo.

This has been the case for the past day after a number of refreshes and a couple of charges to see if it corrects itself, which it hasn’t.

Any ideas?

Thanks,
Jeremy

***@***.***D73CDB.A00AB680]



From: David Villegas ***@***.***>
Date: Wednesday, 28 April 2021 at 23:54
To: itsMeDavidV/Watchla-Support ***@***.***>
Cc: Jeremy Waring ***@***.***>, Mention ***@***.***>
Subject: Re: [itsMeDavidV/Watchla-Support] Charge status incorrect (#8)

Just updating this thread to say that the update (v1.70) was released yesterday!

**Comment by itsMeDavidV** [comment]
Hi @JeremyWaring sorry to hear that. Is this still happening? If so, can you provide the range showed on Watchla and the range showed on the Tesla app?

**Comment by JeremyWaring** [comment]
Hi David,

Please see photo.

[cid:A8462B24-17D0-4017-BADE-1A787F448CBC-L0-001]

As I type this Watchla now shows 96 miles, Tesla 109 miles, so Watchla is consistently lower.

Thanks,
Jeremy


Sent from iPhone

On 1 May 2021, at 06:16, David Villegas ***@***.***> wrote:

﻿

Hi @JeremyWaring<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeremyWaring&data=04%7C01%7Cjeremy.waring%40icsluk.com%7Cb4ae41c70f0c4e381a4008d90c604d3d%7C2a9e69a32a004dbf9737d1dd7101c2eb%7C0%7C0%7C637554430026588292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3ymbLDrBU%2Bwcuq%2FFclNMPZsby3iIAuvfr8sqMVOaSvk%3D&reserved=0> sorry to hear that. Is this still happening? If so, can you provide the range showed on Watchla and the range showed on the Tesla app?

**Comment by itsMeDavidV** [comment]
@JeremyWaring Interesting so its the 88% discrepancy that you see between rated vs estimated but in reverse. I will get to the bottom of this and update you when there is a solution. Is this still happening as of today?

**Comment by JeremyWaring** [comment]
@***@***.***> yes still happening.

Right now I've just arrived at work and plugged in, Tesla car & Tesla app show 50 miles, Watchla shows 44 miles so you're spot on with the 88% discrepancy!

Thanks,
Jeremy

**Comment by itsMeDavidV** [comment]
@JeremyWaring I may have a solution and would like to add you to the beta to see if it works before putting it to production. If you're up for being in the beta, would you mind sending me your email to david@villegasventures.co so that I can add you in?

(If you don't want to be in the beta, no worries)

**Comment by itsMeDavidV** [comment]
@JeremyWaring I've just introduced v1.90 (72) into beta which contains a possible solution for your range discrepancy issue.

And @KurtSanders I also included a fix to the +/- 1 mile range discrepancy issue that you experienced.

Once I validate this build with you both, I will roll it out to the rest of the beta and put it in the line up for the next App Store update.

Hope it works, let me know how it goes 🤞

**Comment by JeremyWaring** [comment]
@itsMeDavidV @KurtSanders 

I’ve received V1.90 (72) beta which has updated my watch, and pleased to say the range now showing is identical on both Watchla and Tesla apps, so all looking good from my perspective. 👍

**Comment by KurtSanders** [comment]
I can also confirm this last beta release fixed accurate range mileage between Watchla and Tesla app.

**Comment by itsMeDavidV** [comment]
@JeremyWaring @KurtSanders That's great to hear! 

Thanks to both of you for quick responses. I've now rolled out build 72 to all of the beta and I'll close this once 1.90 makes it to the App Store in case anyone else comes across this issue before then.
