### ISSUE TITLE
Watch complications have no icon

### ISSUE THREAD

**Issue by amy26point2** [itsMeDavidV/Watchla-Support#80]
I have uninstalled and reinstalled the app. The watch face I have with the Watchla complications is showing just dotted lines where the complication icon should be. If I edit the watch face from the watch, the only complications showing icons are vehicle status, battery state, range, and climate status. All others are blank.

**Comment by itsMeDavidV** [comment]
Hi @amy26point2 thanks for reporting this, that's concerning. Can you please send over your Watchla support code to my email: david@watchla.app and can you please post a video of this behavior happening to this comment thread?

**Comment by amy26point2** [comment]
Here is a video of the watch complications. Apologies for the one handed shooting. As you can see, the behavior of the complications work but the icon is blank. The photo is the setup. 
![A7438998-CE41-4942-B0B4-5346D70993B9](https://user-images.githubusercontent.com/77081911/202073236-964fa2e8-c9f9-4815-a03e-37a71deb4db0.png)
 [Video](https://share.icloud.com/photos/0d2iySsNa8sqpNxv-Zi6dLfkQ)

**Comment by itsMeDavidV** [comment]
Edit: There's been a correction to this, please see my comment below.

@amy26point2 Thanks for that, this helps a lot.

I do believe that you have discovered an asset bug that only affects Apple Watch Ultra users (Apple Watch Ultra has a different set of asset requirements for complications than other Apple Watches)

I will work on a fix ASAP and push out an update with the fix to the App Store as soon as I can.

Thanks again for reporting this and sorry for the inconvenience.

**Comment by itsMeDavidV** [comment]
@amy26point2 Sorry correction:

In your particular case you are not experiencing the bug mentioned above (after investigation its been determined that bug only applies to a small subset of available watch faces) That bug has been corrected and will be included in next update.

So unfortunately this is more isolated to your case. I will investigate further and report back to you ASAP.

Thank you for your patience, sorry again for the inconvenience.

**Comment by amy26point2** [comment]
Thanks, David! At least it helped you solve one issue. No need to rush on my behalf.

**Comment by itsMeDavidV** [comment]
@amy26point2 you're very welcome!

For some reason the iCloud link you attached containing the video isn't playing and is only showing a photo. Could you re-upload that video directly to GitHub here in this comment thread?

Thanks!

**Comment by amy26point2** [comment]
I’ve tried shrink the video to numerous sizes and it will not upload. Can I email it to you?

**Comment by itsMeDavidV** [comment]
@amy26point2 Yes that works also!

**Comment by itsMeDavidV** [comment]
Hi @amy26point2 I had a TestFlight invite to Watchla's beta emailed over to you. The current Watchla beta app contains Apple Watch Ultra specific fixes and I'd love to see if these fixes solve your issue.

I also sent you an email with more info on this that you might find helpful.

Thanks!

**Comment by itsMeDavidV** [comment]
Hi @amy26point2 just wanted to let you know that I was finally able to reproduce your exact issue and a fix has been developed and implemented. The fix will be available in the next update v2.99 which should be out in the coming days (give or take a few bc of Thanksgiving).

Sorry again for this inconvenience.

**Comment by amy26point2** [comment]
That’s great! Thanks so much for working on the issue. I’m looking forward to using my driving watch face again.

**Comment by gsy0402** [comment]
Hi when will v2.99 out? I have 3 Watchla complications on a watch face and all 3 have been like “- -“ for a while which is really annoying… thanks…

**Comment by itsMeDavidV** [comment]
@gsy0402  Very soon. Most likely today or tomorrow, depending on how long Apple takes to review v2.99

**Comment by itsMeDavidV** [comment]
@amy26point2 @gsy0402 and whom it may concern, v2.99 was just released. It contains the fix for this issue. It may take 30 minutes or so from the time of this comment to be available in the App Store. Sorry again for the inconvenience this has caused.

-David

**Comment by amy26point2** [comment]
Thanks David! Once I uninstalled the watch app and reinstalled it all the complications now show properly.

**Comment by itsMeDavidV** [comment]
You're very welcome! I'm glad it's working now :) 

Thank you for your patience on this!
