### ISSUE TITLE
Tesla Model E will not do a remote start from App

### ISSUE THREAD

**Issue by GalinL** [itsMeDavidV/Watchla-Support#81]
Just paired my Apple Watch Ultra to a 2018 Model 3.  When I execute remote start and follow instruction to “spin steering wheel” to start the Tesla, the car will not start.

**Comment by itsMeDavidV** [comment]
@GalinL sorry to hear that, can you please include your Watchla Support code so I can check any error logs that might point to a cause for the issue?

Thanks,
-David

**Comment by GalinL** [comment]
Hi David.  Thank you.  Where do I find the Watchla Support Code?

Sent from my iPhone

Galin Luk


On Nov 19, 2022, at 11:10 AM, David Villegas ***@***.***> wrote:

﻿

@GalinL<https://github.com/GalinL> sorry to hear that, can you please include your Watchla Support code so I can check any error logs that might point to an issue?

Thanks,
-David

**Comment by GalinL** [comment]
Hi David.  Found the code.  Here it is:

DGPGo7rW94

Sent from my iPhone

Galin Luk


On Nov 19, 2022, at 11:30 AM, galin Luk ***@***.***> wrote:

﻿ Hi David.  Thank you.  Where do I find the Watchla Support Code?

Sent from my iPhone

Galin Luk


On Nov 19, 2022, at 11:10 AM, David Villegas ***@***.***> wrote:

﻿

@GalinL<https://github.com/GalinL> sorry to hear that, can you please include your Watchla Support code so I can check any error logs that might point to an issue?

Thanks,
-David

**Comment by itsMeDavidV** [comment]
@GalinL Perfect, I will take a look at any error logs that might exist and report back here.

Sorry for the inconvenience and thanks for your patience.

**Comment by GalinL** [comment]
Thank you David.

FYI: after a failed attempt at starting the car, I did a hard reset of the Tesla and reset my phone and watch.  Then I tried executing the start command again. No luck.

Sent from my iPhone

Galin Luk


On Nov 19, 2022, at 11:43 AM, David Villegas ***@***.***> wrote:

﻿

@GalinL<https://github.com/GalinL> Perfect, I will take a look at any error logs that might exist and report back here.

Sorry for the inconvenience and thanks for your patience.

**Comment by GalinL** [comment]
Hi David,

The remote start does work.  The instructions on the watch led me to believe I had to turn the steering weel to start the car [the instructions say "spin the wheel to  start driving".  I just figured out the "wheel" is the "crown".  I can't believe I'm the only idiot who just realized this...perhaps, it'd be good to clarify this on the app [to "Spin the crown"].

Thanks!

Galin


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by itsMeDavidV** [comment]
@GalinL no worries! I was a little confused when I didn't find any error logs that were remote start errors so I'm glad to hear that everything ended up working. Sorry about the confusion, I might have to consider changing the wording!
