### ISSUE TITLE
Regarding Tesla app/watch being a key

### ISSUE THREAD

**Issue by swinneyj** [itsMeDavidV/Watchla-Support#85]
Is this a current feature? I want to be able to take the car and drive it without the need for the phone. If for example the phone is dead. Is this something that’s possible or is it being worked out? I tried to shift into drive, but it still required me to have the phone with me as a key.

**Comment by itsMeDavidV** [comment]
This is now possible with the release of v3 :)

Watchla can now be used as a Bluetooth key for your Tesla, making it possible for you to not have to bring a phone or keycard to unlock and drive.
