### ISSUE TITLE
Apple watch: to sign in

### ISSUE THREAD

**Issue by roarskaare** [itsMeDavidV/Watchla-Support#86]
Not able to get app working on apple watch.
Message received when starting app on iphone: To sign in.
I am signed in on Apple iphone Watchla app.![image](https://user-images.githubusercontent.com/120064285/206419227-a9845ac4-8099-441b-8ee0-67273e2eb63b.jpeg)![image](https://user-images.githubusercontent.com/120064285/206419373-a2dc759c-439d-4c1b-b9a6-197d9135d956.png)

**Comment by itsMeDavidV** [comment]
Hi @roarskaare sorry to hear about this. You might be experiencing a pairing issue that is disrupting the communication of your authentication status from the Watchla iOS app to the Watchla watch app.

Here’s a helpful link on how to tell if you are experiencing pairing issues and if so how to remedy the issue: https://support.apple.com/en-us/HT205025

Additionally, if you send your Watchla Support code over via https://watchla.app/contact I'd be happy to look at any relevant error logs you might have and report back on what exactly is going on.

**Comment by roarskaare** [comment]
Case closed after ios update 16.1.2 or reboot ios phone.

**Comment by itsMeDavidV** [comment]
Very happy to hear that! Closing this issue.
