### ISSUE TITLE
Charge complication shows 0% almost always

### ISSUE THREAD

**Issue by malmentm** [itsMeDavidV/Watchla-Support#88]
Hello. I got a problem with the charge % complication on my watch face. Is says always 0% until I click on the complication and the watch fetches data. It does not matter if I have wake disable or not. If this is a delay or slow wake of the car would it not be better to show least the last know charge level instead of 0? Doesn't help to have can in sentry mode either, not connections issues either, I live in the city with good cellular connectivity

**Comment by itsMeDavidV** [comment]
Hi @malmentm sorry to hear that. Can you please send your Watchla support code here: https://watchla.app/contact/ so I can investigate any error logs that may be attached to it then and get back to you.

Your Watchla support code can be found by going to Preferences -> Support/Feedback -> Support Code

Thanks!
-David

**Comment by dwhes** [comment]
I have the same bug.

**Comment by mape01** [comment]
I have the same issue.

**Comment by itsMeDavidV** [comment]
@dwhes @mape01 sorry to hear that. Quick question do you both also keep Sentry mode on or do you leave it off at the time this error occurs. Also could you send in your Support Codes as well so error data can be gathered for this issue. Thanks!

**Comment by mape01** [comment]
Hi,I also have submitted a message via contact Formular.Sorry for double posting. I do not use sentry mode at the moment, so this should be no problem. I use „do not wake“ that the app isn’t waking the car every time the app is opened. But when the car is online the states would be actualised anyway, right?Br,Markus

**Comment by dwhes** [comment]
I can’t confirm all occasions but definitely occurring when sentry mode is off. As I don’t have sentry enabled when I’m at work or at home as it uses too much battery and it’s secure where I’m parking. I sent my support code in with the report I did on this issue and the select vehicle bug. Cheers

**Comment by itsMeDavidV** [comment]
Hi @malmentm @mape01  & @dwhes I just wanted to let you know that a new update (v3.02) that addresses this issue has been released earlier today.

You can update here: https://apps.apple.com/us/app/watchla/id1546599747

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
