### ISSUE TITLE
Keeps prompting me to select a vehicle

### ISSUE THREAD

**Issue by dwhes** [itsMeDavidV/Watchla-Support#89]
Updated to the beta 3.0 yesterday. Have set my watch up as a phone key to the car (seems to work great by the way!). Since this new update though after a period of time of not using the Watch app and potentially after having driven the car. If then open the Watch app it will display a message saying selected vehicle not found. If I hit ok it then immediately loads my vehicle as normal. Never had this issue before 3.0? 

Is it something to do with the app changing between Bluetooth key to normal internet based?

![34244E39-232A-4A78-BEED-6B49268C5909](https://user-images.githubusercontent.com/121735431/210156425-a25220c8-2add-46f8-97eb-05d1228a7600.jpeg)

**Comment by itsMeDavidV** [comment]
This is a known issue in beta and a fix is being developed. Thanks for reporting this!

**Comment by itsMeDavidV** [comment]
A fix for this issue has been completed and will be in beta by end of day PST :)

**Comment by dwhes** [comment]
Thanks!!
