### ISSUE TITLE
Model x Refresh no door function

### ISSUE THREAD

**Issue by RourkeModelX** [itsMeDavidV/Watchla-Support#90]
Hey guys,

I’ve been testing the watchla app and have been loving it so far.

I saw that 3.0 had a potential feature to open doors, which is very exciting as I’ve been wanting to use my watch complications to control my model x refresh’s doors.

Is that option showing up for anyone else?

**Comment by itsMeDavidV** [comment]
Hi @RourkeModelX, sorry for the late reply. Watchla has been swamped with messages as of late. I've seen your email and will send over a reply shortly.

Sorry about that and thanks for your patience!

-David

**Comment by scottharr27** [comment]
I would love to know if the app controls Model X doors as well

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
