### ISSUE TITLE
"Unlock door" function

### ISSUE THREAD

**Issue by Eldoc62** [itsMeDavidV/Watchla-Support#93]
Hello,

In the TESLA application I have the function "Unlock the door"

Is it possible to find it in the WATCHLA application in order to have the command function by Siri?

Thank you for your help

**Comment by itsMeDavidV** [comment]
Yes! Just goto the Watchla iOS app, open Preferences -> Shortcuts and then search for "Unlock my Tesla" then just add the shortcut when prompted! 

From there, open the Shortcuts app and in the shortcut's settings and make sure to enable "Show on Apple Watch".

There is a full run down on Watchla's FAQs list here: https://watchla.app/faqs that detail how to setup and use Watchla's Siri Shortcuts!

Hope this helps, please feel free to reach out with any questions.

-David

**Comment by Eldoc62** [comment]
ok for unlock all but i want just open my door, the same on Tesla app. You Know 
? 

[2FB3BF7E-0890-4E0D-8218-5DF0E35B73ED](https://user-images.githubusercontent.com/31630516/212830673-65e839aa-c4e5-42c1-98c3-ebc2ed6b272b.jpeg)

**Comment by itsMeDavidV** [comment]
Ah your referencing door unlatch. This is different than door unlock in that it actually opens the door. You can do this on Watchla by going to All Commands -> Open Doors. You can also add Open Doors to your custom layout in the Home Screen. 

In Open Doors you can open any door or all of them at once.

Keep in mind, you will need to setup Bluetooth on Watchla before hand for this to work.

**Comment by Eldoc62** [comment]
Realy really good job !!

It's ok for connect my Apple watch to my Tesla :)

Do you think it's possible to create siri shortcut for open the doors ?

**Comment by itsMeDavidV** [comment]
> Do you think it's possible to create siri shortcut for open the doors ?

Thank you! Yes that's coming ;)

**Comment by Eldoc62** [comment]
👍👍👍👍👍Envoyé de mon iPhoneLe 21 janv. 2023 à 19:04, David Villegas ***@***.***> a écrit :﻿
Yes that's coming ;)
