### ISSUE TITLE
Incorrect support of BLÉ key when used with multiple cars

### ISSUE THREAD

**Issue by jyavenard** [itsMeDavidV/Watchla-Support#94]
You can select different vehicle, but you can only have one BLE key. 

Step to reproduce:
Have two Tesla linked on your account. 
In Watchla select a car.
Go to the Bluetooth preferences and set a new BLE key. 
Go back and select another car. 
Go to BLE preferences; the previous car BLE key is showing as connected. 

You can’t set a new one

**Comment by itsMeDavidV** [comment]
@jyavenard thanks for reporting this and sorry about that! 

A fix for this issue has been made and should make it to the App Store in update version 3.01 sometime tomorrow PST if all goes well with App Store review.

**Comment by jyavenard** [comment]
That’s great news. 

Something that has been happening a few times to and when attempting to switch cars, the list shows as empty. 

Another great feature would be the ability to set keys without having to log in into the Tesla account. 

Can create another issue

**Comment by itsMeDavidV** [comment]
Update v3.01 is now out and it should fix this issue. If you continue to experience this issue after updating, please re-open this and let me know. Thanks again for reporting this!

**Comment by jyavenard** [comment]
Verified as working
