### ISSUE TITLE
On left hand drive car; screen shown for opening door incorrect

### ISSUE THREAD

**Issue by jyavenard** [itsMeDavidV/Watchla-Support#97]
When you have a left hand drive car (such as available in UK, Japan or Australia); if you use the right right icon to open the door, it opens the rear left side instead.

**Comment by itsMeDavidV** [comment]
@jyavenard thanks for pointing this out and sorry about that. This will be fixed in v3.02 follow-up update in the coming days.

**Comment by itsMeDavidV** [comment]
Hi @jyavenard I just wanted to let you know that v3.02 was released earlier today which fixes this issue.

You can update here: https://apps.apple.com/us/app/watchla/id1546599747
