### ISSUE TITLE
Should have the ability to use BT key without the need for Tesla login details

### ISSUE THREAD

**Issue by jyavenard** [itsMeDavidV/Watchla-Support#98]
Right now, you can't use the app without first logging into the Tesla account

Only then can you set BT keys. 

If you have set-up a key, and have disable wake the car option, you are prompted to wake the car which isn't possible if you're in an area without network connectivity.

The use of BT commands shouldn't require access to the car over data (Wi-Fi or cellular)

**Comment by itsMeDavidV** [comment]
@jyavenard I hear what you're saying but on the contrary, this is a security step in of itself. When you sign into Watchla, Watchla is able to verify vehicle information and match it to vehicles nearby that it communicates with over Bluetooth. This allows Watchla to only connect to authorized vehicles.

If sign in was not required, bad actors with temporary access to a key card (like a renter for example) could use Watchla to gain unlimited access to the vehicle beyond the scope that the owner granted for them.

I believe this is why this is also not possible on the Tesla app.

**Comment by jyavenard** [comment]
You can do this with a Tesla keyfob already. Which works as both a keycard and a BTLE key. 
 
There are other apps on the app store working exactly as I described. 

Without internet connectivity, you also can't switch vehicles to access the key for another vehicle. But this probably should be a bug on its own.

**Comment by jyavenard** [comment]
What about this for an alternative: need to login to Tesla account to retrieve list of cars, but store the keys and give the ability to choose between multiple keys without having to switch vehicles first. 

Lately we’ve been going with two cars in an area with extremely poor mobile coverage. This has prevented the ability to switch cars as it shows no car in the list if there’s no network. 
And as such, I could only unlock one car. The one I first selected when network coverage was present

**Comment by itsMeDavidV** [comment]
> Without internet connectivity, you also can't switch vehicles to access the key for another vehicle. But this probably should be a bug on its own.

I see. This is certainly an issue. I'll see how the solution to this can be implemented and get back to you that. But ultimately yes, I'll add in the ability to select another vehicle while offline so that you can comfortably switch back and forth in the scenario mentioned above. Thanks for proposing that!

**Comment by itsMeDavidV** [comment]
Maybe even add an auto detect for this as well (eg: you are near or inside a non selected vehicle (that you own) and your Selected Vehicle is not nearby, Watchla will ask if you want to switch)

**Comment by jyavenard** [comment]
That sounds great !

**Comment by itsMeDavidV** [comment]
Hey @jyavenard sorry for the late reply. Just wanted to update you and let you know that in v3.4 ([released last Friday](https://twitter.com/WatchlaApp/status/1629265291514466311?s=20)) you can now select different vehicles while offline! This will allow you to control multiple vehicles via Bluetooth while offline. 

Please do let me know how it goes for you and thank you for your feedback on this :)
